package io.github.amichne.kast.appserver.core

internal enum class ProviderFailureCode {
    UNEXPECTED_FAILURE,
    IDE_CONFIGURATION_REJECTED,
    IDE_INVALID_NAME,
    IDE_INVALID_REQUEST,
    IDE_HOST_UNAVAILABLE,
    IDE_DESCRIPTOR_REJECTED,
    IDE_RESPONSE_REJECTED,
    IDE_REQUEST_TOO_LARGE,
    IDE_DEADLINE_EXCEEDED,
    IDE_TRANSPORT_REJECTED,
    IDE_SCHEMA_UNAVAILABLE,
    IDE_OPERATION_UNSUPPORTED,
    IDE_APPROVAL_REQUIRED,
    IDE_APPROVAL_REJECTED,
    WORKSPACE_START_UNAVAILABLE,
    WORKSPACE_START_NOT_DIRECTORY,
    WORKSPACE_ROOT_MARKER_NOT_FOUND,
    WORKSPACE_INVALID_ROOT_MARKER,
    TIMED_OUT,
    IO_REJECTED,
    OUTPUT_LIMIT,
    SPAWN_FAILED,
    TERMINATED,
    KAST_QUALIFICATION_FAILED,
    KAST_CONTRACT_CHANGED,
    KAST_ARGUMENT_NOT_SCALAR,
    MALFORMED_KAST_OUTPUT,
    APPROVAL_REQUIRED,
    APPROVAL_BINDING_REJECTED,
    GRADLE_WRAPPER_UNAVAILABLE;

    val value: String
        get() = name
}
