package support.delivery

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@Serializable
private data class Kvp015EpochLedgerDocument(
    val schemaVersion: Int,
    val authority: Kvp015ReportAuthority,
    val ideBuild: String,
    val signals: List<Kvp015SignalDocument>,
    val rejectedConstantZeroAuthorities: List<String>,
    val cases: List<Kvp015CaseDocument>,
    val vfsRefreshCount: Int,
    val gradleImportCount: Int,
    val repositoryWalkCount: Int,
    val sourceHashCount: Int,
    val semanticJobCount: Int,
    val edtWorkCount: Int,
    val blockingWaitCount: Int,
)

@Serializable
private data class Kvp015SignalDocument(
    val category: Kvp015SignalCategory,
    val authorities: List<String>,
    val observation: String,
    val movement: String,
)

@Serializable
private data class Kvp015CaseDocument(
    val caseId: Kvp015CaseId,
    val sampleCount: Int,
    val movedSignals: List<Kvp015SignalCategory>,
    val projectModelTransitions: List<Kvp015ProjectModelTransition>,
    val dumbModeSamples: List<Kvp015DumbModeState>,
    val dumbModeTransitions: List<Kvp015DumbModeTransition>,
    val vfsEventCount: Int,
    val expectedRelation: Kvp015SampleRelation,
    val observedRelation: Kvp015SampleRelation,
)

@Serializable
private enum class Kvp015ReportAuthority { READ_EPOCH }

@Serializable
private enum class Kvp015SignalCategory {
    PROJECT_MODEL,
    PSI,
    VFS,
    ROOT_MODEL,
    DUMB_MODE,
}

@Serializable
private enum class Kvp015CaseId {
    STABLE,
    WORKSPACE_MODEL_MOVEMENT,
    GRADLE_IMPORT_STARTED,
    GRADLE_IMPORT_COMPLETED,
    GRADLE_ROOT_MOVEMENT,
    PSI_MOVEMENT,
    VFS_MOVEMENT,
    ROOT_MODEL_MOVEMENT,
    SMART_DUMB_SMART,
    COMBINED_MOVEMENT,
    VFS_EVENT_STORM,
}

@Serializable
private enum class Kvp015ProjectModelTransition {
    WORKSPACE_MODEL_CHANGED,
    GRADLE_IMPORT_STARTED,
    GRADLE_IMPORT_COMPLETED,
    GRADLE_ROOT_CHANGED,
}

@Serializable
private enum class Kvp015DumbModeState { SMART, DUMB }

@Serializable
private enum class Kvp015DumbModeTransition { SMART_TO_DUMB, DUMB_TO_SMART }

@Serializable
private enum class Kvp015SampleRelation { UNCHANGED, CHANGED }

internal enum class Kvp015EpochLedgerReportFailure {
    MALFORMED_DOCUMENT,
    NON_CANONICAL_DOCUMENT,
    SCHEMA_VERSION_MISMATCH,
    AUTHORITY_MISMATCH,
    IDE_BUILD_MISMATCH,
    SIGNAL_SET_MISMATCH,
    CONSTANT_ZERO_AUTHORITY_NOT_REJECTED,
    CASE_SET_MISMATCH,
    SAMPLE_COUNT_MISMATCH,
    STORM_EVENT_COUNT_MISMATCH,
    CASE_EXPECTATION_MISMATCH,
    FORBIDDEN_EFFECT_OBSERVED,
}

internal class AdmittedKvp015EpochLedgerReport private constructor(
    val canonicalDocument: String,
    val authority: String,
    val ideBuild: String,
    val signalCount: Int,
    val caseCount: Int,
    val sampleCount: Int,
    val stormEventCount: Int,
) {
    companion object {
        /**
         * Proof transition: `String -> Kvp015EpochLedgerReportAdmission`.
         *
         * Establishes canonical generated bytes for the exact IDEA-262 READ_EPOCH signal and case
         * ledger. The admitted report proves ordered signal authority, two samples per case, every
         * required movement, rejection of constant-zero VFS manager counters, the 1,000-event
         * storm, and zero forbidden stronger effects. [Kvp015EpochLedgerReportFailure] closes every
         * expected report failure; raw JSON may leave only at this Gradle receipt boundary.
         */
        fun admit(raw: String): Kvp015EpochLedgerReportAdmission {
            val document = try {
                EPOCH_LEDGER_JSON.decodeFromString(Kvp015EpochLedgerDocument.serializer(), raw)
            } catch (_: SerializationException) {
                return rejected(Kvp015EpochLedgerReportFailure.MALFORMED_DOCUMENT)
            } catch (_: IllegalArgumentException) {
                return rejected(Kvp015EpochLedgerReportFailure.MALFORMED_DOCUMENT)
            }
            val expectedCases = canonicalCases()
            val failure = when {
                document.schemaVersion != SCHEMA_VERSION ->
                    Kvp015EpochLedgerReportFailure.SCHEMA_VERSION_MISMATCH
                document.authority != Kvp015ReportAuthority.READ_EPOCH ->
                    Kvp015EpochLedgerReportFailure.AUTHORITY_MISMATCH
                document.ideBuild != IDE_BUILD ->
                    Kvp015EpochLedgerReportFailure.IDE_BUILD_MISMATCH
                document.signals != canonicalSignals() ->
                    Kvp015EpochLedgerReportFailure.SIGNAL_SET_MISMATCH
                document.rejectedConstantZeroAuthorities != CONSTANT_ZERO_VFS_AUTHORITIES ->
                    Kvp015EpochLedgerReportFailure.CONSTANT_ZERO_AUTHORITY_NOT_REJECTED
                document.cases.map(Kvp015CaseDocument::caseId) !=
                    expectedCases.map(Kvp015CaseDocument::caseId) ->
                    Kvp015EpochLedgerReportFailure.CASE_SET_MISMATCH
                document.cases.any { case -> case.sampleCount != SAMPLES_PER_CASE } ->
                    Kvp015EpochLedgerReportFailure.SAMPLE_COUNT_MISMATCH
                document.cases.singleOrNull {
                    case -> case.caseId == Kvp015CaseId.VFS_EVENT_STORM
                }?.vfsEventCount != STORM_EVENT_COUNT ->
                    Kvp015EpochLedgerReportFailure.STORM_EVENT_COUNT_MISMATCH
                document.cases != expectedCases ->
                    Kvp015EpochLedgerReportFailure.CASE_EXPECTATION_MISMATCH
                document.forbiddenEffectCounts().any { count -> count != 0 } ->
                    Kvp015EpochLedgerReportFailure.FORBIDDEN_EFFECT_OBSERVED
                else -> null
            }
            if (failure != null) return rejected(failure)
            val canonical = EPOCH_LEDGER_JSON.encodeToString(
                Kvp015EpochLedgerDocument.serializer(),
                document,
            ) + "\n"
            if (raw != canonical) {
                return rejected(Kvp015EpochLedgerReportFailure.NON_CANONICAL_DOCUMENT)
            }
            return Kvp015EpochLedgerReportAdmission.Admitted(
                AdmittedKvp015EpochLedgerReport(
                    canonical,
                    document.authority.name,
                    document.ideBuild,
                    document.signals.size,
                    document.cases.size,
                    document.cases.sumOf(Kvp015CaseDocument::sampleCount),
                    document.cases.single {
                        case -> case.caseId == Kvp015CaseId.VFS_EVENT_STORM
                    }.vfsEventCount,
                ),
            )
        }
    }
}

internal sealed interface Kvp015EpochLedgerReportAdmission {
    data class Admitted(
        val report: AdmittedKvp015EpochLedgerReport,
    ) : Kvp015EpochLedgerReportAdmission

    data class Rejected(
        val failure: Kvp015EpochLedgerReportFailure,
    ) : Kvp015EpochLedgerReportAdmission
}

@CacheableTask
abstract class GenerateKvp015EpochLedgerReportTask : DefaultTask() {
    @get:OutputFile
    abstract val reportFile: RegularFileProperty

    /** Writes the canonical generated KVP-015 READ_EPOCH characterization ledger. */
    @TaskAction
    fun generate() {
        writeTextAtomically(reportFile.get().asFile.toPath(), canonicalKvp015EpochLedgerReport())
    }
}

private fun canonicalKvp015EpochLedgerReport(): String = EPOCH_LEDGER_JSON.encodeToString(
    Kvp015EpochLedgerDocument.serializer(),
    Kvp015EpochLedgerDocument(
        schemaVersion = SCHEMA_VERSION,
        authority = Kvp015ReportAuthority.READ_EPOCH,
        ideBuild = IDE_BUILD,
        signals = canonicalSignals(),
        rejectedConstantZeroAuthorities = CONSTANT_ZERO_VFS_AUTHORITIES,
        cases = canonicalCases(),
        vfsRefreshCount = 0,
        gradleImportCount = 0,
        repositoryWalkCount = 0,
        sourceHashCount = 0,
        semanticJobCount = 0,
        edtWorkCount = 0,
        blockingWaitCount = 0,
    ),
) + "\n"

private fun canonicalSignals(): List<Kvp015SignalDocument> = listOf(
    Kvp015SignalDocument(
        Kvp015SignalCategory.PROJECT_MODEL,
        listOf(
            "WorkspaceModelTopics.CHANGED",
            "ExternalProjectInfo.lastImportTimestamp+lastSuccessfulImportTimestamp",
        ),
        "projectCounter+exactRootImportTimestamps",
        "projectCounterOrExactRootImportTimestampChanged",
    ),
    Kvp015SignalDocument(
        Kvp015SignalCategory.PSI,
        listOf("PsiModificationTracker.modificationCount"),
        "modificationCount",
        "modificationCountChanged",
    ),
    Kvp015SignalDocument(
        Kvp015SignalCategory.VFS,
        listOf("VirtualFileManager.VFS_CHANGES"),
        "rootFilteredChangeCounter",
        "rootFilteredChangeCounterChanged",
    ),
    Kvp015SignalDocument(
        Kvp015SignalCategory.ROOT_MODEL,
        listOf("ProjectRootModificationTracker.modificationCount"),
        "modificationCount",
        "modificationCountChanged",
    ),
    Kvp015SignalDocument(
        Kvp015SignalCategory.DUMB_MODE,
        listOf("DumbService.modificationTracker", "DumbService.isDumb"),
        "modificationCount+isDumb",
        "modificationCountOrDumbStateChanged",
    ),
)

private fun canonicalCases(): List<Kvp015CaseDocument> = listOf(
    epochCase(Kvp015CaseId.STABLE, emptyList(), relation = Kvp015SampleRelation.UNCHANGED),
    epochCase(
        Kvp015CaseId.WORKSPACE_MODEL_MOVEMENT,
        listOf(Kvp015SignalCategory.PROJECT_MODEL),
        projectTransitions = listOf(Kvp015ProjectModelTransition.WORKSPACE_MODEL_CHANGED),
    ),
    epochCase(
        Kvp015CaseId.GRADLE_IMPORT_STARTED,
        listOf(Kvp015SignalCategory.PROJECT_MODEL),
        projectTransitions = listOf(Kvp015ProjectModelTransition.GRADLE_IMPORT_STARTED),
    ),
    epochCase(
        Kvp015CaseId.GRADLE_IMPORT_COMPLETED,
        listOf(Kvp015SignalCategory.PROJECT_MODEL),
        projectTransitions = listOf(Kvp015ProjectModelTransition.GRADLE_IMPORT_COMPLETED),
    ),
    epochCase(
        Kvp015CaseId.GRADLE_ROOT_MOVEMENT,
        listOf(Kvp015SignalCategory.PROJECT_MODEL),
        projectTransitions = listOf(Kvp015ProjectModelTransition.GRADLE_ROOT_CHANGED),
    ),
    epochCase(Kvp015CaseId.PSI_MOVEMENT, listOf(Kvp015SignalCategory.PSI)),
    epochCase(Kvp015CaseId.VFS_MOVEMENT, listOf(Kvp015SignalCategory.VFS)),
    epochCase(Kvp015CaseId.ROOT_MODEL_MOVEMENT, listOf(Kvp015SignalCategory.ROOT_MODEL)),
    epochCase(
        Kvp015CaseId.SMART_DUMB_SMART,
        listOf(Kvp015SignalCategory.DUMB_MODE),
        dumbTransitions = listOf(
            Kvp015DumbModeTransition.SMART_TO_DUMB,
            Kvp015DumbModeTransition.DUMB_TO_SMART,
        ),
    ),
    epochCase(
        Kvp015CaseId.COMBINED_MOVEMENT,
        Kvp015SignalCategory.entries,
        projectTransitions = listOf(Kvp015ProjectModelTransition.WORKSPACE_MODEL_CHANGED),
        dumbTransitions = listOf(
            Kvp015DumbModeTransition.SMART_TO_DUMB,
            Kvp015DumbModeTransition.DUMB_TO_SMART,
        ),
    ),
    epochCase(
        Kvp015CaseId.VFS_EVENT_STORM,
        listOf(Kvp015SignalCategory.VFS),
        vfsEventCount = STORM_EVENT_COUNT,
    ),
)

private fun epochCase(
    caseId: Kvp015CaseId,
    movedSignals: List<Kvp015SignalCategory>,
    projectTransitions: List<Kvp015ProjectModelTransition> = emptyList(),
    relation: Kvp015SampleRelation = Kvp015SampleRelation.CHANGED,
    dumbModeSamples: List<Kvp015DumbModeState> = listOf(
        Kvp015DumbModeState.SMART,
        Kvp015DumbModeState.SMART,
    ),
    dumbTransitions: List<Kvp015DumbModeTransition> = emptyList(),
    vfsEventCount: Int = 0,
) = Kvp015CaseDocument(
    caseId,
    SAMPLES_PER_CASE,
    movedSignals,
    projectTransitions,
    dumbModeSamples,
    dumbTransitions,
    vfsEventCount,
    relation,
    relation,
)

private fun Kvp015EpochLedgerDocument.forbiddenEffectCounts(): List<Int> = listOf(
    vfsRefreshCount,
    gradleImportCount,
    repositoryWalkCount,
    sourceHashCount,
    semanticJobCount,
    edtWorkCount,
    blockingWaitCount,
)

private fun rejected(
    failure: Kvp015EpochLedgerReportFailure,
): Kvp015EpochLedgerReportAdmission = Kvp015EpochLedgerReportAdmission.Rejected(failure)

private const val SCHEMA_VERSION = 1
private const val IDE_BUILD = "262.9437.185"
private const val SAMPLES_PER_CASE = 2
private const val STORM_EVENT_COUNT = 1_000
private val CONSTANT_ZERO_VFS_AUTHORITIES = listOf(
    "VirtualFileManager.modificationCount",
    "VirtualFileManager.structureModificationCount",
)

private val EPOCH_LEDGER_JSON = Json {
    encodeDefaults = true
    explicitNulls = true
    ignoreUnknownKeys = false
    isLenient = false
    prettyPrint = true
    prettyPrintIndent = "    "
}
