[profile.default]
slow-timeout = "15s"
retries = 0

[profile.ci]
fail-fast = false
slow-timeout = "15s"
retries = 0

[profile.ci.junit]
path = "junit.xml"
store-failure-output = true
store-success-output = false
