package support.architecture

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json

@Serializable
internal enum class HostedReadInventoryScope {
    COMPILED_MAIN_CLASSES,
}

internal enum class HostedReadPathReportFailure {
    MALFORMED_DOCUMENT,
    IDENTITY_MISMATCH,
    INVENTORY_REJECTED,
    INJECTED_AUTHORITY_COUNT_MISMATCH,
    EFFECT_COUNTS_MISMATCH,
    ALLOWED_REFERENCE_COUNT_INVALID,
    RUNTIME_PROJECT_PATHS_MISMATCH,
    PROJECT_CLASSPATH_MISMATCH,
    EXTERNAL_CLASSPATH_MISMATCH,
    PREDECESSOR_RECEIPTS_MISMATCH,
    DOCUMENT_MISMATCH,
    NON_CANONICAL_DOCUMENT,
}

internal sealed interface HostedReadPathReportAdmission {
    data class Admitted(
        val proof: VfsPassiveHostedModelCapture,
        val report: AdmittedKvp018NoWalkReport,
    ) : HostedReadPathReportAdmission
    data class Rejected(val failure: HostedReadPathReportFailure) : HostedReadPathReportAdmission
}

internal class AdmittedKvp018NoWalkReport private constructor(
    private val canonicalDocument: String,
    val classCount: Int,
    val classInventoryDigest: String,
    val injectedForbiddenAuthorityCount: Int,
    val prohibitedEffectCount: Int,
    val allowedIntellijReferenceCount: Int,
    val runtimeProjectCount: Int,
    val runtimeProjectArtifactSetSha256: String,
    val runtimeProjectClassCount: Int,
    val runtimeExternalArtifactCount: Int,
    val runtimeExternalArtifactSetSha256: String,
    val runtimeExternalClassCount: Int,
    val runtimeExternalGenericFilesystemPrimitiveReferenceCount: Int,
) {
    internal fun canonicalDocumentAtReportBoundary(): String = canonicalDocument

    internal companion object {
        /**
         * Proof transition: `(String, VfsPassiveHostedModelCapture,
         * Kvp018PredecessorReceipts) -> Kvp018NoWalkReportRefinement`.
         *
         * Establishes exact KVP-018 identity/scope, equality with an independently derived complete
         * class/runtime proof, all finite injected authorities, the exact all-zero prohibited-
         * effect set, nonnegative allowed IntelliJ evidence, exact semantic predecessor digests,
         * and canonical generated bytes.
         * Expected schema and invariant gaps remain closed [HostedReadPathReportFailure]. Raw JSON
         * may be extracted only at this receipt/report boundary.
         */
        fun admit(
            raw: String,
            proof: VfsPassiveHostedModelCapture,
            predecessors: Kvp018PredecessorReceipts,
        ): Kvp018NoWalkReportRefinement {
            val document = try {
                hostedReadPathJson.decodeFromString(Kvp018NoWalkReportDocument.serializer(), raw)
            } catch (_: SerializationException) {
                return Kvp018NoWalkReportRefinement.Rejected(
                    HostedReadPathReportFailure.MALFORMED_DOCUMENT,
                )
            }
            val identityMatches = document.schemaVersion == 3 &&
                document.taskId == "KVP-018" &&
                document.module == ModuleId.WORKSPACE_INTELLIJ_READ.projectPath &&
                document.role == ModuleRole.IDE_READ_ONLY &&
                document.inventoryScope == HostedReadInventoryScope.COMPILED_MAIN_CLASSES &&
                document.publicInterface == "VfsPassiveHostedModelCapture"
            if (!identityMatches) return Kvp018NoWalkReportRefinement.Rejected(
                HostedReadPathReportFailure.IDENTITY_MISMATCH,
            )
            val inventory = when (val refined = HostedReadClassInventory.refine(
                document.inventory.classes.map {
                    RawHostedReadClassArtifact(it.relativeName, it.sha256)
                },
                proof.inventory.classes().mapTo(linkedSetOf()) { it.relativeName },
            )) {
                is HostedReadInventoryRefinement.Refined -> refined.inventory
                is HostedReadInventoryRefinement.Rejected ->
                    return Kvp018NoWalkReportRefinement.Rejected(
                        HostedReadPathReportFailure.INVENTORY_REJECTED,
                    )
            }
            if (
                document.inventory.classCount != inventory.classes().size ||
                document.inventory.classSetSha256 != inventory.digest.value ||
                document.inventory.classes != document.inventory.classes.sortedBy { it.relativeName }
            ) return Kvp018NoWalkReportRefinement.Rejected(
                HostedReadPathReportFailure.INVENTORY_REJECTED,
            )
            if (
                document.injectedForbiddenAuthorityCount !=
                Kvp018RequiredForbiddenFamily.entries.size
            ) {
                return Kvp018NoWalkReportRefinement.Rejected(
                    HostedReadPathReportFailure.INJECTED_AUTHORITY_COUNT_MISMATCH,
                )
            }
            val expectedEffects = ForbiddenEffect.entries
                .filterNot { it == ForbiddenEffect.INTELLIJ_PLATFORM }
                .map { HostedReadEffectCountDocument(it, 0) }
            if (
                document.prohibitedEffectCounts != expectedEffects ||
                document.observedForbiddenReferenceCount != 0 ||
                document.allowedEffect != ForbiddenEffect.INTELLIJ_PLATFORM
            ) return Kvp018NoWalkReportRefinement.Rejected(
                HostedReadPathReportFailure.EFFECT_COUNTS_MISMATCH,
            )
            if (document.allowedIntellijReferenceCount < 0) {
                return Kvp018NoWalkReportRefinement.Rejected(
                    HostedReadPathReportFailure.ALLOWED_REFERENCE_COUNT_INVALID,
                )
            }
            val expectedPredecessors = predecessors.artifacts().map {
                Kvp018PredecessorReceiptDocument(it.id, it.sha256)
            }
            if (document.predecessorReceipts != expectedPredecessors) {
                return Kvp018NoWalkReportRefinement.Rejected(
                    HostedReadPathReportFailure.PREDECESSOR_RECEIPTS_MISMATCH,
                )
            }
            if (document.runtimeProjectPaths !=
                proof.projectClasspath.projectPaths().map(ModuleId::projectPath)
            ) {
                return Kvp018NoWalkReportRefinement.Rejected(
                    HostedReadPathReportFailure.RUNTIME_PROJECT_PATHS_MISMATCH,
                )
            }
            val expectedProjectArtifacts = proof.projectClasspath.artifacts().map { artifact ->
                HostedReadProjectArtifactDocument(
                    artifact.project.projectPath,
                    artifact.artifactName,
                    artifact.sha256,
                    artifact.classCount,
                )
            }
            val expectedProjectEffects = proof.projectClasspath.prohibitedEffectCounts().map {
                HostedReadEffectCountDocument(it.effect, it.count)
            }
            if (
                document.runtimeProjectArtifacts != expectedProjectArtifacts ||
                document.runtimeProjectArtifactSetSha256 !=
                proof.projectClasspath.artifactSetSha256 ||
                document.projectClasspathProhibitedEffectCounts != expectedProjectEffects
            ) return Kvp018NoWalkReportRefinement.Rejected(
                HostedReadPathReportFailure.PROJECT_CLASSPATH_MISMATCH,
            )
            val expectedExternalArtifacts = proof.externalClasspath.artifacts().map { artifact ->
                HostedReadExternalArtifactDocument(
                    artifact.componentId,
                    artifact.artifactName,
                    artifact.sha256,
                    artifact.classCount,
                )
            }
            val expectedExternalEffects = proof.externalClasspath.prohibitedEffectCounts().map {
                HostedReadEffectCountDocument(it.effect, it.count)
            }
            if (
                document.runtimeExternalClasspathAuthority != proof.externalClasspath.authority ||
                document.runtimeExternalArtifacts != expectedExternalArtifacts ||
                document.runtimeExternalArtifactSetSha256 !=
                proof.externalClasspath.artifactSetSha256 ||
                document.runtimeExternalGenericFilesystemPrimitiveReferenceCount !=
                proof.externalClasspath.genericFilesystemPrimitiveReferenceCount ||
                document.externalClasspathProhibitedEffectCounts != expectedExternalEffects
            ) {
                return Kvp018NoWalkReportRefinement.Rejected(
                    HostedReadPathReportFailure.EXTERNAL_CLASSPATH_MISMATCH,
                )
            }
            if (document != proof.document(predecessors)) {
                return Kvp018NoWalkReportRefinement.Rejected(
                    HostedReadPathReportFailure.DOCUMENT_MISMATCH,
                )
            }
            if (raw != hostedReadPathJson.encodeToString(
                Kvp018NoWalkReportDocument.serializer(),
                document,
            ) + "\n") return Kvp018NoWalkReportRefinement.Rejected(
                HostedReadPathReportFailure.NON_CANONICAL_DOCUMENT,
            )
            return Kvp018NoWalkReportRefinement.Admitted(
                AdmittedKvp018NoWalkReport(
                    raw,
                    inventory.classes().size,
                    inventory.digest.value,
                    document.injectedForbiddenAuthorityCount,
                    expectedEffects.size,
                    document.allowedIntellijReferenceCount,
                    document.runtimeProjectPaths.size,
                    document.runtimeProjectArtifactSetSha256,
                    document.runtimeProjectArtifacts.sumOf(
                        HostedReadProjectArtifactDocument::classCount,
                    ),
                    document.runtimeExternalArtifacts.size,
                    document.runtimeExternalArtifactSetSha256,
                    document.runtimeExternalArtifacts.sumOf(
                        HostedReadExternalArtifactDocument::classCount,
                    ),
                    document.runtimeExternalGenericFilesystemPrimitiveReferenceCount,
                ),
            )
        }
    }
}

internal sealed interface Kvp018NoWalkReportRefinement {
    data class Admitted(val report: AdmittedKvp018NoWalkReport) : Kvp018NoWalkReportRefinement
    data class Rejected(val failure: HostedReadPathReportFailure) : Kvp018NoWalkReportRefinement
}

@Serializable
private data class HostedReadClassArtifactDocument(
    val relativeName: String,
    val sha256: String,
)

@Serializable
private data class HostedReadInventoryDocument(
    val classCount: Int,
    val classSetSha256: String,
    val classes: List<HostedReadClassArtifactDocument>,
)

@Serializable
private data class HostedReadEffectCountDocument(
    val effect: ForbiddenEffect,
    val count: Int,
)

@Serializable
private data class Kvp018PredecessorReceiptDocument(
    val receiptId: Kvp018PredecessorReceiptId,
    val sha256: String,
)

@Serializable
private data class HostedReadExternalArtifactDocument(
    val componentId: String,
    val artifactName: String,
    val sha256: String,
    val classCount: Int,
)

@Serializable
private data class HostedReadProjectArtifactDocument(
    val projectPath: String,
    val artifactName: String,
    val sha256: String,
    val classCount: Int,
)

@Serializable
private data class Kvp018NoWalkReportDocument(
    val schemaVersion: Int,
    val taskId: String,
    val module: String,
    val role: ModuleRole,
    val inventoryScope: HostedReadInventoryScope,
    val publicInterface: String,
    val injectedForbiddenAuthorityCount: Int,
    val inventory: HostedReadInventoryDocument,
    val prohibitedEffectCounts: List<HostedReadEffectCountDocument>,
    val observedForbiddenReferenceCount: Int,
    val allowedEffect: ForbiddenEffect,
    val allowedIntellijReferenceCount: Int,
    val runtimeProjectPaths: List<String>,
    val runtimeProjectArtifacts: List<HostedReadProjectArtifactDocument>,
    val runtimeProjectArtifactSetSha256: String,
    val projectClasspathProhibitedEffectCounts: List<HostedReadEffectCountDocument>,
    val runtimeExternalClasspathAuthority: HostedReadExternalClasspathAuthority,
    val runtimeExternalArtifacts: List<HostedReadExternalArtifactDocument>,
    val runtimeExternalArtifactSetSha256: String,
    val runtimeExternalGenericFilesystemPrimitiveReferenceCount: Int,
    val externalClasspathProhibitedEffectCounts: List<HostedReadEffectCountDocument>,
    val predecessorReceipts: List<Kvp018PredecessorReceiptDocument>,
)

private val hostedReadPathJson = Json {
    encodeDefaults = true
    explicitNulls = false
    ignoreUnknownKeys = false
    prettyPrint = true
}

/**
 * Proof transition: `(VfsPassiveHostedModelCapture,
 * Kvp018PredecessorReceipts) -> String`.
 *
 * Preserves the complete compiled-class inventory, deterministic inventory digest, every finite
 * prohibited effect count, exact external runtime artifact byte identities, allowed IntelliJ
 * reference count, and both predecessor receipt digests in a dedicated generated JSON document.
 * Raw JSON leaves only at the Gradle report boundary.
 */
internal fun encodeHostedReadPathReport(
    proof: VfsPassiveHostedModelCapture,
    predecessors: Kvp018PredecessorReceipts,
): String = hostedReadPathJson.encodeToString(
    Kvp018NoWalkReportDocument.serializer(),
    proof.document(predecessors),
) + "\n"

/**
 * Proof transition: `(String, VfsPassiveHostedModelCapture,
 * Kvp018PredecessorReceipts) -> HostedReadPathReportAdmission`.
 *
 * Establishes exact schema, canonical bytes, inventory, effect counts, and predecessor digests
 * against an independently admitted hosted proof. Expected malformed, mismatched, or noncanonical
 * evidence remains closed [HostedReadPathReportFailure]. Raw JSON is accepted only here.
 */
internal fun admitHostedReadPathReport(
    raw: String,
    proof: VfsPassiveHostedModelCapture,
    predecessors: Kvp018PredecessorReceipts,
): HostedReadPathReportAdmission {
    return when (val result = AdmittedKvp018NoWalkReport.admit(
        raw,
        proof,
        predecessors,
    )) {
        is Kvp018NoWalkReportRefinement.Admitted ->
            HostedReadPathReportAdmission.Admitted(proof, result.report)
        is Kvp018NoWalkReportRefinement.Rejected ->
            HostedReadPathReportAdmission.Rejected(result.failure)
    }
}

private fun VfsPassiveHostedModelCapture.document(
    predecessors: Kvp018PredecessorReceipts,
) = Kvp018NoWalkReportDocument(
    schemaVersion = 3,
    taskId = "KVP-018",
    module = ModuleId.WORKSPACE_INTELLIJ_READ.projectPath,
    role = ModuleRole.IDE_READ_ONLY,
    inventoryScope = HostedReadInventoryScope.COMPILED_MAIN_CLASSES,
    publicInterface = "VfsPassiveHostedModelCapture",
    injectedForbiddenAuthorityCount = Kvp018RequiredForbiddenFamily.entries.size,
    inventory = HostedReadInventoryDocument(
        classCount = inventory.classes().size,
        classSetSha256 = inventory.digest.value,
        classes = inventory.classes().map { artifact ->
            HostedReadClassArtifactDocument(artifact.relativeName, artifact.sha256)
        },
    ),
    prohibitedEffectCounts = prohibitedEffectCounts().map { count ->
        HostedReadEffectCountDocument(count.effect, count.count)
    },
    observedForbiddenReferenceCount = prohibitedEffectCounts().sumOf(HostedReadEffectCount::count),
    allowedEffect = ForbiddenEffect.INTELLIJ_PLATFORM,
    allowedIntellijReferenceCount = allowedIntellijReferenceCount,
    runtimeProjectPaths = projectClasspath.projectPaths().map(ModuleId::projectPath),
    runtimeProjectArtifacts = projectClasspath.artifacts().map { artifact ->
        HostedReadProjectArtifactDocument(
            artifact.project.projectPath,
            artifact.artifactName,
            artifact.sha256,
            artifact.classCount,
        )
    },
    runtimeProjectArtifactSetSha256 = projectClasspath.artifactSetSha256,
    projectClasspathProhibitedEffectCounts = projectClasspath.prohibitedEffectCounts().map {
        HostedReadEffectCountDocument(it.effect, it.count)
    },
    runtimeExternalClasspathAuthority = externalClasspath.authority,
    runtimeExternalArtifacts = externalClasspath.artifacts().map { artifact ->
        HostedReadExternalArtifactDocument(
            artifact.componentId,
            artifact.artifactName,
            artifact.sha256,
            artifact.classCount,
        )
    },
    runtimeExternalArtifactSetSha256 = externalClasspath.artifactSetSha256,
    runtimeExternalGenericFilesystemPrimitiveReferenceCount =
        externalClasspath.genericFilesystemPrimitiveReferenceCount,
    externalClasspathProhibitedEffectCounts = externalClasspath.prohibitedEffectCounts().map {
        HostedReadEffectCountDocument(it.effect, it.count)
    },
    predecessorReceipts = predecessors.artifacts().map { predecessor ->
        Kvp018PredecessorReceiptDocument(predecessor.id, predecessor.sha256)
    },
)
