package support.architecture

internal object KastCleanSlateModules {
    val all: List<ModulePolicy> = listOf(
        target(ModuleId.KERNEL, ModuleRole.KERNEL),
        target(
            ModuleId.CHANGE_PROTOCOL,
            ModuleRole.SERVICE,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.QUERY_PROTOCOL,
            ModuleRole.SERVICE,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.QUERY_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.SOURCE_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
        ),
        target(ModuleId.DISTRIBUTION_CONTRACT, ModuleRole.CONTRACT, ModuleId.KERNEL),
        target(
            ModuleId.DISTRIBUTION_MANAGED,
            ModuleRole.FILESYSTEM_WRITE_ADAPTER,
            ModuleId.DISTRIBUTION_CONTRACT,
            effects = setOf(ForbiddenEffect.FILESYSTEM_WRITE),
        ),
        target(
            ModuleId.PROTOCOL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.SYMBOL_CONTRACT,
        ),
        target(ModuleId.WORKSPACE_CONTRACT, ModuleRole.CONTRACT, ModuleId.KERNEL),
        target(
            ModuleId.SYMBOL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.RELATION_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        ModulePolicy(ModuleId.TOPOLOGY_CONTRACT, ModuleLifecycle.RETIRED, ModuleRole.CONTRACT, emptySet(), emptySet()),
        target(
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
        ),
        target(
            ModuleId.EVIDENCE_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.PROTOCOL_REGISTRY,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.PROTOCOL_WIRE,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
        ),
        ModulePolicy(ModuleId.WORKSPACE_SERVICE, ModuleLifecycle.RETIRED, ModuleRole.SERVICE, emptySet(), emptySet()),
        ModulePolicy(ModuleId.WORKSPACE_INTELLIJ, ModuleLifecycle.RETIRED, ModuleRole.WORKSPACE_ADAPTER, emptySet(), emptySet()),
        target(
            ModuleId.SYMBOL_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.SYMBOL_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.SOURCE_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
        ),
        target(
            ModuleId.SOURCE_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.SOURCE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.SOURCE_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.SOURCE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.RELATION_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.RELATION_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.TRAVERSAL_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
        ),
        ModulePolicy(ModuleId.TOPOLOGY_BUILD, ModuleLifecycle.RETIRED, ModuleRole.SERVICE, emptySet(), emptySet()),
        ModulePolicy(ModuleId.TOPOLOGY_SERVICE, ModuleLifecycle.RETIRED, ModuleRole.SERVICE, emptySet(), emptySet()),
        ModulePolicy(ModuleId.TOPOLOGY_INTELLIJ, ModuleLifecycle.RETIRED, ModuleRole.INTELLIJ_READ_ADAPTER, emptySet(), emptySet()),
        target(
            ModuleId.DIAGNOSTIC_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.DIAGNOSTIC_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.CHANGE_PLAN,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_APPLY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_RECOVERY,
            ModuleId.EVIDENCE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_VERIFY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_RECOVERY,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_RECOVERY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.EVIDENCE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_INTELLIJ,
            ModuleRole.INTELLIJ_WRITE_ADAPTER,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_RECOVERY,
            ModuleId.CHANGE_VERIFY,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.INTELLIJ_WRITE,
            ),
        ),
        target(
            ModuleId.EVIDENCE_SQLITE,
            ModuleRole.SQLITE_ADAPTER,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_VERIFY,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            effects = setOf(
                ForbiddenEffect.JDBC,
                ForbiddenEffect.FILESYSTEM_WRITE,
            ),
        ),
        ModulePolicy(ModuleId.RUNTIME_SERVER, ModuleLifecycle.RETIRED, ModuleRole.TRANSPORT, emptySet(), emptySet()),
        ModulePolicy(ModuleId.RUNTIME_TELEMETRY, ModuleLifecycle.RETIRED, ModuleRole.FILESYSTEM_WRITE_ADAPTER, emptySet(), emptySet()),
        target(
            ModuleId.APP_SERVER,
            ModuleRole.APP_SERVER,
            ModuleId.KERNEL,
            ModuleId.DISTRIBUTION_CONTRACT,
            ModuleId.DISTRIBUTION_MANAGED,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
            effects = setOf(ForbiddenEffect.PROCESS_CONTROL),
            scopedEffects = mapOf(ForbiddenEffect.FILESYSTEM_WRITE to setOf(
                    JvmClassName("io/github/amichne/kast/appserver/InstalledAppServerManager"),
                    JvmClassName("io/github/amichne/kast/appserver/BrokerInstallationState"),
                    JvmClassName("io/github/amichne/kast/appserver/InstalledCoordinatorConfiguration"),
                    JvmClassName("io/github/amichne/kast/appserver/WorkspaceEnrollmentStore"),
                    JvmClassName("io/github/amichne/kast/appserver/runtime/InvocationFence"),
                    JvmClassName(
                        "io/github/amichne/kast/appserver/MacOsPersistentBrokerServiceHost",
                    ),
                    JvmClassName(
                        "io/github/amichne/kast/appserver/InstalledBrokerServerConfiguration\$Companion",
                    ),
                    JvmClassName("io/github/amichne/kast/appserver/InstalledBrokerServerKt"),
                    JvmClassName("io/github/amichne/kast/appserver/OwnedBrokerServiceReadiness"),
                    JvmClassName(
                        "io/github/amichne/kast/appserver/protocol/codex/CodexProtocolQualifier\$retireTemporaryTree\$1\$1",
                    ),
                    JvmClassName(
                        "io/github/amichne/kast/appserver/protocol/FileThreadCatalogStore",
                    ),
                    JvmClassName("io/github/amichne/kast/appserver/runtime/OwnedUnixSocket"),
                    JvmClassName(
                        "io/github/amichne/kast/appserver/runtime/UnixSocketPathOwnership",
                    ),
            )),
        ),
        target(
            ModuleId.CLI,
            ModuleRole.CLI,
            ModuleId.APP_SERVER,
            ModuleId.DISTRIBUTION_CONTRACT,
            ModuleId.DISTRIBUTION_MANAGED,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
            ModuleId.PROTOCOL_WIRE,
            effects = setOf(ForbiddenEffect.PROCESS_CONTROL),
            scopedEffects = mapOf(
                ForbiddenEffect.FILESYSTEM_WRITE to setOf(
                    JvmClassName("io/github/amichne/kast/cli/ide/FilesystemBrokerTrustRegistrar"),
                    JvmClassName(
                        "io/github/amichne/kast/cli/installation/InstallationWorkflow",
                    ),
                    JvmClassName(
                        "io/github/amichne/kast/cli/installation/InstallationWorkflow\$copyControl\$1",
                    ),
                    JvmClassName(
                        "io/github/amichne/kast/cli/installation/InstallationWorkflowKt",
                    ),
                    JvmClassName(
                        "io/github/amichne/kast/cli/installation/InstallationWorkflowKt\$deleteTree\$1",
                    ),
                ),
            ),
        ),
        ideRead(
            ModuleId.WORKSPACE_INTELLIJ_READ,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            lifecycle = ModuleLifecycle.ACTIVE,
            additionalEffects = setOf(
                ForbiddenEffect.PROJECT_FILE_INDEX_AUTHORITY,
                ForbiddenEffect.PROJECT_READ_EPOCH_AUTHORITY,
            ),
        ),
        ModulePolicy(ModuleId.RUNTIME_COMPOSITION, ModuleLifecycle.RETIRED, ModuleRole.COMPOSITION, emptySet(), emptySet()),
        target(
            ModuleId.RUNTIME_HOSTED,
            ModuleRole.IDE_HOST,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_PLAN,
            ModuleId.CHANGE_PROTOCOL,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_VERIFY,
            ModuleId.CHANGE_RECOVERY,
            ModuleId.CHANGE_INTELLIJ,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.EVIDENCE_SQLITE,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_WIRE,
            ModuleId.QUERY_CONTRACT,
            ModuleId.QUERY_PROTOCOL,
            ModuleId.QUERY_SERVICE,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.SYMBOL_SERVICE,
            ModuleId.SYMBOL_INTELLIJ,
            ModuleId.SOURCE_CONTRACT,
            ModuleId.SOURCE_SERVICE,
            ModuleId.SOURCE_INTELLIJ,
            ModuleId.RELATION_CONTRACT,
            ModuleId.RELATION_SERVICE,
            ModuleId.RELATION_INTELLIJ,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.DIAGNOSTIC_SERVICE,
            ModuleId.DIAGNOSTIC_INTELLIJ,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.TRAVERSAL_SERVICE,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM, ForbiddenEffect.UDS_BIND, ForbiddenEffect.ENDPOINT_DESCRIPTOR_WRITE),
            scopedEffects = mapOf(ForbiddenEffect.FILESYSTEM_WRITE to setOf(
                JvmClassName("io/github/amichne/kast/runtime/hosted/OwnedHostedEndpoint"),
                JvmClassName("io/github/amichne/kast/runtime/hosted/DeadHostedEndpoint"),
                JvmClassName("io/github/amichne/kast/runtime/hosted/OwnedHostedEndpoint\$Companion"),
            ),
                // Reads are confined to endpoint ownership and approval artifacts; the digest names the canonical root.
                ForbiddenEffect.PHYSICAL_SOURCE_READ to setOf(
                    JvmClassName("io/github/amichne/kast/runtime/hosted/OwnedHostedEndpoint\$Companion"),
                    JvmClassName("io/github/amichne/kast/runtime/hosted/HostedChangeApprovalsKt"),
                    JvmClassName("io/github/amichne/kast/runtime/hosted/DeadHostedEndpointOwner\$Companion"),
                ),
                ForbiddenEffect.SOURCE_CONTENT_HASH to setOf(JvmClassName("io/github/amichne/kast/runtime/hosted/OwnedHostedEndpoint\$Companion")),
            ),
        ),
        ModulePolicy(ModuleId.INDEXER, ModuleLifecycle.RETIRED, ModuleRole.INDEXER_HOST, emptySet(), emptySet()),
    )

    private fun target(
        id: ModuleId,
        role: ModuleRole,
        vararg dependencies: ModuleId,
        effects: Set<ForbiddenEffect> = emptySet(),
        scopedEffects: Map<ForbiddenEffect, Set<JvmClassName>> = emptyMap(),
    ): ModulePolicy = ModulePolicy(
        id = id,
        lifecycle = ModuleLifecycle.ACTIVE,
        role = role,
        allowedProjectDependencies = dependencies.toSet(),
        allowedEffects = effects,
        allowedScopedEffectCallers = scopedEffects,
    )

    private fun ideRead(
        id: ModuleId,
        vararg dependencies: ModuleId,
        lifecycle: ModuleLifecycle = ModuleLifecycle.PLANNED,
        additionalEffects: Set<ForbiddenEffect> = emptySet(),
    ): ModulePolicy = ModulePolicy(
        id = id,
        lifecycle = lifecycle,
        role = ModuleRole.IDE_READ_ONLY,
        allowedProjectDependencies = dependencies.toSet(),
        allowedEffects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM) + additionalEffects,
    )

}
