package support.architecture

internal object KastCleanSlateModules {
    val all: List<ModulePolicy> = listOf(
        target(ModuleId.KERNEL, ModuleRole.KERNEL),
        target(ModuleId.PROTOCOL_CONTRACT, ModuleRole.CONTRACT, ModuleId.KERNEL),
        target(ModuleId.WORKSPACE_CONTRACT, ModuleRole.CONTRACT, ModuleId.KERNEL),
        target(
            ModuleId.SYMBOL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.RELATION_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
        ),
        target(
            ModuleId.EVIDENCE_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.PROTOCOL_REGISTRY,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.PROTOCOL_WIRE,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
        ),
        target(
            ModuleId.WORKSPACE_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.EVIDENCE_CONTRACT,
            effects = setOf(ForbiddenEffect.WORKSPACE_TRANSITION),
        ),
        target(
            ModuleId.WORKSPACE_INTELLIJ,
            ModuleRole.WORKSPACE_ADAPTER,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.GRADLE_PLATFORM,
                ForbiddenEffect.GRADLE_IMPORT,
                ForbiddenEffect.GRAPH_BUILD,
            ),
        ),
        target(
            ModuleId.SYMBOL_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.SYMBOL_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.RELATION_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.RELATION_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.TRAVERSAL_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
        ),
        target(
            ModuleId.DIAGNOSTIC_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.DIAGNOSTIC_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.CHANGE_PLAN,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
        ),
        target(ModuleId.CHANGE_APPLY, ModuleRole.SERVICE, ModuleId.CHANGE_CONTRACT),
        target(
            ModuleId.CHANGE_VERIFY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.EVIDENCE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_RECOVERY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.EVIDENCE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_INTELLIJ,
            ModuleRole.INTELLIJ_WRITE_ADAPTER,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.INTELLIJ_WRITE,
                ForbiddenEffect.FILESYSTEM_WRITE,
                ForbiddenEffect.SOURCE_FILESYSTEM_WRITE,
            ),
        ),
        target(
            ModuleId.EVIDENCE_SQLITE,
            ModuleRole.SQLITE_ADAPTER,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
            effects = setOf(ForbiddenEffect.JDBC),
        ),
        target(
            ModuleId.RUNTIME_SERVER,
            ModuleRole.TRANSPORT,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
            ModuleId.PROTOCOL_WIRE,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.CLI,
            ModuleRole.CLI,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
            ModuleId.PROTOCOL_WIRE,
            effects = setOf(ForbiddenEffect.PROCESS_CONTROL),
        ),
        runtimeComposition(),
        target(
            ModuleId.INDEXER,
            ModuleRole.INDEXER_HOST,
            ModuleId.RUNTIME_COMPOSITION,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
    )

    private fun runtimeComposition(): ModulePolicy {
        val excluded = setOf(ModuleId.CLI, ModuleId.INDEXER, ModuleId.RUNTIME_COMPOSITION)
        return target(
            ModuleId.RUNTIME_COMPOSITION,
            ModuleRole.COMPOSITION,
            *(targetIds() - excluded).toTypedArray(),
        )
    }

    private fun target(
        id: ModuleId,
        role: ModuleRole,
        vararg dependencies: ModuleId,
        effects: Set<ForbiddenEffect> = emptySet(),
    ): ModulePolicy = ModulePolicy(
        id = id,
        lifecycle = ModuleLifecycle.ACTIVE,
        role = role,
        allowedProjectDependencies = dependencies.toSet(),
        allowedEffects = effects,
    )

    private fun targetIds(): Set<ModuleId> = setOf(
        ModuleId.KERNEL,
        ModuleId.PROTOCOL_CONTRACT,
        ModuleId.PROTOCOL_REGISTRY,
        ModuleId.PROTOCOL_WIRE,
        ModuleId.WORKSPACE_CONTRACT,
        ModuleId.WORKSPACE_SERVICE,
        ModuleId.WORKSPACE_INTELLIJ,
        ModuleId.SYMBOL_CONTRACT,
        ModuleId.SYMBOL_SERVICE,
        ModuleId.SYMBOL_INTELLIJ,
        ModuleId.RELATION_CONTRACT,
        ModuleId.RELATION_SERVICE,
        ModuleId.RELATION_INTELLIJ,
        ModuleId.TRAVERSAL_CONTRACT,
        ModuleId.TRAVERSAL_SERVICE,
        ModuleId.DIAGNOSTIC_CONTRACT,
        ModuleId.DIAGNOSTIC_SERVICE,
        ModuleId.DIAGNOSTIC_INTELLIJ,
        ModuleId.CHANGE_CONTRACT,
        ModuleId.CHANGE_PLAN,
        ModuleId.CHANGE_APPLY,
        ModuleId.CHANGE_VERIFY,
        ModuleId.CHANGE_RECOVERY,
        ModuleId.CHANGE_INTELLIJ,
        ModuleId.EVIDENCE_CONTRACT,
        ModuleId.EVIDENCE_SQLITE,
        ModuleId.RUNTIME_SERVER,
        ModuleId.RUNTIME_COMPOSITION,
        ModuleId.CLI,
        ModuleId.INDEXER,
    )
}
