package support.architecture

internal object KastCleanSlateModules {
    val all: List<ModulePolicy> = listOf(
        target(ModuleId.KERNEL, ModuleRole.KERNEL),
        target(ModuleId.DISTRIBUTION_CONTRACT, ModuleRole.CONTRACT, ModuleId.KERNEL),
        target(
            ModuleId.DISTRIBUTION_MANAGED,
            ModuleRole.FILESYSTEM_WRITE_ADAPTER,
            ModuleId.DISTRIBUTION_CONTRACT,
            effects = setOf(ForbiddenEffect.FILESYSTEM_WRITE),
        ),
        target(
            ModuleId.PROTOCOL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.SYMBOL_CONTRACT,
        ),
        target(ModuleId.WORKSPACE_CONTRACT, ModuleRole.CONTRACT, ModuleId.KERNEL),
        target(
            ModuleId.SYMBOL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.RELATION_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.TOPOLOGY_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
        ),
        target(
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
        ),
        target(
            ModuleId.EVIDENCE_CONTRACT,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.PROTOCOL_REGISTRY,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.PROTOCOL_WIRE,
            ModuleRole.CONTRACT,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
        ),
        target(
            ModuleId.WORKSPACE_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.EVIDENCE_CONTRACT,
            effects = setOf(ForbiddenEffect.WORKSPACE_TRANSITION),
        ),
        target(
            ModuleId.WORKSPACE_INTELLIJ,
            ModuleRole.WORKSPACE_ADAPTER,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.GRADLE_PLATFORM,
                ForbiddenEffect.GRADLE_IMPORT,
                ForbiddenEffect.GRAPH_BUILD,
            ),
        ),
        target(
            ModuleId.SYMBOL_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.SYMBOL_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.RELATION_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.RELATION_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.TRAVERSAL_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
        ),
        target(
            ModuleId.TOPOLOGY_BUILD,
            ModuleRole.SERVICE,
            ModuleId.TOPOLOGY_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            effects = setOf(ForbiddenEffect.TOPOLOGY_BUILD_AUTHORITY),
        ),
        target(
            ModuleId.TOPOLOGY_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.TOPOLOGY_CONTRACT,
        ),
        target(
            ModuleId.TOPOLOGY_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.TOPOLOGY_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            ModuleId.SYMBOL_CONTRACT,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.TOPOLOGY_SOURCE_ROOT_VFS_SYNCHRONIZATION,
            ),
        ),
        target(
            ModuleId.DIAGNOSTIC_SERVICE,
            ModuleRole.SERVICE,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.DIAGNOSTIC_INTELLIJ,
            ModuleRole.INTELLIJ_READ_ADAPTER,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM),
        ),
        target(
            ModuleId.CHANGE_PLAN,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_APPLY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_RECOVERY,
            ModuleId.EVIDENCE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_VERIFY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_RECOVERY,
            ModuleRole.SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.EVIDENCE_CONTRACT,
        ),
        target(
            ModuleId.CHANGE_INTELLIJ,
            ModuleRole.INTELLIJ_WRITE_ADAPTER,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_RECOVERY,
            ModuleId.CHANGE_VERIFY,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.INTELLIJ_WRITE,
            ),
        ),
        target(
            ModuleId.EVIDENCE_SQLITE,
            ModuleRole.SQLITE_ADAPTER,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_VERIFY,
            ModuleId.TOPOLOGY_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            effects = setOf(
                ForbiddenEffect.JDBC,
                ForbiddenEffect.FILESYSTEM_WRITE,
                ForbiddenEffect.TOPOLOGY_PUBLICATION,
            ),
        ),
        target(
            ModuleId.RUNTIME_SERVER,
            ModuleRole.TRANSPORT,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
            ModuleId.PROTOCOL_WIRE,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.RELATION_CONTRACT,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.TOPOLOGY_CONTRACT,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.CHANGE_CONTRACT,
        ),
        target(
            ModuleId.RUNTIME_TELEMETRY,
            ModuleRole.FILESYSTEM_WRITE_ADAPTER,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_WIRE,
            effects = setOf(ForbiddenEffect.FILESYSTEM_WRITE),
        ),
        target(
            ModuleId.CLI,
            ModuleRole.CLI,
            ModuleId.DISTRIBUTION_CONTRACT,
            ModuleId.DISTRIBUTION_MANAGED,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
            ModuleId.PROTOCOL_WIRE,
            effects = setOf(ForbiddenEffect.PROCESS_CONTROL),
        ),
        ideRead(
            ModuleId.WORKSPACE_INTELLIJ_READ,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            lifecycle = ModuleLifecycle.ACTIVE,
            additionalEffects = setOf(ForbiddenEffect.PROJECT_FILE_INDEX_AUTHORITY),
        ),
        ideRead(
            ModuleId.RUNTIME_IDE_READ,
            ModuleId.KERNEL,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_REGISTRY,
            ModuleId.PROTOCOL_WIRE,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            ModuleId.SYMBOL_CONTRACT,
            ModuleId.SYMBOL_INTELLIJ,
            lifecycle = ModuleLifecycle.ACTIVE,
        ),
        target(
            ModuleId.RUNTIME_IDE_HOST,
            ModuleRole.COMPOSITION,
            ModuleId.RUNTIME_IDE_READ,
            ModuleId.RUNTIME_SERVER,
            ModuleId.RUNTIME_TELEMETRY,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_SERVICE,
            ModuleId.TOPOLOGY_CONTRACT,
            ModuleId.TOPOLOGY_BUILD,
            ModuleId.TOPOLOGY_SERVICE,
            ModuleId.RELATION_CONTRACT,
            ModuleId.RELATION_SERVICE,
            ModuleId.TRAVERSAL_CONTRACT,
            ModuleId.TRAVERSAL_SERVICE,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.DIAGNOSTIC_SERVICE,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_PLAN,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_VERIFY,
            ModuleId.CHANGE_RECOVERY,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.EVIDENCE_SQLITE,
        ),
        target(
            ModuleId.IDE_PLUGIN,
            ModuleRole.IDE_HOST,
            ModuleId.PROTOCOL_CONTRACT,
            ModuleId.PROTOCOL_WIRE,
            ModuleId.RUNTIME_IDE_READ,
            ModuleId.RUNTIME_IDE_HOST,
            ModuleId.EVIDENCE_CONTRACT,
            ModuleId.WORKSPACE_CONTRACT,
            ModuleId.WORKSPACE_INTELLIJ_READ,
            ModuleId.TOPOLOGY_CONTRACT,
            ModuleId.TOPOLOGY_INTELLIJ,
            ModuleId.RELATION_CONTRACT,
            ModuleId.RELATION_INTELLIJ,
            ModuleId.DIAGNOSTIC_CONTRACT,
            ModuleId.DIAGNOSTIC_INTELLIJ,
            ModuleId.CHANGE_CONTRACT,
            ModuleId.CHANGE_APPLY,
            ModuleId.CHANGE_VERIFY,
            ModuleId.CHANGE_INTELLIJ,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.PROJECT_READ_EPOCH_AUTHORITY,
                ForbiddenEffect.UDS_BIND,
                ForbiddenEffect.ENDPOINT_DESCRIPTOR_WRITE,
            ),
        ),
        runtimeComposition(),
        target(
            ModuleId.INDEXER,
            ModuleRole.INDEXER_HOST,
            ModuleId.RUNTIME_COMPOSITION,
            effects = setOf(
                ForbiddenEffect.INTELLIJ_PLATFORM,
                ForbiddenEffect.FILESYSTEM_WRITE,
            ),
        ),
    )

    private fun runtimeComposition(): ModulePolicy {
        val excluded = setOf(
            ModuleId.CLI,
            ModuleId.INDEXER,
            ModuleId.RUNTIME_COMPOSITION,
            ModuleId.RUNTIME_IDE_HOST,
        )
        return target(
            ModuleId.RUNTIME_COMPOSITION,
            ModuleRole.COMPOSITION,
            *(targetIds() - excluded).toTypedArray(),
        )
    }

    private fun target(
        id: ModuleId,
        role: ModuleRole,
        vararg dependencies: ModuleId,
        effects: Set<ForbiddenEffect> = emptySet(),
    ): ModulePolicy = ModulePolicy(
        id = id,
        lifecycle = ModuleLifecycle.ACTIVE,
        role = role,
        allowedProjectDependencies = dependencies.toSet(),
        allowedEffects = effects,
    )

    private fun ideRead(
        id: ModuleId,
        vararg dependencies: ModuleId,
        lifecycle: ModuleLifecycle = ModuleLifecycle.PLANNED,
        additionalEffects: Set<ForbiddenEffect> = emptySet(),
    ): ModulePolicy = ModulePolicy(
        id = id,
        lifecycle = lifecycle,
        role = ModuleRole.IDE_READ_ONLY,
        allowedProjectDependencies = dependencies.toSet(),
        allowedEffects = setOf(ForbiddenEffect.INTELLIJ_PLATFORM) + additionalEffects,
    )

    private fun targetIds(): Set<ModuleId> = setOf(
        ModuleId.KERNEL,
        ModuleId.DISTRIBUTION_CONTRACT,
        ModuleId.DISTRIBUTION_MANAGED,
        ModuleId.PROTOCOL_CONTRACT,
        ModuleId.PROTOCOL_REGISTRY,
        ModuleId.PROTOCOL_WIRE,
        ModuleId.WORKSPACE_CONTRACT,
        ModuleId.WORKSPACE_SERVICE,
        ModuleId.WORKSPACE_INTELLIJ,
        ModuleId.WORKSPACE_INTELLIJ_READ,
        ModuleId.SYMBOL_CONTRACT,
        ModuleId.SYMBOL_SERVICE,
        ModuleId.SYMBOL_INTELLIJ,
        ModuleId.RELATION_CONTRACT,
        ModuleId.RELATION_SERVICE,
        ModuleId.RELATION_INTELLIJ,
        ModuleId.TRAVERSAL_CONTRACT,
        ModuleId.TRAVERSAL_SERVICE,
        ModuleId.TOPOLOGY_CONTRACT,
        ModuleId.TOPOLOGY_BUILD,
        ModuleId.TOPOLOGY_SERVICE,
        ModuleId.TOPOLOGY_INTELLIJ,
        ModuleId.DIAGNOSTIC_CONTRACT,
        ModuleId.DIAGNOSTIC_SERVICE,
        ModuleId.DIAGNOSTIC_INTELLIJ,
        ModuleId.CHANGE_CONTRACT,
        ModuleId.CHANGE_PLAN,
        ModuleId.CHANGE_APPLY,
        ModuleId.CHANGE_VERIFY,
        ModuleId.CHANGE_RECOVERY,
        ModuleId.CHANGE_INTELLIJ,
        ModuleId.EVIDENCE_CONTRACT,
        ModuleId.EVIDENCE_SQLITE,
        ModuleId.RUNTIME_SERVER,
        ModuleId.RUNTIME_TELEMETRY,
        ModuleId.RUNTIME_COMPOSITION,
        ModuleId.RUNTIME_IDE_READ,
        ModuleId.RUNTIME_IDE_HOST,
        ModuleId.IDE_PLUGIN,
        ModuleId.CLI,
        ModuleId.INDEXER,
    )
}
