use crate::SCHEMA_VERSION;
use crate::cli::{BackendName, DaemonStartArgs};
use crate::error::{CliError, Result};
use crate::manifest;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fmt;
use std::fs;
use std::num::NonZeroU64;
use std::path::{Path, PathBuf};

include!("config/model.rs");
include!("config/partial.rs");
include!("config/load.rs");
include!("config/path_resolution.rs");
include!("config/launch.rs");
include!("config/filesystem.rs");
include!("config/git_workspace.rs");
include!("config/tests.rs");
