include!("bundle_entrypoint/types/setup_and_projection_contracts.rs");
include!("bundle_entrypoint/types/path_projection_authority.rs");
include!("bundle_entrypoint/types/path_transaction_preparation.rs");
include!("bundle_entrypoint/types/path_transaction_completion.rs");
include!("bundle_entrypoint/types/agent_command_projection.rs");
include!("bundle_entrypoint/types/receipt_authority.rs");
include!("bundle_entrypoint/types/projection_exchange.rs");
include!("bundle_entrypoint/types/projection_journal.rs");
include!("bundle_entrypoint/types/setup_result.rs");
