plugins {
    id("kast.kotlin-serialization")
    id("kast.role.composition")
}

dependencies {
    implementation(project(":kernel"))
    implementation(project(":protocol:contract"))
    implementation(project(":protocol:registry"))
    implementation(project(":protocol:wire"))
    implementation(project(":workspace:contract"))
    implementation(project(":workspace:service"))
    implementation(project(":workspace:intellij"))
    implementation(project(":symbol:contract"))
    implementation(project(":symbol:service"))
    implementation(project(":symbol:intellij"))
    implementation(project(":relation:contract"))
    implementation(project(":relation:service"))
    implementation(project(":relation:intellij"))
    implementation(project(":traversal:contract"))
    implementation(project(":traversal:service"))
    implementation(project(":diagnostic:contract"))
    implementation(project(":diagnostic:service"))
    implementation(project(":diagnostic:intellij"))
    implementation(project(":change:contract"))
    implementation(project(":change:plan"))
    implementation(project(":change:apply"))
    implementation(project(":change:verify"))
    implementation(project(":change:recovery"))
    implementation(project(":change:intellij"))
    implementation(project(":evidence:contract"))
    implementation(project(":evidence:sqlite"))
    implementation(project(":runtime:server"))
}
