package support.delivery

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@Serializable
private data class Kvp016DetachedModelDocument(
    val schemaVersion: Int,
    val authority: Kvp016ReportAuthority,
    val canonicalRoot: String,
    val captureMode: Kvp016CaptureMode,
    val modelState: Kvp016ModelState,
    val retainedFacets: List<Kvp016RetainedFacet>,
    val rejectedLiveCapabilities: List<Kvp016RejectedLiveCapability>,
    val maxCachedGradleModelCount: Int,
    val maxModuleCount: Int,
    val maxSourceRootCountPerModule: Int,
    val maxClasspathEntryCountPerModule: Int,
    val maxIdentityUtf8Bytes: Int,
    val maxPathUtf8Bytes: Int,
    val maxClasspathUrlUtf8Bytes: Int,
    val gradleImportCount: Int,
    val gradleLinkCount: Int,
    val gradlePrepareCount: Int,
    val gradleRepairCount: Int,
    val vfsRefreshCount: Int,
    val repositoryWalkCount: Int,
    val sourceHashCount: Int,
    val blockingWaitCount: Int,
    val liveObjectEscapeCount: Int,
    val edtSemanticWorkCount: Int,
    val productionEpochFieldCount: Int,
)

@Serializable
private enum class Kvp016ReportAuthority { OPEN_PROJECT }

@Serializable
private enum class Kvp016CaptureMode { CANCELLABLE_WRITE_PRIORITY_READ }

@Serializable
private enum class Kvp016ModelState { COMPLETE_DETACHED }

@Serializable
private enum class Kvp016RetainedFacet {
    ROOT,
    MODULES,
    SOURCE_ROOTS,
    GRADLE_OWNERSHIP,
    SDK,
    CLASSPATH_IDENTITY,
    HOST_COMPATIBILITY,
}

@Serializable
private enum class Kvp016RejectedLiveCapability {
    PROJECT,
    VIRTUAL_FILE,
    MODULE,
    SEARCH_SCOPE,
    PSI,
    GRADLE_DATA_NODE,
    CALLBACK,
    MUTABLE_COLLECTION,
}

internal enum class Kvp016DetachedModelReportFailure {
    MALFORMED_DOCUMENT,
    NON_CANONICAL_DOCUMENT,
    SCHEMA_VERSION_MISMATCH,
    AUTHORITY_MISMATCH,
    CANONICAL_ROOT_MISMATCH,
    CAPTURE_MODE_MISMATCH,
    MODEL_STATE_MISMATCH,
    RETAINED_FACET_SET_MISMATCH,
    LIVE_CAPABILITY_SET_MISMATCH,
    BOUND_MISMATCH,
    FORBIDDEN_EFFECT_OBSERVED,
}

internal class AdmittedKvp016DetachedModelReport private constructor(
    val canonicalDocument: String,
    val authority: String,
    val canonicalRoot: String,
    val retainedFacetCount: Int,
    val rejectedLiveCapabilityCount: Int,
    val maxCachedGradleModelCount: Int,
    val maxModuleCount: Int,
    val maxSourceRootCountPerModule: Int,
    val maxClasspathEntryCountPerModule: Int,
) {
    companion object {
        /**
         * Proof transition: `String -> Kvp016DetachedModelReportAdmission`.
         *
         * Establishes canonical generated bytes for the bounded existing-Project model contract,
         * including every retained detached facet, rejected live capability, fixed bound, and zero
         * forbidden stronger effect. [Kvp016DetachedModelReportFailure] closes every expected
         * report failure; raw JSON may leave only at this Gradle receipt boundary.
         */
        fun admit(raw: String): Kvp016DetachedModelReportAdmission {
            val document = try {
                DETACHED_MODEL_JSON.decodeFromString(Kvp016DetachedModelDocument.serializer(), raw)
            } catch (_: SerializationException) {
                return rejected(Kvp016DetachedModelReportFailure.MALFORMED_DOCUMENT)
            } catch (_: IllegalArgumentException) {
                return rejected(Kvp016DetachedModelReportFailure.MALFORMED_DOCUMENT)
            }
            val failure = when {
                document.schemaVersion != SCHEMA_VERSION ->
                    Kvp016DetachedModelReportFailure.SCHEMA_VERSION_MISMATCH
                document.authority != Kvp016ReportAuthority.OPEN_PROJECT ->
                    Kvp016DetachedModelReportFailure.AUTHORITY_MISMATCH
                document.canonicalRoot != CANONICAL_ROOT ->
                    Kvp016DetachedModelReportFailure.CANONICAL_ROOT_MISMATCH
                document.captureMode != Kvp016CaptureMode.CANCELLABLE_WRITE_PRIORITY_READ ->
                    Kvp016DetachedModelReportFailure.CAPTURE_MODE_MISMATCH
                document.modelState != Kvp016ModelState.COMPLETE_DETACHED ->
                    Kvp016DetachedModelReportFailure.MODEL_STATE_MISMATCH
                document.retainedFacets != Kvp016RetainedFacet.entries ->
                    Kvp016DetachedModelReportFailure.RETAINED_FACET_SET_MISMATCH
                document.rejectedLiveCapabilities != Kvp016RejectedLiveCapability.entries ->
                    Kvp016DetachedModelReportFailure.LIVE_CAPABILITY_SET_MISMATCH
                document.maxModuleCount != MAX_MODULE_COUNT ||
                    document.maxCachedGradleModelCount != MAX_CACHED_GRADLE_MODEL_COUNT ||
                    document.maxSourceRootCountPerModule != MAX_SOURCE_ROOT_COUNT_PER_MODULE ||
                    document.maxClasspathEntryCountPerModule != MAX_CLASSPATH_ENTRY_COUNT_PER_MODULE ||
                    document.maxIdentityUtf8Bytes != MAX_IDENTITY_UTF8_BYTES ||
                    document.maxPathUtf8Bytes != MAX_PATH_UTF8_BYTES ||
                    document.maxClasspathUrlUtf8Bytes != MAX_CLASSPATH_URL_UTF8_BYTES ->
                    Kvp016DetachedModelReportFailure.BOUND_MISMATCH
                document.forbiddenEffectCounts().any { count -> count != 0 } ->
                    Kvp016DetachedModelReportFailure.FORBIDDEN_EFFECT_OBSERVED
                else -> null
            }
            if (failure != null) return rejected(failure)
            val canonical = DETACHED_MODEL_JSON.encodeToString(
                Kvp016DetachedModelDocument.serializer(),
                document,
            ) + "\n"
            if (raw != canonical) {
                return rejected(Kvp016DetachedModelReportFailure.NON_CANONICAL_DOCUMENT)
            }
            return Kvp016DetachedModelReportAdmission.Admitted(
                AdmittedKvp016DetachedModelReport(
                    canonical,
                    document.authority.name,
                    document.canonicalRoot,
                    document.retainedFacets.size,
                    document.rejectedLiveCapabilities.size,
                    document.maxCachedGradleModelCount,
                    document.maxModuleCount,
                    document.maxSourceRootCountPerModule,
                    document.maxClasspathEntryCountPerModule,
                ),
            )
        }
    }
}

internal sealed interface Kvp016DetachedModelReportAdmission {
    data class Admitted(
        val report: AdmittedKvp016DetachedModelReport,
    ) : Kvp016DetachedModelReportAdmission

    data class Rejected(
        val failure: Kvp016DetachedModelReportFailure,
    ) : Kvp016DetachedModelReportAdmission
}

@CacheableTask
abstract class GenerateKvp016DetachedModelReportTask : DefaultTask() {
    @get:OutputFile
    abstract val reportFile: RegularFileProperty

    /** Writes the canonical generated KVP-016 detached-model report. */
    @TaskAction
    fun generate() {
        writeTextAtomically(reportFile.get().asFile.toPath(), canonicalKvp016DetachedModelReport())
    }
}

private fun canonicalKvp016DetachedModelReport(): String = DETACHED_MODEL_JSON.encodeToString(
    Kvp016DetachedModelDocument.serializer(),
    Kvp016DetachedModelDocument(
        schemaVersion = SCHEMA_VERSION,
        authority = Kvp016ReportAuthority.OPEN_PROJECT,
        canonicalRoot = CANONICAL_ROOT,
        captureMode = Kvp016CaptureMode.CANCELLABLE_WRITE_PRIORITY_READ,
        modelState = Kvp016ModelState.COMPLETE_DETACHED,
        retainedFacets = Kvp016RetainedFacet.entries,
        rejectedLiveCapabilities = Kvp016RejectedLiveCapability.entries,
        maxCachedGradleModelCount = MAX_CACHED_GRADLE_MODEL_COUNT,
        maxModuleCount = MAX_MODULE_COUNT,
        maxSourceRootCountPerModule = MAX_SOURCE_ROOT_COUNT_PER_MODULE,
        maxClasspathEntryCountPerModule = MAX_CLASSPATH_ENTRY_COUNT_PER_MODULE,
        maxIdentityUtf8Bytes = MAX_IDENTITY_UTF8_BYTES,
        maxPathUtf8Bytes = MAX_PATH_UTF8_BYTES,
        maxClasspathUrlUtf8Bytes = MAX_CLASSPATH_URL_UTF8_BYTES,
        gradleImportCount = 0,
        gradleLinkCount = 0,
        gradlePrepareCount = 0,
        gradleRepairCount = 0,
        vfsRefreshCount = 0,
        repositoryWalkCount = 0,
        sourceHashCount = 0,
        blockingWaitCount = 0,
        liveObjectEscapeCount = 0,
        edtSemanticWorkCount = 0,
        productionEpochFieldCount = 0,
    ),
) + "\n"

private fun Kvp016DetachedModelDocument.forbiddenEffectCounts(): List<Int> = listOf(
    gradleImportCount,
    gradleLinkCount,
    gradlePrepareCount,
    gradleRepairCount,
    vfsRefreshCount,
    repositoryWalkCount,
    sourceHashCount,
    blockingWaitCount,
    liveObjectEscapeCount,
    edtSemanticWorkCount,
    productionEpochFieldCount,
)

private fun rejected(
    failure: Kvp016DetachedModelReportFailure,
): Kvp016DetachedModelReportAdmission = Kvp016DetachedModelReportAdmission.Rejected(failure)

private const val SCHEMA_VERSION = 1
private const val CANONICAL_ROOT = "/workspace/kast"
private const val MAX_CACHED_GRADLE_MODEL_COUNT = 8
private const val MAX_MODULE_COUNT = 128
private const val MAX_SOURCE_ROOT_COUNT_PER_MODULE = 256
private const val MAX_CLASSPATH_ENTRY_COUNT_PER_MODULE = 512
private const val MAX_IDENTITY_UTF8_BYTES = 512
private const val MAX_PATH_UTF8_BYTES = 4_096
private const val MAX_CLASSPATH_URL_UTF8_BYTES = 8_192

private val DETACHED_MODEL_JSON = Json {
    encodeDefaults = true
    explicitNulls = true
    ignoreUnknownKeys = false
    isLenient = false
    prettyPrint = true
    prettyPrintIndent = "    "
}
