package support.delivery

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@Serializable
private data class Kvp017ReadEpochDocument(
    val schemaVersion: Int,
    val authority: Kvp017ReportAuthority,
    val ideBuild: String,
    val comparisonScope: Kvp017ComparisonScope,
    val signalComponents: List<Kvp017SignalComponent>,
    val comparisonRelations: List<Kvp017ComparisonRelation>,
    val observationFailures: List<Kvp017ObservationFailure>,
    val maxVfsEventsPerBatch: Int,
    val maxVfsPathCharacters: Int,
    val maxVfsPathUtf8Bytes: Int,
    val maxCachedGradleModels: Int,
    val cases: List<Kvp017CaseDocument>,
    val primitiveCounterEscapeCount: Int,
    val callerEpochReconstructionCount: Int,
    val repeatedValidationCount: Int,
    val dumbModeEpochValueCount: Int,
    val vfsRefreshCount: Int,
    val gradleImportCount: Int,
    val gradleRepairCount: Int,
    val repositoryWalkCount: Int,
    val vfsTraversalCount: Int,
    val sourceHashCount: Int,
    val semanticJobCount: Int,
    val edtSemanticWorkCount: Int,
    val blockingWaitCount: Int,
    val liveObjectEscapeCount: Int,
)

@Serializable
private data class Kvp017CaseDocument(
    val caseId: Kvp017CaseId,
    val sampleCount: Int,
    val movedSignals: List<Kvp017SignalComponent>,
    val vfsEventCount: Int,
    val expectedRelation: Kvp017ComparisonRelation,
    val observedRelation: Kvp017ComparisonRelation,
)

@Serializable
private enum class Kvp017ReportAuthority { READ_EPOCH, OPEN_PROJECT }

@Serializable
private enum class Kvp017ComparisonScope { ADMITTED_PROJECT_RUNTIME, GLOBAL_RUNTIME }

@Serializable
private enum class Kvp017SignalComponent {
    PROJECT_MODEL,
    PSI,
    ROOT_FILTERED_VFS,
    ROOT_MODEL,
    DUMB_MODE_TRACKER,
}

@Serializable
private enum class Kvp017ComparisonRelation { SAME, MOVED, INCOMPARABLE }

@Serializable
private enum class Kvp017ObservationFailure {
    WRONG_THREAD,
    PROJECT_DISPOSED,
    PROJECT_NOT_OPEN,
    PROJECT_NOT_INITIALIZED,
    PROJECT_ROOT_UNAVAILABLE,
    PROJECT_ROOT_MALFORMED,
    DUMB_MODE,
    GRADLE_MODEL_UNAVAILABLE,
    GRADLE_MODEL_INCOMPLETE,
    GRADLE_MODEL_AMBIGUOUS,
    GRADLE_ROOT_UNAVAILABLE,
    GRADLE_ROOT_MALFORMED,
    IMPORT_TIMESTAMPS_INCOHERENT,
    VFS_BATCH_LIMIT_EXCEEDED,
    VFS_PATH_MALFORMED,
    SIGNAL_EXHAUSTED,
    READ_PREEMPTED,
    OBSERVATION_FAILED_THREAD,
    OBSERVATION_FAILED_DISPOSAL,
    OBSERVATION_FAILED_OPEN,
    OBSERVATION_FAILED_INITIALIZATION,
    OBSERVATION_FAILED_PROJECT_ROOT,
    OBSERVATION_FAILED_PROJECT_MODEL,
    OBSERVATION_FAILED_PSI,
    OBSERVATION_FAILED_VFS,
    OBSERVATION_FAILED_ROOT_MODEL,
    OBSERVATION_FAILED_DUMB_MODE,
}

@Serializable
private enum class Kvp017CaseId {
    STABLE,
    WORKSPACE_MODEL_MOVEMENT,
    GRADLE_IMPORT_STARTED,
    GRADLE_IMPORT_COMPLETED,
    GRADLE_ROOT_MOVEMENT,
    PSI_MOVEMENT,
    VFS_MOVEMENT,
    ROOT_MODEL_MOVEMENT,
    DUMB_MODE_TRACKER_MOVEMENT,
    COMBINED_MOVEMENT,
    VFS_EVENT_STORM,
    OTHER_PROJECT_SCOPE,
    OTHER_RUNTIME_SCOPE,
}

internal enum class Kvp017ReadEpochReportFailure {
    MALFORMED_DOCUMENT,
    NON_CANONICAL_DOCUMENT,
    SCHEMA_VERSION_MISMATCH,
    AUTHORITY_MISMATCH,
    IDE_BUILD_MISMATCH,
    COMPARISON_SCOPE_MISMATCH,
    SIGNAL_SET_MISMATCH,
    COMPARISON_RELATION_SET_MISMATCH,
    OBSERVATION_FAILURE_SET_MISMATCH,
    OBSERVATION_BOUND_MISMATCH,
    CASE_SET_MISMATCH,
    FORBIDDEN_CONTRACT_OBSERVED,
    FORBIDDEN_EFFECT_OBSERVED,
}

internal class AdmittedKvp017ReadEpochReport private constructor(
    val canonicalDocument: String,
    val authority: String,
    val ideBuild: String,
    val comparisonScope: String,
    val signalCount: Int,
    val comparisonRelationCount: Int,
    val observationFailureCount: Int,
    val caseCount: Int,
    val maxVfsEventsPerBatch: Int,
    val maxVfsPathCharacters: Int,
    val maxVfsPathUtf8Bytes: Int,
    val maxCachedGradleModels: Int,
    val vfsTraversalCount: Int,
) {
    companion object {
        /**
         * Proof transition: `String -> Kvp017ReadEpochReportAdmission`.
         *
         * Establishes canonical generated bytes for the scope-bound project-read epoch contract,
         * including all characterized signal components, finite comparison and observation
         * outcomes, stable and moved cases, and zero forbidden representation or effect counts.
         * [Kvp017ReadEpochReportFailure] closes every expected report failure; raw JSON may leave
         * only at this outer Gradle receipt boundary.
         */
        fun admit(raw: String): Kvp017ReadEpochReportAdmission {
            val document = try {
                READ_EPOCH_JSON.decodeFromString(Kvp017ReadEpochDocument.serializer(), raw)
            } catch (_: SerializationException) {
                return rejected(Kvp017ReadEpochReportFailure.MALFORMED_DOCUMENT)
            } catch (_: IllegalArgumentException) {
                return rejected(Kvp017ReadEpochReportFailure.MALFORMED_DOCUMENT)
            }
            val failure = when {
                document.schemaVersion != SCHEMA_VERSION ->
                    Kvp017ReadEpochReportFailure.SCHEMA_VERSION_MISMATCH
                document.authority != Kvp017ReportAuthority.READ_EPOCH ->
                    Kvp017ReadEpochReportFailure.AUTHORITY_MISMATCH
                document.ideBuild != IDE_BUILD ->
                    Kvp017ReadEpochReportFailure.IDE_BUILD_MISMATCH
                document.comparisonScope != Kvp017ComparisonScope.ADMITTED_PROJECT_RUNTIME ->
                    Kvp017ReadEpochReportFailure.COMPARISON_SCOPE_MISMATCH
                document.signalComponents != Kvp017SignalComponent.entries ->
                    Kvp017ReadEpochReportFailure.SIGNAL_SET_MISMATCH
                document.comparisonRelations != Kvp017ComparisonRelation.entries ->
                    Kvp017ReadEpochReportFailure.COMPARISON_RELATION_SET_MISMATCH
                document.observationFailures != Kvp017ObservationFailure.entries ->
                    Kvp017ReadEpochReportFailure.OBSERVATION_FAILURE_SET_MISMATCH
                document.maxVfsEventsPerBatch != MAX_VFS_EVENTS_PER_BATCH ||
                    document.maxVfsPathCharacters != MAX_VFS_PATH_CHARACTERS ||
                    document.maxVfsPathUtf8Bytes != MAX_VFS_PATH_UTF8_BYTES ||
                    document.maxCachedGradleModels != MAX_CACHED_GRADLE_MODELS ->
                    Kvp017ReadEpochReportFailure.OBSERVATION_BOUND_MISMATCH
                document.cases != canonicalCases() ->
                    Kvp017ReadEpochReportFailure.CASE_SET_MISMATCH
                document.forbiddenContractCounts().any { count -> count != 0 } ->
                    Kvp017ReadEpochReportFailure.FORBIDDEN_CONTRACT_OBSERVED
                document.forbiddenEffectCounts().any { count -> count != 0 } ->
                    Kvp017ReadEpochReportFailure.FORBIDDEN_EFFECT_OBSERVED
                else -> null
            }
            if (failure != null) return rejected(failure)
            val canonical = READ_EPOCH_JSON.encodeToString(
                Kvp017ReadEpochDocument.serializer(),
                document,
            ) + "\n"
            if (raw != canonical) {
                return rejected(Kvp017ReadEpochReportFailure.NON_CANONICAL_DOCUMENT)
            }
            return Kvp017ReadEpochReportAdmission.Admitted(
                AdmittedKvp017ReadEpochReport(
                    canonical,
                    document.authority.name,
                    document.ideBuild,
                    document.comparisonScope.name,
                    document.signalComponents.size,
                    document.comparisonRelations.size,
                    document.observationFailures.size,
                    document.cases.size,
                    document.maxVfsEventsPerBatch,
                    document.maxVfsPathCharacters,
                    document.maxVfsPathUtf8Bytes,
                    document.maxCachedGradleModels,
                    document.vfsTraversalCount,
                ),
            )
        }
    }
}

internal sealed interface Kvp017ReadEpochReportAdmission {
    data class Admitted(
        val report: AdmittedKvp017ReadEpochReport,
    ) : Kvp017ReadEpochReportAdmission

    data class Rejected(
        val failure: Kvp017ReadEpochReportFailure,
    ) : Kvp017ReadEpochReportAdmission
}

@CacheableTask
abstract class GenerateKvp017ReadEpochReportTask : DefaultTask() {
    @get:OutputFile
    abstract val reportFile: RegularFileProperty

    /** Writes the canonical generated KVP-017 project-read epoch report. */
    @TaskAction
    fun generate() {
        writeTextAtomically(reportFile.get().asFile.toPath(), canonicalKvp017ReadEpochReport())
    }
}

internal fun canonicalKvp017ReadEpochReport(): String = READ_EPOCH_JSON.encodeToString(
    Kvp017ReadEpochDocument.serializer(),
    Kvp017ReadEpochDocument(
        schemaVersion = SCHEMA_VERSION,
        authority = Kvp017ReportAuthority.READ_EPOCH,
        ideBuild = IDE_BUILD,
        comparisonScope = Kvp017ComparisonScope.ADMITTED_PROJECT_RUNTIME,
        signalComponents = Kvp017SignalComponent.entries,
        comparisonRelations = Kvp017ComparisonRelation.entries,
        observationFailures = Kvp017ObservationFailure.entries,
        maxVfsEventsPerBatch = MAX_VFS_EVENTS_PER_BATCH,
        maxVfsPathCharacters = MAX_VFS_PATH_CHARACTERS,
        maxVfsPathUtf8Bytes = MAX_VFS_PATH_UTF8_BYTES,
        maxCachedGradleModels = MAX_CACHED_GRADLE_MODELS,
        cases = canonicalCases(),
        primitiveCounterEscapeCount = 0,
        callerEpochReconstructionCount = 0,
        repeatedValidationCount = 0,
        dumbModeEpochValueCount = 0,
        vfsRefreshCount = 0,
        gradleImportCount = 0,
        gradleRepairCount = 0,
        repositoryWalkCount = 0,
        vfsTraversalCount = 0,
        sourceHashCount = 0,
        semanticJobCount = 0,
        edtSemanticWorkCount = 0,
        blockingWaitCount = 0,
        liveObjectEscapeCount = 0,
    ),
) + "\n"

private fun canonicalCases(): List<Kvp017CaseDocument> = listOf(
    epochCase(Kvp017CaseId.STABLE, relation = Kvp017ComparisonRelation.SAME),
    epochCase(
        Kvp017CaseId.WORKSPACE_MODEL_MOVEMENT,
        listOf(Kvp017SignalComponent.PROJECT_MODEL),
    ),
    epochCase(
        Kvp017CaseId.GRADLE_IMPORT_STARTED,
        listOf(Kvp017SignalComponent.PROJECT_MODEL),
    ),
    epochCase(
        Kvp017CaseId.GRADLE_IMPORT_COMPLETED,
        listOf(Kvp017SignalComponent.PROJECT_MODEL),
    ),
    epochCase(
        Kvp017CaseId.GRADLE_ROOT_MOVEMENT,
        listOf(Kvp017SignalComponent.PROJECT_MODEL),
    ),
    epochCase(Kvp017CaseId.PSI_MOVEMENT, listOf(Kvp017SignalComponent.PSI)),
    epochCase(
        Kvp017CaseId.VFS_MOVEMENT,
        listOf(Kvp017SignalComponent.ROOT_FILTERED_VFS),
    ),
    epochCase(Kvp017CaseId.ROOT_MODEL_MOVEMENT, listOf(Kvp017SignalComponent.ROOT_MODEL)),
    epochCase(
        Kvp017CaseId.DUMB_MODE_TRACKER_MOVEMENT,
        listOf(Kvp017SignalComponent.DUMB_MODE_TRACKER),
    ),
    Kvp017CaseDocument(
        Kvp017CaseId.COMBINED_MOVEMENT,
        2,
        Kvp017SignalComponent.entries,
        0,
        Kvp017ComparisonRelation.MOVED,
        Kvp017ComparisonRelation.MOVED,
    ),
    epochCase(
        Kvp017CaseId.VFS_EVENT_STORM,
        listOf(Kvp017SignalComponent.ROOT_FILTERED_VFS),
        vfsEventCount = 1_000,
    ),
    epochCase(
        Kvp017CaseId.OTHER_PROJECT_SCOPE,
        relation = Kvp017ComparisonRelation.INCOMPARABLE,
    ),
    epochCase(
        Kvp017CaseId.OTHER_RUNTIME_SCOPE,
        relation = Kvp017ComparisonRelation.INCOMPARABLE,
    ),
)

private fun epochCase(
    caseId: Kvp017CaseId,
    movedSignals: List<Kvp017SignalComponent> = emptyList(),
    vfsEventCount: Int = 0,
    relation: Kvp017ComparisonRelation = Kvp017ComparisonRelation.MOVED,
) = Kvp017CaseDocument(
    caseId,
    2,
    movedSignals,
    vfsEventCount,
    relation,
    relation,
)

private fun Kvp017ReadEpochDocument.forbiddenContractCounts() = listOf(
    primitiveCounterEscapeCount,
    callerEpochReconstructionCount,
    repeatedValidationCount,
    dumbModeEpochValueCount,
)

private fun Kvp017ReadEpochDocument.forbiddenEffectCounts() = listOf(
    vfsRefreshCount,
    gradleImportCount,
    gradleRepairCount,
    repositoryWalkCount,
    vfsTraversalCount,
    sourceHashCount,
    semanticJobCount,
    edtSemanticWorkCount,
    blockingWaitCount,
    liveObjectEscapeCount,
)

private fun rejected(
    failure: Kvp017ReadEpochReportFailure,
): Kvp017ReadEpochReportAdmission = Kvp017ReadEpochReportAdmission.Rejected(failure)

private const val SCHEMA_VERSION = 1
private const val IDE_BUILD = "262.9437.185"
private const val MAX_VFS_EVENTS_PER_BATCH = 4_096
private const val MAX_VFS_PATH_CHARACTERS = 4_096
private const val MAX_VFS_PATH_UTF8_BYTES = 8_192
private const val MAX_CACHED_GRADLE_MODELS = 16

private val READ_EPOCH_JSON = Json {
    encodeDefaults = true
    explicitNulls = true
    ignoreUnknownKeys = false
    isLenient = false
    prettyPrint = true
    prettyPrintIndent = "    "
}
