package io.github.amichne.kast.workspace.intellij.read

/** Exhaustive emitted-class inventory for every project-read epoch production type and changed bridge. */
internal fun productionEpochResources(): List<String> = contractEpochResources() +
    adapterEpochResources() + admissionBridgeResources()

private fun contractEpochResources(): List<String> = listOf(
    "ProjectReadEpoch.class",
    "ProjectReadEpoch\$ComparisonDomain.class",
    "ProjectReadEpoch\$Source.class",
    "ProjectReadEpoch\$Source\$Companion.class",
    "ProjectReadEpochObservation.class",
    "ProjectReadEpochObservation\$Observed.class",
    "ProjectReadEpochObservation\$Rejected.class",
    "ProjectReadEpochObservationFailure.class",
    "ProjectReadEpochObservationFailure\$DumbMode.class",
    "ProjectReadEpochObservationFailure\$GradleModelAmbiguous.class",
    "ProjectReadEpochObservationFailure\$GradleModelIncomplete.class",
    "ProjectReadEpochObservationFailure\$GradleModelUnavailable.class",
    "ProjectReadEpochObservationFailure\$GradleRootMalformed.class",
    "ProjectReadEpochObservationFailure\$GradleRootUnavailable.class",
    "ProjectReadEpochObservationFailure\$ImportTimestampsIncoherent.class",
    "ProjectReadEpochObservationFailure\$ObservationFailed.class",
    "ProjectReadEpochObservationFailure\$ProjectDisposed.class",
    "ProjectReadEpochObservationFailure\$ProjectNotInitialized.class",
    "ProjectReadEpochObservationFailure\$ProjectNotOpen.class",
    "ProjectReadEpochObservationFailure\$ProjectRootMalformed.class",
    "ProjectReadEpochObservationFailure\$ProjectRootUnavailable.class",
    "ProjectReadEpochObservationFailure\$ReadPreempted.class",
    "ProjectReadEpochObservationFailure\$SignalExhausted.class",
    "ProjectReadEpochObservationFailure\$VfsBatchLimitExceeded.class",
    "ProjectReadEpochObservationFailure\$VfsPathMalformed.class",
    "ProjectReadEpochObservationFailure\$WrongThread.class",
    "ProjectReadEpochObservationStage.class",
    "ProjectReadEpochRelation.class",
).map { name -> CONTRACT + name }

private fun adapterEpochResources(): List<String> = listOf(
    "DumbModeSignal.class",
    "EpochImportState.class",
    "EpochImportState\$Companion.class",
    "EpochPlatformObservation.class",
    "EpochPlatformObservation\$Failed.class",
    "EpochPlatformObservation\$Observed.class",
    "EpochRootComparisonKey.class",
    "EpochRootComparisonKey\$Companion.class",
    "EpochSignalAuthority.class",
    "EpochSignalCount.class",
    "EpochSignalCount\$Companion.class",
    "GradleEpochRootIdentity.class",
    "GradleEpochRootIdentity\$Companion.class",
    "GradleEpochRootIdentity\$Companion\$admit\$1.class",
    "IdeaProjectReadEpochExecution.class",
    "LiveProjectReadEpochObservationKt.class",
    "LiveProjectReadEpochPlatformPort.class",
    "LiveProjectReadEpochSource.class",
    "LiveProjectReadEpochSource\$observeState\$1.class",
    "LiveProjectReadEpochSource\$source\$1.class",
    "LiveProjectReadEpochSourceFactory.class",
    "LiveProjectReadEpochSourceFactory\$create\$1.class",
    "ObservedEpochGradleModel.class",
    "ProjectEpochRootIdentity.class",
    "ProjectEpochRootIdentity\$Companion.class",
    "ProjectEpochRootIdentity\$Companion\$admit\$1.class",
    "ProjectGradleRootRelation.class",
    "ProjectModelSignal.class",
    "ProjectReadEpochBoundary.class",
    "ProjectReadEpochExecution.class",
    "ProjectReadEpochIdentityKt.class",
    "ProjectReadEpochMetadataCounter.class",
    "ProjectReadEpochObservationKt.class",
    "ProjectReadEpochPlatformPort.class",
    "ProjectReadEpochSignalSample.class",
    "ProjectReadEpochSignalSample\$Rejected.class",
    "ProjectReadEpochSignalSample\$Value.class",
    "ProjectReadEpochState.class",
    "ProjectReadEpochState\$Companion.class",
    "ProjectReadEpochVfsBatchObservation.class",
    "ProjectReadEpochVfsBatchObservation\$OutsideRoot.class",
    "ProjectReadEpochVfsBatchObservation\$Rejected.class",
    "ProjectReadEpochVfsBatchObservation\$TouchesRoot.class",
    "ProjectReadEpochVfsEvent.class",
    "ProjectReadEpochVfsEvent\$Change.class",
    "ProjectReadEpochVfsEvent\$Move.class",
    "ProjectReadEpochVfsEvent\$Rename.class",
    "ProjectReadEpochVfsPath.class",
    "ProjectReadEpochVfsPath\$Companion.class",
    "ProjectReadEpochVfsRoot.class",
    "ProjectReadEpochVfsRoot\$Companion.class",
    "PsiSignal.class",
    "RootFilteredProjectEpochVfsListener.class",
    "RootModelSignal.class",
    "VfsSignal.class",
).map { name -> ADAPTER + name }

private fun admissionBridgeResources(): List<String> = listOf(
    "AdmittedIdeProject.class",
    "AdmittedIdeProject\$Companion.class",
    "AdmittedIdeProject\$Companion\$WhenMappings.class",
    "ExistingProjectReadEpochSourceFactory.class",
    "ExistingProjectReadEpochSourceInstallationFailure.class",
    "ExistingProjectReadEpochSourceInstallationFailure\$ProjectDisposed.class",
    "LiveProjectHandle.class",
).map { name -> ADAPTER + name }

private const val CONTRACT = "io/github/amichne/kast/workspace/contract/"
private const val ADAPTER = "io/github/amichne/kast/workspace/intellij/read/"
