package support.delivery

internal fun deliveryTasksM0M1(): List<TaskNode> = listOf(
            TaskNode(
                id = TaskId("KVP-001"), title = "Freeze program authorities and contradictions", goal = "Bind the exact current head, requirement fingerprint, source digests, obsolete assumptions, and unproven claims before implementation work begins.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, emptySet()),
                allowedReads = listOf("settings.gradle.kts", "build.gradle.kts", "build-logic", "indexer", "cli", "runtime", "workspace", "symbol") + KastVfsPassiveReusedIndexProgram.authoritySourceCandidates.map { it.value }, allowedWrites = listOf(KastVfsPassiveReusedIndexProgram.authorityLedgerOutputPath.value, KastVfsPassiveReusedIndexProgram.authorityContradictionOutputPath.value, KastVfsPassiveReusedIndexProgram.authorityVerificationOutputPath.value),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "KVP-REQ-001", "kind" to "requirement"), mapOf("id" to "KVP-REQ-002", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.001.proof", "PROOF_ARTIFACT", KastVfsPassiveReusedIndexProgram.authorityVerificationOutputPath.value, "Emits one authority ledger bound to current head and all source digests.")),
                publicInterface = "ProgramAuthority", internalImplementation = "Typed authority ledger and contradiction set generated from exact inputs.",
                effects = setOf(EffectId("METADATA_READ"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("METADATA", "BUILD_POLICY"),
                forbiddenWork = listOf("Production behavior changes", "Manual progress fields", "Silently retaining the old two-process authority"),
                red = ProofCommand("KVP-001-RED", "./gradlew verifyKastVfsPassiveAuthorityNegative", "Rejects a stale head, changed requirement digest, omitted contradiction, or obsolete two-process assumption."),
                green = ProofCommand("KVP-001-GREEN", "./gradlew verifyKastVfsPassiveAuthority", "Emits one authority ledger bound to current head and all source digests."),
                reviewBoundary = "Only authority and contradiction artifacts may change.",
                completionReceipt = CompletionReceiptContract("KVP-001-COMPLETE", setOf("KVP-001-RED", "KVP-001-GREEN"), emptySet(), "build/reports/delivery/receipts/KVP-001-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-001"), RequirementId("KVP-REQ-002"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM")),
            ),
            TaskNode(
                id = TaskId("KVP-002"), title = "Define proof-preserving delivery types", goal = "Define distinct types for identity, generation, dependency, authority, effect, cost, evidence, gate, receipt, progression, and closed outcomes.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-001"))),
                allowedReads = listOf(KastVfsPassiveReusedIndexProgram.authorityLedgerOutputPath.value, "build-logic/src/main/kotlin/support/architecture"), allowedWrites = listOf("build-logic/src/main/kotlin/support/delivery/DeliveryProgramModel.kt", "build-logic/src/test/kotlin/support/delivery/DeliveryProgramModelTest.kt"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.001.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-002", "kind" to "requirement"), mapOf("id" to "KVP-REQ-004", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.002.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-002-types.json", "Illegal states fail construction and closed outcomes are exhaustive.")),
                publicInterface = "DeliveryProgram domain types", internalImplementation = "Value classes, closed variants, smart constructors, and exhaustive transitions.",
                effects = setOf(EffectId("PURE"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Boolean completion fields", "Nullable authority", "Stringly typed edge kinds", "Unchecked constructors"),
                red = ProofCommand("KVP-002-RED", "./gradlew :build-logic:test --tests \"*DeliveryProgramModelNegativeTest\"", "Invalid IDs, empty evidence, illegal status fields, or primitive authority remain representable."),
                green = ProofCommand("KVP-002-GREEN", "./gradlew :build-logic:test --tests \"*DeliveryProgramModelTest\"", "Illegal states fail construction and closed outcomes are exhaustive."),
                reviewBoundary = "No Gradle task registration or product code changes.",
                completionReceipt = CompletionReceiptContract("KVP-002-COMPLETE", setOf("KVP-002-RED", "KVP-002-GREEN"), setOf("KVP-001-COMPLETE"), "build/reports/delivery/receipts/KVP-002-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-002"), RequirementId("KVP-REQ-004"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM")),
            ),
            TaskNode(
                id = TaskId("KVP-003"), title = "Encode dependency, join, retirement, invalidation, and recovery edges", goal = "Represent all-of, one-of, selected-lane joins, retirement edges, invalidation edges, and recovery transitions as typed graph semantics.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-002"))),
                allowedReads = listOf("build-logic/src/main/kotlin/support/delivery/DeliveryProgramModel.kt"), allowedWrites = listOf("build-logic/src/main/kotlin/support/delivery/DeliveryGraph.kt", "build-logic/src/test/kotlin/support/delivery/DeliveryGraphTest.kt"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.002.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-002", "kind" to "requirement"), mapOf("id" to "KVP-REQ-003", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.003.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-003-graph.json", "All graph semantics validate and topological waves derive mechanically.")),
                publicInterface = "TypedGraph", internalImplementation = "Acyclic task graph plus explicit non-ordering lifecycle edges.",
                effects = setOf(EffectId("PURE"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Flattening alternatives into dependsOn", "Manual waves", "Unbound retirement target", "Recovery as a final sequential node"),
                red = ProofCommand("KVP-003-RED", "./gradlew :build-logic:test --tests \"*DeliveryGraphNegativeTest\"", "Cycles, impossible joins, missing retirement targets, and recovery dead ends are accepted."),
                green = ProofCommand("KVP-003-GREEN", "./gradlew :build-logic:test --tests \"*DeliveryGraphTest\"", "All graph semantics validate and topological waves derive mechanically."),
                reviewBoundary = "Only graph semantics and fixtures may change.",
                completionReceipt = CompletionReceiptContract("KVP-003-COMPLETE", setOf("KVP-003-RED", "KVP-003-GREEN"), setOf("KVP-002-COMPLETE"), "build/reports/delivery/receipts/KVP-003-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-002"), RequirementId("KVP-REQ-003"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM")),
            ),
            TaskNode(
                id = TaskId("KVP-004"), title = "Encode the canonical Kotlin delivery graph", goal = "Materialize every atomic task, module boundary, authority owner, effect owner, process transition, and gate in one Kotlin program object.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-002"), TaskId("KVP-003"))),
                allowedReads = listOf("build-logic/src/main/kotlin/support/delivery", KastVfsPassiveReusedIndexProgram.authorityLedgerOutputPath.value), allowedWrites = listOf("build-logic/src/main/kotlin/support/delivery/KastVfsPassiveReusedIndexProgram.kt", "build-logic/src/test/kotlin/support/delivery/KastVfsPassiveReusedIndexProgramTest.kt"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.002.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.003.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-002", "kind" to "requirement"), mapOf("id" to "KVP-REQ-003", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.004.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-004-program.json", "The canonical graph validates, is connected, and reaches exactly one terminal proof.")),
                publicInterface = "KastVfsPassiveReusedIndexProgram", internalImplementation = "Repository-local DSL definition with no status or wave literals.",
                effects = setOf(EffectId("PURE"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Duplicate authority owners", "Missing task contract fields", "Untraced requirement", "Manually assigned wave"),
                red = ProofCommand("KVP-004-RED", "./gradlew :build-logic:test --tests \"*KastVfsPassiveProgramNegativeTest\"", "The incomplete or contradictory graph is accepted."),
                green = ProofCommand("KVP-004-GREEN", "./gradlew :build-logic:test --tests \"*KastVfsPassiveReusedIndexProgramTest\"", "The canonical graph validates, is connected, and reaches exactly one terminal proof."),
                reviewBoundary = "No generated JSON may be hand-edited as authority.",
                completionReceipt = CompletionReceiptContract("KVP-004-COMPLETE", setOf("KVP-004-RED", "KVP-004-GREEN"), setOf("KVP-002-COMPLETE", "KVP-003-COMPLETE"), "build/reports/delivery/receipts/KVP-004-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-002"), RequirementId("KVP-REQ-003"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM")),
            ),
            TaskNode(
                id = TaskId("KVP-005"), title = "Generate deterministic projections and JSON Schemas", goal = "Project the Kotlin authority deterministically to task, module, process, gate, and requirement JSON and validate each artifact against its schema.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-004"))),
                allowedReads = listOf("build-logic/src/main/kotlin/support/delivery/KastVfsPassiveReusedIndexProgram.kt"), allowedWrites = listOf("gradle/delivery/kast-vfs-passive-reused-index-program.json", "gradle/delivery/kast-vfs-passive-requirements.json", "gradle/delivery/schema/delivery-program.schema.json", "gradle/delivery/schema/proof-receipt.schema.json", "gradle/delivery/schema/requirement-trace.schema.json"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.004.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-003", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.005.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-005-projection.json", "Two generations are byte-identical and every JSON artifact validates.")),
                publicInterface = "DeterministicProgramProjection", internalImplementation = "Canonical key ordering, stable task ordering, derived waves, and SHA-256 program fingerprint.",
                effects = setOf(EffectId("PURE"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Timestamps in projection", "Unsorted map iteration", "Status fields", "Projection-only facts"),
                red = ProofCommand("KVP-005-RED", "./gradlew verifyKastVfsPassiveProjectionNegative", "A reordered input or repeated generation changes bytes or schema-invalid output passes."),
                green = ProofCommand("KVP-005-GREEN", "./gradlew generateKastVfsPassiveProjection verifyKastVfsPassiveProjection", "Two generations are byte-identical and every JSON artifact validates."),
                reviewBoundary = "Generated projections and schemas only.",
                completionReceipt = CompletionReceiptContract("KVP-005-COMPLETE", setOf("KVP-005-RED", "KVP-005-GREEN"), setOf("KVP-004-COMPLETE"), "build/reports/delivery/receipts/KVP-005-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-003"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM")),
            ),
            TaskNode(
                id = TaskId("KVP-006"), title = "Register the Gradle delivery-program gate graph", goal = "Add the convention plugin that registers structural checks, per-gate proof tasks, receipt tasks, state derivation, and the terminal proof task.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-003"), TaskId("KVP-005"))),
                allowedReads = listOf("build-logic/src/main/kotlin/support/delivery", "gradle/delivery/kast-vfs-passive-reused-index-program.json", "build-logic/src/main/kotlin/kast.architecture.gradle.kts"), allowedWrites = listOf("build-logic/src/main/kotlin/kast.vfs-passive-delivery.gradle.kts", "build-logic/src/main/kotlin/support/delivery/gradle/DeliveryProgramTasks.kt", "build.gradle.kts"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.003.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.005.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-002", "kind" to "requirement"), mapOf("id" to "KVP-REQ-003", "kind" to "requirement"), mapOf("id" to "KVP-REQ-004", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.006.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-006-gradle-gates.json", "Every gate consumes declared predecessor receipts and owns one output receipt.")),
                publicInterface = "Gradle gate graph", internalImplementation = "Task registration driven only by the typed program definition.",
                effects = setOf(EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Hard-coded manual completion", "Gate without declared inputs", "Receipt output shared by two gates", "Gradle task not represented by a gate"),
                red = ProofCommand("KVP-006-RED", "./gradlew verifyKastVfsPassiveGateGraphNegative", "Missing predecessor receipt inputs or duplicate receipt outputs are accepted."),
                green = ProofCommand("KVP-006-GREEN", "./gradlew verifyKastVfsPassiveGateGraph", "Every gate consumes declared predecessor receipts and owns one output receipt."),
                reviewBoundary = "Build policy and root plugin application only.",
                completionReceipt = CompletionReceiptContract("KVP-006-COMPLETE", setOf("KVP-006-RED", "KVP-006-GREEN"), setOf("KVP-003-COMPLETE", "KVP-005-COMPLETE"), "build/reports/delivery/receipts/KVP-006-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-002"), RequirementId("KVP-REQ-003"), RequirementId("KVP-REQ-004")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM")),
            ),
            TaskNode(
                id = TaskId("KVP-007"), title = "Bind and validate proof-carrying gate receipts", goal = "Define receipt creation and admission over program fingerprint, exact head, dependency receipt digests, input digest, command digest, observations, and artifact digests.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-006"))),
                allowedReads = listOf("build-logic/src/main/kotlin/support/delivery", "gradle/delivery/schema/proof-receipt.schema.json"), allowedWrites = listOf("build-logic/src/main/kotlin/support/delivery/DeliveryProof.kt", "build-logic/src/test/kotlin/support/delivery/DeliveryProofTest.kt", "gradle/delivery/schema/proof-receipt.schema.json"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.006.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-004", "kind" to "requirement"), mapOf("id" to "KVP-REQ-023", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.007.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-007-receipts.json", "Every changed head, requirement, command, dependency, input, or artifact invalidates proof.")),
                publicInterface = "ProofReceipt", internalImplementation = "Canonical receipt codec, digest, dependency closure, and invalidation rules.",
                effects = setOf(EffectId("PURE"), EffectId("FILESYSTEM_READ"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Receipt without exact head", "Receipt without command digest", "Trusting filename as identity", "Editable PASS field"),
                red = ProofCommand("KVP-007-RED", "./gradlew :build-logic:test --tests \"*DeliveryProofNegativeTest\"", "Forged, stale, dependency-mismatched, or artifact-mismatched receipts are admitted."),
                green = ProofCommand("KVP-007-GREEN", "./gradlew :build-logic:test --tests \"*DeliveryProofTest\"", "Every changed head, requirement, command, dependency, input, or artifact invalidates proof."),
                reviewBoundary = "Receipt code, schema, and fixtures only.",
                completionReceipt = CompletionReceiptContract("KVP-007-COMPLETE", setOf("KVP-007-RED", "KVP-007-GREEN"), setOf("KVP-006-COMPLETE"), "build/reports/delivery/receipts/KVP-007-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-004"), RequirementId("KVP-REQ-023"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("PROOF_RECEIPT")),
            ),
            TaskNode(
                id = TaskId("KVP-008"), title = "Derive progression and terminal completion", goal = "Derive blocked, ready, invalid, and proven tasks, requirement PASS states, critical path, and terminal completion solely from admitted receipts.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-007"))),
                allowedReads = listOf("gradle/delivery/kast-vfs-passive-reused-index-program.json", "build/reports/delivery/receipts"), allowedWrites = listOf("build-logic/src/main/kotlin/support/delivery/DeliveryState.kt", "build-logic/src/test/kotlin/support/delivery/DeliveryStateTest.kt"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.007.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-004", "kind" to "requirement"), mapOf("id" to "KVP-REQ-025", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.008.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-008-derived-state.json", "Only a complete exact-head receipt closure derives terminal completion.")),
                publicInterface = "DerivedProgramState", internalImplementation = "Pure receipt fold with no writable status or completion flag.",
                effects = setOf(EffectId("PURE"), EffectId("FILESYSTEM_READ"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Manual task completion", "Partial requirement success", "Completion with stale receipt", "Completion before final revalidation"),
                red = ProofCommand("KVP-008-RED", "./gradlew :build-logic:test --tests \"*DeliveryStateNegativeTest\"", "A manual flag, missing receipt, or stale receipt can report complete."),
                green = ProofCommand("KVP-008-GREEN", "./gradlew :build-logic:test --tests \"*DeliveryStateTest\"", "Only a complete exact-head receipt closure derives terminal completion."),
                reviewBoundary = "Progression model and reports only.",
                completionReceipt = CompletionReceiptContract("KVP-008-COMPLETE", setOf("KVP-008-RED", "KVP-008-GREEN"), setOf("KVP-007-COMPLETE"), "build/reports/delivery/receipts/KVP-008-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-004"), RequirementId("KVP-REQ-025"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM"), AuthorityId("PROOF_RECEIPT")),
            ),
            TaskNode(
                id = TaskId("KVP-009"), title = "Enforce the IDE-read module and effect firewall", goal = "Add module roles and forbidden-reference checks that make the plugin unable to recover project-open, import, refresh, write, topology, JDBC, or isolated-runtime authority.", milestone = "M0",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-001"), TaskId("KVP-006"))),
                allowedReads = listOf("build-logic/src/main/kotlin/support/architecture", "settings.gradle.kts", "workspace", "runtime", "symbol", "indexer"), allowedWrites = listOf("build-logic/src/main/kotlin/support/architecture", "gradle/architecture/kast-architecture-policy.json", "settings.gradle.kts"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.001.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.006.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-016", "kind" to "requirement"), mapOf("id" to "KVP-REQ-026", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.009.proof", "PROOF_ARTIFACT", "build/reports/delivery/KVP-009-firewall.json", "All invalid fixtures reject and the target read graph remains physically narrow.")),
                publicInterface = "IDE_READ_ONLY module role", internalImplementation = "Allowed dependency and bytecode reference policy for workspace:intellij-read, runtime:ide-read, and ide-plugin.",
                effects = setOf(EffectId("BUILD_POLICY_WRITE")), costs = setOf("BUILD_POLICY"),
                forbiddenWork = listOf("Adding allowlist exceptions for implementation convenience", "Service locator", "Generic Project or database handle crossing boundaries"),
                red = ProofCommand("KVP-009-RED", "./gradlew verifyKastVfsPassiveFirewallNegative", "Fixtures importing openProject, Gradle refresh, VFS refresh, change, topology, JDBC, or indexer process APIs compile."),
                green = ProofCommand("KVP-009-GREEN", "./gradlew verifyKastModuleGraph verifyForbiddenEffects verifyKastVfsPassiveFirewall", "All invalid fixtures reject and the target read graph remains physically narrow."),
                reviewBoundary = "Architecture policy, module declarations, and negative fixtures only.",
                completionReceipt = CompletionReceiptContract("KVP-009-COMPLETE", setOf("KVP-009-RED", "KVP-009-GREEN"), setOf("KVP-001-COMPLETE", "KVP-006-COMPLETE"), "build/reports/delivery/receipts/KVP-009-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-016"), RequirementId("KVP-REQ-026")), authorities = setOf(AuthorityId("DELIVERY_PROGRAM")),
            ),
            TaskNode(
                id = TaskId("KVP-010"), title = "Split a standalone IntelliJ plugin module", goal = "Move the private plugin payload out of the isolated indexer distribution into a first-class ide-plugin module without changing semantic behavior.", milestone = "M1",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-009"))),
                allowedReads = listOf("indexer/build.gradle.kts", "indexer/src/main", "runtime", "workspace", "symbol"), allowedWrites = listOf("ide-plugin", "settings.gradle.kts", "indexer/build.gradle.kts", "build-logic/src/main/kotlin"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.009.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-005", "kind" to "requirement"), mapOf("id" to "KVP-REQ-007", "kind" to "requirement"), mapOf("id" to "KVP-REQ-016", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.010.proof", "PROOF_ARTIFACT", "ide-plugin/build/reports/KVP-010-plugin.json", "Produces a standalone plugin ZIP from Kast classes and private non-platform libraries.")),
                publicInterface = "Kast IDE plugin artifact", internalImplementation = "Plugin module, descriptor, service registration point, and private library configuration.",
                effects = setOf(EffectId("PACKAGE_WRITE"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("PACKAGE_BUILD"),
                forbiddenWork = listOf("Copying idea-home", "Bundling IntelliJ/Kotlin/Gradle platform JARs", "Changing operation semantics"),
                red = ProofCommand("KVP-010-RED", "./gradlew :ide-plugin:standalonePluginNegativeProof", "No standalone plugin exists or the artifact still depends on private idea-home layout."),
                green = ProofCommand("KVP-010-GREEN", "./gradlew :ide-plugin:buildPlugin", "Produces a standalone plugin ZIP from Kast classes and private non-platform libraries."),
                reviewBoundary = "Only module split and packaging ownership.",
                completionReceipt = CompletionReceiptContract("KVP-010-COMPLETE", setOf("KVP-010-RED", "KVP-010-GREEN"), setOf("KVP-009-COMPLETE"), "build/reports/delivery/receipts/KVP-010-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-005"), RequirementId("KVP-REQ-007"), RequirementId("KVP-REQ-016")), authorities = setOf(AuthorityId("DEFAULT_DISTRIBUTION")),
            ),
            TaskNode(
                id = TaskId("KVP-011"), title = "Prove plugin layout and classpath closure", goal = "Reject every platform, bootstrap, mutation, topology, JDBC, runtime-acquisition, and process-launch artifact from the plugin ZIP and runtime classpath.", milestone = "M1",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-010"))),
                allowedReads = listOf("ide-plugin/build.gradle.kts", "ide-plugin/src", "runtime/ide-read", "workspace/intellij-read"), allowedWrites = listOf("build-logic/src/main/kotlin/support/tasks/VerifyIdeHostedPluginLayoutTask.kt", "ide-plugin/src/test"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.010.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-007", "kind" to "requirement"), mapOf("id" to "KVP-REQ-016", "kind" to "requirement"), mapOf("id" to "KVP-REQ-021", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.011.proof", "PROOF_ARTIFACT", "ide-plugin/build/reports/KVP-011-layout.json", "Plugin contents and transitive classpath satisfy the read-only policy and size ceiling.")),
                publicInterface = "VerifiedIdePluginLayout", internalImplementation = "Artifact inventory and bytecode owner report.",
                effects = setOf(EffectId("FILESYSTEM_READ"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("PACKAGE_BUILD"),
                forbiddenWork = listOf("Size-only verification", "Filename-only verification", "Allowing hidden shaded platform classes"),
                red = ProofCommand("KVP-011-RED", "./gradlew :ide-plugin:verifyPluginLayoutNegative", "Injected IntelliJ, Kotlin, Gradle, JBR, bootstrap, change, topology, or JDBC class is not detected."),
                green = ProofCommand("KVP-011-GREEN", "./gradlew :ide-plugin:verifyPluginLayout", "Plugin contents and transitive classpath satisfy the read-only policy and size ceiling."),
                reviewBoundary = "Layout verifier and plugin tests only.",
                completionReceipt = CompletionReceiptContract("KVP-011-COMPLETE", setOf("KVP-011-RED", "KVP-011-GREEN"), setOf("KVP-010-COMPLETE"), "build/reports/delivery/receipts/KVP-011-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-007"), RequirementId("KVP-REQ-016"), RequirementId("KVP-REQ-021")), authorities = setOf(AuthorityId("DEFAULT_DISTRIBUTION")),
            ),
            TaskNode(
                id = TaskId("KVP-012"), title = "Define IDE host compatibility identity", goal = "Parse IDE build, Kotlin plugin build, Kast plugin version, runtime protocol identity, registry digest, and wire-schema digest into one admitted compatibility value.", milestone = "M1",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-002"), TaskId("KVP-011"))),
                allowedReads = listOf("protocol", "ide-plugin", "gradle/libs.versions.toml"), allowedWrites = listOf("workspace/contract", "protocol/contract", "ide-plugin/src/main/kotlin"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.002.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.011.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-017", "kind" to "requirement"), mapOf("id" to "KVP-REQ-018", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.012.proof", "PROOF_ARTIFACT", "ide-plugin/build/reports/KVP-012-compatibility.json", "Only one exact supported compatibility tuple is admitted.")),
                publicInterface = "AdmittedIdeHostCompatibility", internalImplementation = "Closed compatibility parser and mismatch failures.",
                effects = setOf(EffectId("PURE"), EffectId("METADATA_READ")), costs = setOf("METADATA"),
                forbiddenWork = listOf("Loose version comparison", "Ignoring Kotlin plugin build", "Boolean compatible flag", "Unknown capability acceptance"),
                red = ProofCommand("KVP-012-RED", "./gradlew :ide-plugin:test --tests \"*IdeHostCompatibilityNegativeTest\"", "Wrong IDE, Kotlin, plugin, registry, wire, or capability identity is accepted."),
                green = ProofCommand("KVP-012-GREEN", "./gradlew :ide-plugin:test --tests \"*IdeHostCompatibilityTest\"", "Only one exact supported compatibility tuple is admitted."),
                reviewBoundary = "Compatibility contract and tests only.",
                completionReceipt = CompletionReceiptContract("KVP-012-COMPLETE", setOf("KVP-012-RED", "KVP-012-GREEN"), setOf("KVP-002-COMPLETE", "KVP-011-COMPLETE"), "build/reports/delivery/receipts/KVP-012-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-017"), RequirementId("KVP-REQ-018")), authorities = setOf(AuthorityId("IDE_ENDPOINT")),
            ),
            TaskNode(
                id = TaskId("KVP-013"), title = "Define the project endpoint descriptor schema", goal = "Create endpoint schema v2 carrying exact root, host kind, PID, compatibility identity, socket, framing, epoch capability, and exact operation set.", milestone = "M1",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-005"), TaskId("KVP-012"))),
                allowedReads = listOf("indexer/src/main/kotlin/io/github/amichne/kast/indexer/IndexerEndpointDescriptor.kt", "protocol/wire", "ide-plugin"), allowedWrites = listOf("protocol/wire", "ide-plugin/src/main/kotlin", "gradle/delivery/schema/ide-endpoint.schema.json"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.005.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.012.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-008", "kind" to "requirement"), mapOf("id" to "KVP-REQ-009", "kind" to "requirement"), mapOf("id" to "KVP-REQ-017", "kind" to "requirement"), mapOf("id" to "KVP-REQ-018", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.013.proof", "PROOF_ARTIFACT", "protocol/wire/build/reports/KVP-013-endpoint-schema.json", "Descriptor round-trips exactly and every mismatch remains a closed rejection.")),
                publicInterface = "IdeEndpointDescriptorV2", internalImplementation = "Generated serialization, strict parsing, and canonical digest.",
                effects = setOf(EffectId("PURE"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("METADATA"),
                forbiddenWork = listOf("Reusing v1 without host proof", "Unknown fields", "Missing capability set", "Raw string validation downstream"),
                red = ProofCommand("KVP-013-RED", "./gradlew :protocol:wire:test --tests \"*IdeEndpointDescriptorNegativeTest\"", "Malformed, ambiguous, stale, or under-specified endpoint documents are admitted."),
                green = ProofCommand("KVP-013-GREEN", "./gradlew :protocol:wire:test --tests \"*IdeEndpointDescriptorTest\"", "Descriptor round-trips exactly and every mismatch remains a closed rejection."),
                reviewBoundary = "Endpoint contract, codec, and schema only.",
                completionReceipt = CompletionReceiptContract("KVP-013-COMPLETE", setOf("KVP-013-RED", "KVP-013-GREEN"), setOf("KVP-005-COMPLETE", "KVP-012-COMPLETE"), "build/reports/delivery/receipts/KVP-013-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-008"), RequirementId("KVP-REQ-009"), RequirementId("KVP-REQ-017"), RequirementId("KVP-REQ-018")), authorities = setOf(AuthorityId("WIRE_SCHEMA"), AuthorityId("IDE_ENDPOINT")),
            ),
)
