package support.delivery

internal fun deliveryTasksM2(): List<TaskNode> = listOf(
            TaskNode(
                id = TaskId("KVP-014"), title = "Admit the existing open IntelliJ Project", goal = "Refine the Project supplied by IntelliJ into one exact-root, non-disposed, Gradle-model-ready, K2-capable read authority without opening or importing anything.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-009"), TaskId("KVP-012"))),
                allowedReads = listOf("workspace/intellij/src/main", "workspace/contract", "ide-plugin"), allowedWrites = listOf("workspace/intellij-read", "workspace/contract"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.009.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.012.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-005", "kind" to "requirement"), mapOf("id" to "KVP-REQ-006", "kind" to "requirement"), mapOf("id" to "KVP-REQ-011", "kind" to "requirement"), mapOf("id" to "KVP-REQ-012", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.014.proof", "PROOF_ARTIFACT", "workspace/intellij-read/build/reports/KVP-014-project-admission.json", "Only the already-open exact Project yields AdmittedIdeProject and no stronger effect occurs.")),
                publicInterface = "AdmittedIdeProject", internalImplementation = "Project admission adapter with closed root, disposal, model, and plugin failures.",
                effects = setOf(EffectId("IDE_PROJECT_READ")), costs = setOf("METADATA"),
                forbiddenWork = listOf("ProjectManagerEx.openProject", "InstalledIntellijWorkspace.open", "ExternalSystemUtil link or refresh", "Waiting for indexing"),
                red = ProofCommand("KVP-014-RED", "./gradlew :workspace:intellij-read:test --tests \"*ExistingProjectAdmissionNegativeTest\"", "Wrong-root, disposed, unimported, dumb, or incompatible Projects are admitted or trigger repair."),
                green = ProofCommand("KVP-014-GREEN", "./gradlew :workspace:intellij-read:test --tests \"*ExistingProjectAdmissionTest\"", "Only the already-open exact Project yields AdmittedIdeProject and no stronger effect occurs."),
                reviewBoundary = "New read adapter and contract only; existing bootstrap remains untouched.",
                completionReceipt = CompletionReceiptContract("KVP-014-COMPLETE", setOf("KVP-014-RED", "KVP-014-GREEN"), setOf("KVP-009-COMPLETE", "KVP-012-COMPLETE"), "build/reports/delivery/receipts/KVP-014-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-005"), RequirementId("KVP-REQ-006"), RequirementId("KVP-REQ-011"), RequirementId("KVP-REQ-012")), authorities = setOf(AuthorityId("OPEN_PROJECT"), AuthorityId("CANONICAL_ROOT")),
            ),
            TaskNode(
                id = TaskId("KVP-015"), title = "Characterize model and epoch signals", goal = "Produce executable evidence for the supported project-model, PSI, VFS, root-model, and dumb-mode signals that can define a stable read epoch without refresh or repository scanning.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-014"))),
                allowedReads = listOf("workspace/intellij-read", "gradle/libs.versions.toml", "fixtures"), allowedWrites = listOf("workspace/intellij-read/src/test", "docs/engineering/ide-read-epoch-ledger.md"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.014.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-011", "kind" to "requirement"), mapOf("id" to "KVP-REQ-012", "kind" to "requirement"), mapOf("id" to "KVP-REQ-015", "kind" to "requirement"), mapOf("id" to "KVP-REQ-027", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.015.proof", "PROOF_ARTIFACT", "workspace/intellij-read/build/reports/KVP-015-epoch-ledger.json", "The selected signals detect every fixture movement without refresh or source-tree walk.")),
                publicInterface = "IdeEpochSignalLedger", internalImplementation = "Supported-build tests and selected signal set.",
                effects = setOf(EffectId("IDE_PROJECT_READ"), EffectId("NATIVE_INDEX_READ")), costs = setOf("SEMANTIC_READ"),
                forbiddenWork = listOf("Freezing an epoch contract from undocumented assumptions", "Calling refresh to observe disk", "Using one global Boolean readiness flag"),
                red = ProofCommand("KVP-015-RED", "./gradlew :workspace:intellij-read:characterizeEpochNegative", "Signal gaps, movement, dumb-mode transitions, and root-model changes are not detected."),
                green = ProofCommand("KVP-015-GREEN", "./gradlew :workspace:intellij-read:characterizeEpoch", "The selected signals detect every fixture movement without refresh or source-tree walk."),
                reviewBoundary = "Characterization fixtures and ledger only.",
                completionReceipt = CompletionReceiptContract("KVP-015-COMPLETE", setOf("KVP-015-RED", "KVP-015-GREEN"), setOf("KVP-014-COMPLETE"), "build/reports/delivery/receipts/KVP-015-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-011"), RequirementId("KVP-REQ-012"), RequirementId("KVP-REQ-015"), RequirementId("KVP-REQ-027")), authorities = setOf(AuthorityId("READ_EPOCH")),
            ),
            TaskNode(
                id = TaskId("KVP-016"), title = "Capture a detached existing-project model", goal = "Read and detach root, modules, source roots, Gradle ownership, SDK, classpath identity, compatibility, and epoch from the admitted Project in a short cancellable read.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-014"), TaskId("KVP-015"))),
                allowedReads = listOf("workspace/intellij-read", "workspace/contract", "runtime/composition/src/main/kotlin/io/github/amichne/kast/runtime/composition/platform"), allowedWrites = listOf("workspace/intellij-read", "workspace/contract", "runtime/ide-read"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.014.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.015.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-005", "kind" to "requirement"), mapOf("id" to "KVP-REQ-012", "kind" to "requirement"), mapOf("id" to "KVP-REQ-015", "kind" to "requirement"), mapOf("id" to "KVP-REQ-016", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.016.proof", "PROOF_ARTIFACT", "workspace/intellij-read/build/reports/KVP-016-detached-model.json", "Capture is detached, bounded, cancellable, exact-root, and model-complete.")),
                publicInterface = "DetachedIdeWorkspaceModel", internalImplementation = "Short read adapter returning immutable values only.",
                effects = setOf(EffectId("IDE_PROJECT_READ")), costs = setOf("SEMANTIC_READ"),
                forbiddenWork = listOf("Leaking Project, VirtualFile, Module, SearchScope, PSI, or Gradle DataNode", "Importing missing model", "Blocking read action"),
                red = ProofCommand("KVP-016-RED", "./gradlew :workspace:intellij-read:test --tests \"*DetachedModelNegativeTest\"", "Live platform objects escape or capture repairs missing state."),
                green = ProofCommand("KVP-016-GREEN", "./gradlew :workspace:intellij-read:test --tests \"*DetachedModelTest\"", "Capture is detached, bounded, cancellable, exact-root, and model-complete."),
                reviewBoundary = "Model capture only; no freshness policy or operation routing.",
                completionReceipt = CompletionReceiptContract("KVP-016-COMPLETE", setOf("KVP-016-RED", "KVP-016-GREEN"), setOf("KVP-014-COMPLETE", "KVP-015-COMPLETE"), "build/reports/delivery/receipts/KVP-016-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-005"), RequirementId("KVP-REQ-012"), RequirementId("KVP-REQ-015"), RequirementId("KVP-REQ-016")), authorities = setOf(AuthorityId("OPEN_PROJECT"), AuthorityId("READ_EPOCH")),
            ),
            TaskNode(
                id = TaskId("KVP-017"), title = "Define the project read epoch", goal = "Convert the characterized platform signals into one proof-carrying ProjectReadEpoch that can be observed before and after a semantic read.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-015"))),
                allowedReads = listOf("workspace/intellij-read/src/test", "docs/engineering/ide-read-epoch-ledger.md", "workspace/contract"), allowedWrites = listOf("workspace/contract", "workspace/intellij-read"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.015.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-012", "kind" to "requirement"), mapOf("id" to "KVP-REQ-015", "kind" to "requirement"), mapOf("id" to "KVP-REQ-027", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.017.proof", "PROOF_ARTIFACT", "workspace/intellij-read/build/reports/KVP-017-read-epoch.json", "Epochs compare only within one admitted Project/runtime and movement changes identity.")),
                publicInterface = "ProjectReadEpoch", internalImplementation = "Opaque comparable epoch plus finite observation failures.",
                effects = setOf(EffectId("PURE"), EffectId("IDE_PROJECT_READ")), costs = setOf("METADATA"),
                forbiddenWork = listOf("Primitive counters crossing modules", "Epoch recreated by callers", "Treating dumb mode as an epoch value"),
                red = ProofCommand("KVP-017-RED", "./gradlew :workspace:contract:test --tests \"*ProjectReadEpochNegativeTest\"", "Malformed or incomparable epochs and repeated validation remain possible."),
                green = ProofCommand("KVP-017-GREEN", "./gradlew :workspace:contract:test :workspace:intellij-read:test --tests \"*ProjectReadEpochTest\"", "Epochs compare only within one admitted Project/runtime and movement changes identity."),
                reviewBoundary = "Epoch contract and adapter only.",
                completionReceipt = CompletionReceiptContract("KVP-017-COMPLETE", setOf("KVP-017-RED", "KVP-017-GREEN"), setOf("KVP-015-COMPLETE"), "build/reports/delivery/receipts/KVP-017-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-012"), RequirementId("KVP-REQ-015"), RequirementId("KVP-REQ-027")), authorities = setOf(AuthorityId("READ_EPOCH")),
            ),
            TaskNode(
                id = TaskId("KVP-018"), title = "Remove source-tree hashing from the hosted read path", goal = "Ensure the hosted model and epoch path never performs Files.walk, source-content hashing, or physical repository traversal under an IntelliJ read lock.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-016"), TaskId("KVP-017"))),
                allowedReads = listOf("workspace/intellij/src/main/kotlin/io/github/amichne/kast/workspace/intellij/InstalledGradleModelCapture.kt", "workspace/intellij-read"), allowedWrites = listOf("workspace/intellij-read", "build-logic/src/main/kotlin/support/architecture"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.016.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.017.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-006", "kind" to "requirement"), mapOf("id" to "KVP-REQ-011", "kind" to "requirement"), mapOf("id" to "KVP-REQ-014", "kind" to "requirement"), mapOf("id" to "KVP-REQ-016", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.018.proof", "PROOF_ARTIFACT", "workspace/intellij-read/build/reports/KVP-018-no-walk.json", "Hosted read bytecode and traces contain zero repository walks and zero source hashes.")),
                publicInterface = "VfsPassiveHostedModelCapture", internalImplementation = "Hosted adapter separated from isolated content-hash bootstrap.",
                effects = setOf(EffectId("IDE_PROJECT_READ"), EffectId("BUILD_POLICY_WRITE")), costs = setOf("SEMANTIC_READ"),
                forbiddenWork = listOf("Moving Files.walk outside the read but retaining it on each request", "Hashing every source file", "Using LocalFileSystem refreshAndFind"),
                red = ProofCommand("KVP-018-RED", "./gradlew :workspace:intellij-read:verifyNoHostedRepositoryWalkNegative", "Injected Files.walk, hashing loop, or physical source scan is not detected."),
                green = ProofCommand("KVP-018-GREEN", "./gradlew :workspace:intellij-read:verifyNoHostedRepositoryWalk", "Hosted read bytecode and traces contain zero repository walks and zero source hashes."),
                reviewBoundary = "Hosted adapter and effect policy only; isolated fixture may retain old capture temporarily.",
                completionReceipt = CompletionReceiptContract("KVP-018-COMPLETE", setOf("KVP-018-RED", "KVP-018-GREEN"), setOf("KVP-016-COMPLETE", "KVP-017-COMPLETE"), "build/reports/delivery/receipts/KVP-018-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-006"), RequirementId("KVP-REQ-011"), RequirementId("KVP-REQ-014"), RequirementId("KVP-REQ-016")), authorities = setOf(AuthorityId("READ_EPOCH")),
            ),
            TaskNode(
                id = TaskId("KVP-019"), title = "Issue a VFS-passive freshness capability", goal = "Admit current IDE-visible state without refresh, listener-driven semantic work, import, or repair and bind it to ProjectReadEpoch.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-017"), TaskId("KVP-018"))),
                allowedReads = listOf("workspace/contract", "workspace/intellij-read", "build-logic/src/main/kotlin/support/architecture"), allowedWrites = listOf("workspace/contract", "workspace/intellij-read"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.017.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.018.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-011", "kind" to "requirement"), mapOf("id" to "KVP-REQ-012", "kind" to "requirement"), mapOf("id" to "KVP-REQ-015", "kind" to "requirement"), mapOf("id" to "KVP-REQ-027", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.019.proof", "PROOF_ARTIFACT", "workspace/intellij-read/build/reports/KVP-019-vfs-passive.json", "Admission reads only the IDE snapshot and returns a typed capability or closed rejection.")),
                publicInterface = "VfsPassiveReadCapability", internalImplementation = "Admission from exact Project plus epoch with closed dumb, disposed, busy, and unavailable failures.",
                effects = setOf(EffectId("IDE_PROJECT_READ")), costs = setOf("METADATA"),
                forbiddenWork = listOf("VFS refresh", "Gradle import", "Background repair", "Per-event semantic job", "VFS listener in the MVP read path"),
                red = ProofCommand("KVP-019-RED", "./gradlew :workspace:intellij-read:test --tests \"*VfsPassiveAdmissionNegativeTest\"", "Dirty or moved state causes refresh, repair, listener work, or false readiness."),
                green = ProofCommand("KVP-019-GREEN", "./gradlew :workspace:intellij-read:test --tests \"*VfsPassiveAdmissionTest\"", "Admission reads only the IDE snapshot and returns a typed capability or closed rejection."),
                reviewBoundary = "Freshness admission only.",
                completionReceipt = CompletionReceiptContract("KVP-019-COMPLETE", setOf("KVP-019-RED", "KVP-019-GREEN"), setOf("KVP-017-COMPLETE", "KVP-018-COMPLETE"), "build/reports/delivery/receipts/KVP-019-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-011"), RequirementId("KVP-REQ-012"), RequirementId("KVP-REQ-015"), RequirementId("KVP-REQ-027")), authorities = setOf(AuthorityId("READ_EPOCH")),
            ),
            TaskNode(
                id = TaskId("KVP-020"), title = "Enforce single-flight project read admission", goal = "Issue at most one active semantic read permit per Project with at most one bounded queued request and lifecycle cancellation.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-014"), TaskId("KVP-019"))),
                allowedReads = listOf("runtime/ide-read", "workspace/contract", "ide-plugin"), allowedWrites = listOf("runtime/ide-read", "runtime/ide-read/src/test"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.014.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.019.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-013", "kind" to "requirement"), mapOf("id" to "KVP-REQ-019", "kind" to "requirement"), mapOf("id" to "KVP-REQ-027", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.020.proof", "PROOF_ARTIFACT", "runtime/ide-read/build/reports/KVP-020-single-flight.json", "Active and queued bounds hold and cancellation releases authority exactly once.")),
                publicInterface = "ProjectReadPermit", internalImplementation = "Project-scoped permit state machine and Busy rejection.",
                effects = setOf(EffectId("PURE")), costs = setOf("SEMANTIC_READ"),
                forbiddenWork = listOf("Unbounded Channel", "Global lock across projects", "Holding permit after disconnect or disposal", "Parallel semantic reads by default"),
                red = ProofCommand("KVP-020-RED", "./gradlew :runtime:ide-read:test --tests \"*SingleFlightNegativeTest\"", "Concurrent requests exceed one active read or queue without bound."),
                green = ProofCommand("KVP-020-GREEN", "./gradlew :runtime:ide-read:test --tests \"*SingleFlightTest\"", "Active and queued bounds hold and cancellation releases authority exactly once."),
                reviewBoundary = "Admission state machine only.",
                completionReceipt = CompletionReceiptContract("KVP-020-COMPLETE", setOf("KVP-020-RED", "KVP-020-GREEN"), setOf("KVP-014-COMPLETE", "KVP-019-COMPLETE"), "build/reports/delivery/receipts/KVP-020-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-013"), RequirementId("KVP-REQ-019"), RequirementId("KVP-REQ-027")), authorities = setOf(AuthorityId("READ_RUNTIME")),
            ),
            TaskNode(
                id = TaskId("KVP-021"), title = "Execute cancellable smart reads", goal = "Run semantic work through write-priority cancellable smart read actions, propagate platform cancellation, and fail fast during dumb mode or disposal.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-019"), TaskId("KVP-020"))),
                allowedReads = listOf("symbol/intellij", "workspace/intellij-read", "runtime/ide-read"), allowedWrites = listOf("runtime/ide-read", "symbol/intellij/src/test"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.019.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.020.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-012", "kind" to "requirement"), mapOf("id" to "KVP-REQ-013", "kind" to "requirement"), mapOf("id" to "KVP-REQ-016", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.021.proof", "PROOF_ARTIFACT", "runtime/ide-read/build/reports/KVP-021-cancellable-read.json", "Reads cancel for writes, reject dumb/disposed state, and release permits.")),
                publicInterface = "CancellableProjectReadExecutor", internalImplementation = "Permit-scoped smart read wrapper with typed terminal outcomes.",
                effects = setOf(EffectId("IDE_PROJECT_READ"), EffectId("NATIVE_INDEX_READ"), EffectId("SEMANTIC_READ")), costs = setOf("SEMANTIC_READ"),
                forbiddenWork = listOf("ReadAction.computeBlocking", "waitForSmartMode", "Thread.sleep polling", "Swallowing ProcessCanceledException", "EDT execution"),
                red = ProofCommand("KVP-021-RED", "./gradlew :runtime:ide-read:test --tests \"*CancellableReadNegativeTest\"", "Write priority, cancellation, dumb mode, disposal, or timeout can hang or appear empty."),
                green = ProofCommand("KVP-021-GREEN", "./gradlew :runtime:ide-read:test --tests \"*CancellableReadTest\"", "Reads cancel for writes, reject dumb/disposed state, and release permits."),
                reviewBoundary = "Read executor only; no operation semantics.",
                completionReceipt = CompletionReceiptContract("KVP-021-COMPLETE", setOf("KVP-021-RED", "KVP-021-GREEN"), setOf("KVP-019-COMPLETE", "KVP-020-COMPLETE"), "build/reports/delivery/receipts/KVP-021-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-012"), RequirementId("KVP-REQ-013"), RequirementId("KVP-REQ-016")), authorities = setOf(AuthorityId("READ_RUNTIME")),
            ),
            TaskNode(
                id = TaskId("KVP-022"), title = "Revalidate the epoch before accepting a result", goal = "Observe ProjectReadEpoch before the read and after detached projection; accept only equality and reject every moved-state result.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-021"))),
                allowedReads = listOf("workspace/contract", "workspace/intellij-read", "runtime/ide-read"), allowedWrites = listOf("runtime/ide-read", "runtime/ide-read/src/test"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.021.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-010", "kind" to "requirement"), mapOf("id" to "KVP-REQ-012", "kind" to "requirement"), mapOf("id" to "KVP-REQ-015", "kind" to "requirement"), mapOf("id" to "KVP-REQ-027", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.022.proof", "PROOF_ARTIFACT", "runtime/ide-read/build/reports/KVP-022-epoch-revalidation.json", "Stable reads complete and moved reads return closed WorkspaceMoved rejection.")),
                publicInterface = "RevalidatedIdeReadResult", internalImplementation = "Proof transition from detached result plus equal before/after epochs.",
                effects = setOf(EffectId("IDE_PROJECT_READ"), EffectId("SEMANTIC_READ")), costs = setOf("SEMANTIC_READ"),
                forbiddenWork = listOf("Accepting stale output with a warning", "Retry loop without budget", "Reusing prior epoch after cancellation"),
                red = ProofCommand("KVP-022-RED", "./gradlew :runtime:ide-read:test --tests \"*EpochRevalidationNegativeTest\"", "Movement during query or projection can return Complete."),
                green = ProofCommand("KVP-022-GREEN", "./gradlew :runtime:ide-read:test --tests \"*EpochRevalidationTest\"", "Stable reads complete and moved reads return closed WorkspaceMoved rejection."),
                reviewBoundary = "Epoch revalidation only.",
                completionReceipt = CompletionReceiptContract("KVP-022-COMPLETE", setOf("KVP-022-RED", "KVP-022-GREEN"), setOf("KVP-021-COMPLETE"), "build/reports/delivery/receipts/KVP-022-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-010"), RequirementId("KVP-REQ-012"), RequirementId("KVP-REQ-015"), RequirementId("KVP-REQ-027")), authorities = setOf(AuthorityId("READ_EPOCH"), AuthorityId("READ_RUNTIME")),
            ),
            TaskNode(
                id = TaskId("KVP-023"), title = "Assemble the physically read-only IDE runtime", goal = "Construct exactly four operation bindings from read-only workspace and symbol ports without full composition, persistence, change, topology, bootstrap, or runtime acquisition.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-009"), TaskId("KVP-016"), TaskId("KVP-022"))),
                allowedReads = listOf("runtime/server", "runtime/composition", "workspace/service", "symbol/service", "protocol"), allowedWrites = listOf("runtime/ide-read", "runtime/ide-read/src/test", "settings.gradle.kts"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.009.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.016.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.022.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-009", "kind" to "requirement"), mapOf("id" to "KVP-REQ-016", "kind" to "requirement"), mapOf("id" to "KVP-REQ-018", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.023.proof", "PROOF_ARTIFACT", "runtime/ide-read/build/reports/KVP-023-read-runtime.json", "The graph contains exactly four operations and only read effects.")),
                publicInterface = "IdeReadRuntimeDispatch", internalImplementation = "Capability-scoped typed dispatch for the exact four MVP operations.",
                effects = setOf(EffectId("IDE_PROJECT_READ"), EffectId("NATIVE_INDEX_READ"), EffectId("SEMANTIC_READ")), costs = setOf("SEMANTIC_READ"),
                forbiddenWork = listOf("Depending on runtime:composition", "Depending on evidence:sqlite or change or topology", "Service locator", "Operation not in capability set"),
                red = ProofCommand("KVP-023-RED", "./gradlew :runtime:ide-read:verifyReadOnlyGraphNegative", "An injected stronger dependency or fifth operation is accepted."),
                green = ProofCommand("KVP-023-GREEN", "./gradlew :runtime:ide-read:test :runtime:ide-read:verifyReadOnlyGraph", "The graph contains exactly four operations and only read effects."),
                reviewBoundary = "New read composition only.",
                completionReceipt = CompletionReceiptContract("KVP-023-COMPLETE", setOf("KVP-023-RED", "KVP-023-GREEN"), setOf("KVP-009-COMPLETE", "KVP-016-COMPLETE", "KVP-022-COMPLETE"), "build/reports/delivery/receipts/KVP-023-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-009"), RequirementId("KVP-REQ-016"), RequirementId("KVP-REQ-018")), authorities = setOf(AuthorityId("READ_RUNTIME"), AuthorityId("OPERATION_REGISTRY")),
            ),
            TaskNode(
                id = TaskId("KVP-024"), title = "Publish the exact-root project endpoint", goal = "Start a Project-level service, bind one UDS endpoint, and atomically publish descriptor v2 only after read runtime construction succeeds.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-013"), TaskId("KVP-023"))),
                allowedReads = listOf("ide-plugin", "indexer/src/main/kotlin/io/github/amichne/kast/indexer/InstalledIndexerTransport.kt", "protocol/wire"), allowedWrites = listOf("ide-plugin/src/main/kotlin", "ide-plugin/src/test"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.013.proof", "kind" to "taskOutput"), mapOf("id" to "kvp.023.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-005", "kind" to "requirement"), mapOf("id" to "KVP-REQ-017", "kind" to "requirement"), mapOf("id" to "KVP-REQ-019", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.024.proof", "PROOF_ARTIFACT", "ide-plugin/build/reports/KVP-024-endpoint.json", "One exact endpoint becomes reachable only after complete runtime construction.")),
                publicInterface = "ReadyIdeEndpoint", internalImplementation = "Prepared endpoint to bound socket to atomically published descriptor transition.",
                effects = setOf(EffectId("UDS_BIND"), EffectId("ENDPOINT_DESCRIPTOR_WRITE")), costs = setOf("METADATA"),
                forbiddenWork = listOf("Publishing readiness before runtime construction", "Deleting occupied non-socket path", "Binding wrong root", "Multiple endpoints per Project"),
                red = ProofCommand("KVP-024-RED", "./gradlew :ide-plugin:test --tests \"*IdeEndpointPublicationNegativeTest\"", "Wrong-root, occupied, partial, or duplicate endpoint can advertise ready."),
                green = ProofCommand("KVP-024-GREEN", "./gradlew :ide-plugin:test --tests \"*IdeEndpointPublicationTest\"", "One exact endpoint becomes reachable only after complete runtime construction."),
                reviewBoundary = "Endpoint publication only.",
                completionReceipt = CompletionReceiptContract("KVP-024-COMPLETE", setOf("KVP-024-RED", "KVP-024-GREEN"), setOf("KVP-013-COMPLETE", "KVP-023-COMPLETE"), "build/reports/delivery/receipts/KVP-024-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-005"), RequirementId("KVP-REQ-017"), RequirementId("KVP-REQ-019")), authorities = setOf(AuthorityId("IDE_ENDPOINT")),
            ),
            TaskNode(
                id = TaskId("KVP-025"), title = "Bind endpoint retirement to Project and plugin lifecycle", goal = "Retire descriptor and socket on Project close, plugin unload, bind failure, runtime failure, and service cancellation with idempotent cleanup.", milestone = "M2",
                dependencies = DependencyExpression(EdgeKind.REQUIRES_ALL, setOf(TaskId("KVP-024"))),
                allowedReads = listOf("ide-plugin/src/main/kotlin", "protocol/wire"), allowedWrites = listOf("ide-plugin/src/main/kotlin", "ide-plugin/src/test"),
                inputs = listOf(mapOf("id" to "CURRENT_HEAD", "kind" to "baseline"), mapOf("id" to "DELIVERY_AUTHORITY", "kind" to "programAuthority"), mapOf("id" to "kvp.024.proof", "kind" to "taskOutput"), mapOf("id" to "KVP-REQ-019", "kind" to "requirement")),
                outputs = listOf(TaskOutput("kvp.025.proof", "PROOF_ARTIFACT", "ide-plugin/build/reports/KVP-025-retirement.json", "Every lifecycle termination retires owned artifacts exactly once.")),
                publicInterface = "RetiredIdeEndpoint", internalImplementation = "Project-scoped cleanup and recovery transitions.",
                effects = setOf(EffectId("UDS_BIND"), EffectId("ENDPOINT_DESCRIPTOR_WRITE")), costs = setOf("METADATA"),
                forbiddenWork = listOf("Global application lifetime", "Stale descriptor retention", "Deleting unrelated paths", "Non-idempotent cleanup"),
                red = ProofCommand("KVP-025-RED", "./gradlew :ide-plugin:test --tests \"*IdeEndpointRetirementNegativeTest\"", "Failure or disposal leaves reachable stale readiness or unsafe cleanup."),
                green = ProofCommand("KVP-025-GREEN", "./gradlew :ide-plugin:test --tests \"*IdeEndpointRetirementTest\"", "Every lifecycle termination retires owned artifacts exactly once."),
                reviewBoundary = "Lifecycle and cleanup only.",
                completionReceipt = CompletionReceiptContract("KVP-025-COMPLETE", setOf("KVP-025-RED", "KVP-025-GREEN"), setOf("KVP-024-COMPLETE"), "build/reports/delivery/receipts/KVP-025-COMPLETE.receipt.json"),
                provesRequirements = setOf(RequirementId("KVP-REQ-019")), authorities = setOf(AuthorityId("IDE_ENDPOINT")),
            ),
)
