package support.delivery

internal fun deliverySpecialEdges(): List<SpecialEdge> = listOf(
            SpecialEdge(EdgeKind.RETIRES, "KVP-036", "LEGACY_DEFAULT_SEMANTIC_RUNTIME", "KVP-036-COMPLETE"),
            SpecialEdge(EdgeKind.RETIRES, "KVP-025", "READY_IDE_ENDPOINT_ON_PROJECT_CLOSE", "KVP-025-COMPLETE"),
            SpecialEdge(EdgeKind.INVALIDATES, "IDE_OBSERVED_PROJECT_MOVEMENT", "IN_FLIGHT_PROJECT_READ_EPOCH", "Rejected.WorkspaceMoved"),
            SpecialEdge(EdgeKind.RECOVERS_TO, "ENDPOINT_PUBLICATION_AFTER_SOCKET_BIND_FAILURE", "RETIRED_IDE_ENDPOINT", "KVP-025"),
            SpecialEdge(EdgeKind.RECOVERS_TO, "PROJECT_OR_PLUGIN_DISPOSAL", "RETIRED_IDE_ENDPOINT", "KVP-025"),
)
internal fun deliveryProcessNodes(): List<ProcessNode> = listOf(
            ProcessNode("RAW_CLI_ARGUMENTS", "UNTRUSTED_INPUT"),
            ProcessNode("PARSED_CLI_COMMAND", "PARSED_INPUT"),
            ProcessNode("CANONICAL_WORKSPACE_ROOT", "ADMITTED_IDENTITY"),
            ProcessNode("RAW_ENDPOINT_DESCRIPTOR", "UNTRUSTED_INPUT"),
            ProcessNode("PARSED_ENDPOINT_DESCRIPTOR", "PARSED_INPUT"),
            ProcessNode("COMPATIBLE_IDE_ENDPOINT", "ADMITTED_INPUT"),
            ProcessNode("EXACT_ROOT_IDE_ENDPOINT", "CAPABILITY"),
            ProcessNode("REACHABLE_IDE_ENDPOINT", "CAPABILITY"),
            ProcessNode("WIRE_REQUEST", "PARSED_INPUT"),
            ProcessNode("PROJECT_READ_ADMISSION", "ADMISSION"),
            ProcessNode("PROJECT_READ_PERMIT", "CAPABILITY"),
            ProcessNode("READ_EPOCH_BEFORE", "EVIDENCE"),
            ProcessNode("CANCELLABLE_SMART_READ", "EFFECT"),
            ProcessNode("DETACHED_RESULT", "EVIDENCE"),
            ProcessNode("READ_EPOCH_AFTER", "EVIDENCE"),
            ProcessNode("REVALIDATED_RESULT", "VERIFIED_OUTPUT"),
            ProcessNode("OUTCOME_COMPLETE_QUALIFIED_REJECTED", "TERMINAL_OUTCOME"),
            ProcessNode("IDE_OBSERVED_PROJECT_MOVEMENT", "INVALIDATION_SIGNAL"),
            ProcessNode("RETIRED_IDE_ENDPOINT", "RECOVERY_STATE"),
)

internal fun deliveryProcessTransitions(): List<ProcessTransition> = listOf(
            ProcessTransition("RAW_CLI_ARGUMENTS", "PARSED_CLI_COMMAND", "parse", "Rejected.InvalidCommand"),
            ProcessTransition("PARSED_CLI_COMMAND", "CANONICAL_WORKSPACE_ROOT", "admitRoot", "Rejected.InvalidRoot"),
            ProcessTransition("CANONICAL_WORKSPACE_ROOT", "RAW_ENDPOINT_DESCRIPTOR", "locateDescriptor", "Rejected.EndpointMissing"),
            ProcessTransition("RAW_ENDPOINT_DESCRIPTOR", "PARSED_ENDPOINT_DESCRIPTOR", "parseDescriptor", "Rejected.EndpointMalformed"),
            ProcessTransition("PARSED_ENDPOINT_DESCRIPTOR", "COMPATIBLE_IDE_ENDPOINT", "admitCompatibility", "Rejected.EndpointIncompatible"),
            ProcessTransition("COMPATIBLE_IDE_ENDPOINT", "EXACT_ROOT_IDE_ENDPOINT", "admitExactRoot", "Rejected.RootMismatch"),
            ProcessTransition("EXACT_ROOT_IDE_ENDPOINT", "REACHABLE_IDE_ENDPOINT", "probe", "Rejected.EndpointUnreachable"),
            ProcessTransition("REACHABLE_IDE_ENDPOINT", "WIRE_REQUEST", "encode", "Rejected.RequestEncoding"),
            ProcessTransition("WIRE_REQUEST", "PROJECT_READ_ADMISSION", "dispatch", "Rejected.OperationUnavailable"),
            ProcessTransition("PROJECT_READ_ADMISSION", "PROJECT_READ_PERMIT", "singleFlight", "Rejected.BusyOrDumbOrDisposed"),
            ProcessTransition("PROJECT_READ_PERMIT", "READ_EPOCH_BEFORE", "observeEpoch", "Rejected.EpochUnavailable"),
            ProcessTransition("READ_EPOCH_BEFORE", "CANCELLABLE_SMART_READ", "execute", "Rejected.Cancelled"),
            ProcessTransition("CANCELLABLE_SMART_READ", "DETACHED_RESULT", "detach", "Rejected.ProjectionFailed"),
            ProcessTransition("DETACHED_RESULT", "READ_EPOCH_AFTER", "observeEpoch", "Rejected.EpochUnavailable"),
            ProcessTransition("READ_EPOCH_AFTER", "REVALIDATED_RESULT", "compareEpochs", "Rejected.WorkspaceMoved"),
            ProcessTransition("REVALIDATED_RESULT", "OUTCOME_COMPLETE_QUALIFIED_REJECTED", "projectOutcome", "none"),
            ProcessTransition("IDE_OBSERVED_PROJECT_MOVEMENT", "READ_EPOCH_AFTER", "advanceEpoch", "invalidatesInFlightRead"),
)

internal fun deliveryInstalledMetrics(): List<MetricRequirement> = listOf(
            MetricRequirement("endpoint.host.kind", "equals", "IDE_PROJECT"),
            MetricRequirement("endpoint.pid.matches.ide.pid", "equals", true),
            MetricRequirement("spawned.indexer.process.count", "equals", 0),
            MetricRequirement("kast.caused.indexing.cycle.count", "equals", 0),
            MetricRequirement("runtime.archive.read.count", "equals", 0),
            MetricRequirement("semantic.runtime.asset.present", "equals", false),
            MetricRequirement("private.idea.home.created", "equals", false),
            MetricRequirement("project.open.call.count", "equals", 0),
            MetricRequirement("gradle.import.call.count", "equals", 0),
            MetricRequirement("vfs.refresh.call.count", "equals", 0),
            MetricRequirement("vfs.listener.semantic.job.count", "equals", 0),
            MetricRequirement("repository.walk.inside.read.count", "equals", 0),
            MetricRequirement("source.hash.inside.read.count", "equals", 0),
            MetricRequirement("blocking.read.action.call.count", "equals", 0),
            MetricRequirement("semantic.work.on.edt.count", "equals", 0),
            MetricRequirement("max.concurrent.kast.reads", "atMost", 1),
            MetricRequirement("max.queued.kast.reads", "atMost", 1),
            MetricRequirement("selector.round.trip", "equals", true),
            MetricRequirement("wrong.symbol.selection.count", "equals", 0),
            MetricRequirement("stale.epoch.accepted.count", "equals", 0),
            MetricRequirement("endpoint.retired.on.project.close", "equals", true),
            MetricRequirement("plugin.platform.jar.count", "equals", 0),
            MetricRequirement("plugin.bootstrap.class.count", "equals", 0),
            MetricRequirement("default.download.bytes", "atMost", 83886080),
            MetricRequirement("automatic.fallback.path.count", "equals", 0),
            MetricRequirement("unsupported.endpoint.accepted.count", "equals", 0),
)
