package io.github.amichne.kast.protocol.contract

/** Bounded committed text around the exact symbol, with one-based inclusive lines. */
data class QuerySourceWindowDocument(
    val text: ProtocolSourceText,
    val lines: SourceLineRangeDocument,
)

enum class QuerySourceFailureDocument {
    WORKSPACE_NOT_READY,
    WORKSPACE_ROOT_MISMATCH,
    STALE_GENERATION,
    SOURCE_STATE_MISMATCH,
    CANDIDATE_STALE,
    SOURCE_SELECTOR_STALE,
    SOURCE_SNAPSHOT_MISMATCH,
    SOURCE_UNAVAILABLE,
    CONTINUATION_UNAVAILABLE,
    CONTINUATION_REQUEST_MISMATCH,
    DOCUMENT_DIRTY,
    PSI_DOCUMENT_UNCOMMITTED,
    OUTSIDE_SOURCE_SCOPE,
    ANCHOR_NOT_FOUND,
    AMBIGUOUS_ANCHOR,
    REGION_NOT_APPLICABLE,
    REGION_ABSENT,
    COMPILER_ANALYSIS_UNAVAILABLE,
    INTERNAL_CONTEXT_LEASE_MISMATCH,
    INTERNAL_SNAPSHOT_CONTEXT_MISMATCH,
    INTERNAL_SCOPE_MISMATCH,
    INTERNAL_SNAPSHOT_MISMATCH,
    INTERNAL_VISIBILITY_MISMATCH,
    CONTRACT_VIOLATION,
    BYTE_LIMIT_REACHED,
    PROVIDER_UNAVAILABLE,
}
