// Generated by packaging/generate-source-read-types.py from the canonical Kotlin request schema.
// Do not edit directly.

declare const exactSymbolSelectorBrand: unique symbol;
export type ExactSymbolSelector = string & { readonly [exactSymbolSelectorBrand]: true };

export type ExactSymbolSelectorAdmission =
  | { readonly type: "accepted"; readonly value: ExactSymbolSelector }
  | { readonly type: "rejected"; readonly reason: "malformed" };

export function admitExactSymbolSelector(raw: string): ExactSymbolSelectorAdmission {
  return new RegExp("^exact:(?:v4:[0-9a-f]{64}|v5:[A-Za-z0-9_-]{21}[AQgw])$").test(raw)
    ? { type: "accepted", value: raw as ExactSymbolSelector }
    : { type: "rejected", reason: "malformed" };
}

export type SourceReadRequest = ({
  "symbol": ExactSymbolSelector;
  "region"?: "declaration" | "body" | "class-body" | "file";
  "text"?: {
    "mode": "complete";
  } | {
    "mode": "none";
  } | {
    "mode": "window";
    "beforeLines"?: number;
    "afterLines"?: number;
    "maximumBytes": number;
  };
  "entities"?: {
    "mode": "declarations";
    "limit": number;
  } | {
    "mode": "none";
  };
  "format"?: "expanded" | "compact";
} & { "anchor"?: never; "entityLimit"?: never; "execution_budget"?: never; "page"?: never; "textByteLimit"?: never }) | ({
  "anchor": {
    "type": "candidate";
    "selector": string;
  } | {
    "type": "source";
    "selector": string;
  } | {
    "type": "symbol";
    "selector": string;
  };
  "region": {
    "type": "anchor";
  } | {
    "type": "body";
    "kind": "callable" | "class";
  } | {
    "type": "enclosing";
    "kind": "declaration" | "callable-body" | "class-body";
  } | {
    "type": "file";
  };
  "entities": {
    "type": "matching";
    "containment": "direct" | "descendants";
    "filters": Array<{
      "type": "calls";
    } | {
      "type": "declaration";
      "kinds": Array<"classlike" | "constructor" | "function" | "property" | "type-alias">;
      "visibility": {
        "type": "any";
      } | {
        "type": "exact";
        "values": Array<"public" | "protected" | "internal" | "private" | "local">;
      };
    } | {
      "type": "parameters";
    } | {
      "type": "references";
    }>;
  } | {
    "type": "none";
  };
  "text": {
    "type": "complete";
  } | {
    "type": "none";
  } | {
    "type": "window";
    "beforeLines": number;
    "afterLines": number;
  };
  "entityLimit"?: number;
  "textByteLimit"?: number;
  "page"?: {
    "type": "continue";
    "continuation": string;
  } | {
    "type": "first";
  };
  "execution_budget"?: {
    "max_elapsed_ms"?: number | null;
    "max_work_units"?: number | null;
    "max_results"?: number | null;
    "max_returned_bytes"?: number | null;
  } | null;
  "format"?: "expanded" | "compact";
} & { "symbol"?: never }) | ({
  "anchor": {
    "symbolRef": string;
  };
  "region"?: "declaration" | "file" | "class_body" | "callable_body";
  "text"?: {
    "mode": "complete";
    "maxBytes"?: number | null;
  } | {
    "mode": "none";
  } | {
    "mode": "window";
    "beforeLines": number;
    "afterLines": number;
    "maxBytes"?: number | null;
  };
  "entities"?: {
    "mode": "matching";
    "filters": Array<{
      "type": "calls";
    } | {
      "type": "declaration";
      "kinds": Array<"classlike" | "constructor" | "function" | "property" | "type-alias">;
      "visibility": {
        "type": "any";
      } | {
        "type": "exact";
        "values": Array<"public" | "protected" | "internal" | "private" | "local">;
      };
    } | {
      "type": "parameters";
    } | {
      "type": "references";
    }>;
    "limit"?: number | null;
    "containment"?: "direct" | "descendants";
  } | {
    "mode": "none";
  };
  "page"?: {
    "type": "continue";
    "continuation": string;
  } | {
    "type": "first";
  };
  "execution_budget"?: {
    "max_elapsed_ms"?: number | null;
    "max_work_units"?: number | null;
    "max_results"?: number | null;
    "max_returned_bytes"?: number | null;
  } | null;
} & { "entityLimit"?: never; "format"?: never; "symbol"?: never; "textByteLimit"?: never });
