package io.github.amichne.kast.query.contract

enum class QueryImpactPeerProofFailure {
    WORK_RECEIPT_EXCEEDS_GRANT,
    TIME_RECEIPT_EXCEEDS_GRANT,
    SITE_WORK_EXCEEDS_ACQUISITION_WORK,
    SITE_GRANT_EXCEEDS_ACQUISITION_GRANT,
    TARGET_BASIS_MISMATCH,
    TARGET_IDENTITY_MISMATCH,
    SOURCE_BASIS_MISMATCH,
    SAME_SOURCE_ROOT,
    CONNECTION_MISMATCH,
}
