package io.github.amichne.kast.distribution.contract.configuration

/** Removed overrides must be removed by the caller, never silently treated as effective configuration. */
enum class RetiredConfigurationSetting(val key: String) {
    INDEXER_MAX_HEAP("KAST_INDEXER_MAX_HEAP"),
    WORKER_RESIDENT_LIMIT("KAST_WORKER_RESIDENT_LIMIT"),
    WORKER_STARTUP_LIMIT("KAST_WORKER_STARTUP_LIMIT"),
    WORKER_AGGREGATE_MIB("KAST_WORKER_AGGREGATE_MIB"),
    WORKER_NATIVE_MIB("KAST_WORKER_NATIVE_MIB"),
    WORKER_GRADLE_MIB("KAST_WORKER_GRADLE_MIB"),
    RUNTIME_ARCHIVE("KAST_RUNTIME_ARCHIVE"),
    RUNTIME_STORE("KAST_RUNTIME_STORE"),
    CACHE_ROOT("KAST_CACHE_ROOT"),
    ENABLE_APP_SERVER("KAST_ENABLE_APP_SERVER"),
    APP_SERVER_TOOLS("KAST_APP_SERVER_TOOLS"),
    ENABLE_LAUNCHD("KAST_ENABLE_LAUNCHD"),
    INSTALL_REFRESH_APP_SERVER("KAST_INSTALL_REFRESH_APP_SERVER"),
    INSTALL_REPLACE_COMMAND_COLLISIONS("KAST_INSTALL_REPLACE_COMMAND_COLLISIONS"),
}
