package io.github.amichne.kast.protocol.wire

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
internal enum class RelationReadRejectionWireDocument {
    @SerialName("revalidation_wrong_kind") REVALIDATION_WRONG_KIND,
    @SerialName("revalidation_unretained") REVALIDATION_UNRETAINED,
    @SerialName("revalidation_expired") REVALIDATION_EXPIRED,
    @SerialName("revalidation_capacity") REVALIDATION_CAPACITY,
    @SerialName("revalidation_work_limit_reached") REVALIDATION_WORK_LIMIT_REACHED,
    @SerialName("revalidation_time_limit_reached") REVALIDATION_TIME_LIMIT_REACHED,
    @SerialName("revalidation_retired") REVALIDATION_RETIRED,
    @SerialName("revalidation_capture_unavailable") REVALIDATION_CAPTURE_UNAVAILABLE,
    @SerialName("revalidation_workspace_mismatch") REVALIDATION_WORKSPACE_MISMATCH,
    @SerialName("revalidation_owner_mismatch") REVALIDATION_OWNER_MISMATCH,
    @SerialName("revalidation_workspace_not_ready") REVALIDATION_WORKSPACE_NOT_READY,
    @SerialName("revalidation_basis_moved") REVALIDATION_BASIS_MOVED,
    @SerialName("revalidation_content_changed") REVALIDATION_CONTENT_CHANGED,
    @SerialName("revalidation_content_uncommitted") REVALIDATION_CONTENT_UNCOMMITTED,
    @SerialName("revalidation_scope_rejected") REVALIDATION_SCOPE_REJECTED,
    @SerialName("revalidation_declaration_missing") REVALIDATION_DECLARATION_MISSING,
    @SerialName("revalidation_unsupported_declaration") REVALIDATION_UNSUPPORTED_DECLARATION,
    @SerialName("revalidation_ambiguous") REVALIDATION_AMBIGUOUS,
    @SerialName("revalidation_compiler_identity_changed") REVALIDATION_COMPILER_IDENTITY_CHANGED,
    @SerialName("revalidation_compiler_unavailable") REVALIDATION_COMPILER_UNAVAILABLE,
    @SerialName("scope_rejected") SCOPE_REJECTED,
    @SerialName("workspace_index_unavailable") WORKSPACE_INDEX_UNAVAILABLE,
    @SerialName("outside_scope") OUTSIDE_SCOPE,
    @SerialName("ambiguous_subject") AMBIGUOUS_SUBJECT,
    @SerialName("compiler_identity_unavailable") COMPILER_IDENTITY_UNAVAILABLE,
    @SerialName("compiler_contract_violation") COMPILER_CONTRACT_VIOLATION,
    @SerialName("workspace_not_ready") WORKSPACE_NOT_READY,
    @SerialName("selector_wrong_kind") SELECTOR_WRONG_KIND,
    @SerialName("selector_malformed") SELECTOR_MALFORMED,
    @SerialName("selector_workspace_mismatch") SELECTOR_WORKSPACE_MISMATCH,
    @SerialName("selector_stale") SELECTOR_STALE,
    @SerialName("relation_unsupported") RELATION_UNSUPPORTED,
    @SerialName("continuation_malformed") CONTINUATION_MALFORMED,
    @SerialName("continuation_unavailable") CONTINUATION_UNAVAILABLE,
    @SerialName("continuation_request_mismatch") CONTINUATION_REQUEST_MISMATCH,
    @SerialName("continuation_subject_mismatch") CONTINUATION_SUBJECT_MISMATCH,
    @SerialName("continuation_relation_mismatch") CONTINUATION_RELATION_MISMATCH,
    @SerialName("continuation_scope_mismatch") CONTINUATION_SCOPE_MISMATCH,
    @SerialName("continuation_generation_mismatch") CONTINUATION_GENERATION_MISMATCH,
    @SerialName("continuation_cursor_moved") CONTINUATION_CURSOR_MOVED,
}

@Serializable
internal enum class TraversalRunRejectionWireDocument {
    @SerialName("revalidation_wrong_kind") REVALIDATION_WRONG_KIND,
    @SerialName("revalidation_unretained") REVALIDATION_UNRETAINED,
    @SerialName("revalidation_expired") REVALIDATION_EXPIRED,
    @SerialName("revalidation_capacity") REVALIDATION_CAPACITY,
    @SerialName("revalidation_work_limit_reached") REVALIDATION_WORK_LIMIT_REACHED,
    @SerialName("revalidation_time_limit_reached") REVALIDATION_TIME_LIMIT_REACHED,
    @SerialName("revalidation_retired") REVALIDATION_RETIRED,
    @SerialName("revalidation_capture_unavailable") REVALIDATION_CAPTURE_UNAVAILABLE,
    @SerialName("revalidation_workspace_mismatch") REVALIDATION_WORKSPACE_MISMATCH,
    @SerialName("revalidation_owner_mismatch") REVALIDATION_OWNER_MISMATCH,
    @SerialName("revalidation_workspace_not_ready") REVALIDATION_WORKSPACE_NOT_READY,
    @SerialName("revalidation_basis_moved") REVALIDATION_BASIS_MOVED,
    @SerialName("revalidation_content_changed") REVALIDATION_CONTENT_CHANGED,
    @SerialName("revalidation_content_uncommitted") REVALIDATION_CONTENT_UNCOMMITTED,
    @SerialName("revalidation_scope_rejected") REVALIDATION_SCOPE_REJECTED,
    @SerialName("revalidation_declaration_missing") REVALIDATION_DECLARATION_MISSING,
    @SerialName("revalidation_unsupported_declaration") REVALIDATION_UNSUPPORTED_DECLARATION,
    @SerialName("revalidation_ambiguous") REVALIDATION_AMBIGUOUS,
    @SerialName("revalidation_compiler_identity_changed") REVALIDATION_COMPILER_IDENTITY_CHANGED,
    @SerialName("revalidation_compiler_unavailable") REVALIDATION_COMPILER_UNAVAILABLE,
    @SerialName("scope_rejected") SCOPE_REJECTED,
    @SerialName("workspace_index_unavailable") WORKSPACE_INDEX_UNAVAILABLE,
    @SerialName("outside_scope") OUTSIDE_SCOPE,
    @SerialName("ambiguous_subject") AMBIGUOUS_SUBJECT,
    @SerialName("compiler_identity_unavailable") COMPILER_IDENTITY_UNAVAILABLE,
    @SerialName("compiler_contract_violation") COMPILER_CONTRACT_VIOLATION,
    @SerialName("continuation_cursor_moved") CONTINUATION_CURSOR_MOVED,
    @SerialName("relation_unsupported") RELATION_UNSUPPORTED,
    @SerialName("reader_contract_violation") READER_CONTRACT_VIOLATION,
    @SerialName("traversal_contract_violation") TRAVERSAL_CONTRACT_VIOLATION,
    @SerialName("depth_limit_exceeded") DEPTH_LIMIT_EXCEEDED,
    @SerialName("continuation_unavailable") CONTINUATION_UNAVAILABLE,
    @SerialName("continuation_request_mismatch") CONTINUATION_REQUEST_MISMATCH,
    @SerialName("workspace_not_ready") WORKSPACE_NOT_READY,
    @SerialName("selector_wrong_kind") SELECTOR_WRONG_KIND,
    @SerialName("selector_malformed") SELECTOR_MALFORMED,
    @SerialName("selector_workspace_mismatch") SELECTOR_WORKSPACE_MISMATCH,
    @SerialName("selector_stale") SELECTOR_STALE,
    @SerialName("topology_build_required") TOPOLOGY_BUILD_REQUIRED,
    @SerialName("plan_rejected") PLAN_REJECTED,
    @SerialName("continuation_malformed") CONTINUATION_MALFORMED,
    @SerialName("continuation_subject_mismatch") CONTINUATION_SUBJECT_MISMATCH,
    @SerialName("continuation_relation_mismatch") CONTINUATION_RELATION_MISMATCH,
    @SerialName("continuation_scope_mismatch") CONTINUATION_SCOPE_MISMATCH,
    @SerialName("continuation_generation_mismatch") CONTINUATION_GENERATION_MISMATCH,
}
