mod support;

use support::*;

include!("agent_workspace_files_smoke/fixtures/core.rs");
include!("agent_workspace_files_smoke/fixtures/paged_backend.rs");
include!("agent_workspace_files_smoke/fixtures/mixed_backend.rs");
include!("agent_workspace_files_smoke/fixtures/filters.rs");
include!("agent_workspace_files_smoke/pagination/result.rs");
include!("agent_workspace_files_smoke/pagination/pages.rs");
include!("agent_workspace_files_smoke/pagination/malformed.rs");
include!("agent_workspace_files_smoke/pagination/budget.rs");
include!("agent_workspace_files_smoke/pagination/grouping.rs");
include!("agent_workspace_files_smoke/pagination/query_mismatch.rs");
include!("agent_workspace_files_smoke/pagination/consumed_stale.rs");
include!("agent_workspace_files_smoke/pagination/cross_lane.rs");
include!("agent_workspace_files_smoke/pagination/stable_partial.rs");
include!("agent_workspace_files_smoke/evidence/index_complete.rs");
include!("agent_workspace_files_smoke/evidence/index_incomplete.rs");
include!("agent_workspace_files_smoke/evidence/gradle_partial.rs");
include!("agent_workspace_files_smoke/evidence/backend_partial.rs");
include!("agent_workspace_files_smoke/evidence/owner_exact.rs");
include!("agent_workspace_files_smoke/evidence/filters.rs");
include!("agent_workspace_files_smoke/composition/diagnostics.rs");
include!("agent_workspace_files_smoke/composition/mixed_count.rs");
include!("agent_workspace_files_smoke/composition/views.rs");
include!("agent_workspace_files_smoke/contract/public.rs");
include!("agent_workspace_files_smoke/contract/documented.rs");
include!("agent_workspace_files_smoke/contract/root.rs");
include!("agent_workspace_files_smoke/contract/modules.rs");
include!("agent_workspace_files_smoke/contract/packages.rs");
include!("agent_workspace_files_smoke/contract/unicode_packages.rs");
include!("agent_workspace_files_smoke/contract/paths.rs");
include!("agent_workspace_files_smoke/contract/globs.rs");
include!("agent_workspace_files_smoke/contract/limit.rs");
include!("agent_workspace_files_smoke/contract/pages.rs");
include!("agent_workspace_files_smoke/types/views.rs");
include!("agent_workspace_files_smoke/types/source_set.rs");
include!("agent_workspace_files_smoke/types/kind.rs");
include!("agent_workspace_files_smoke/types/unavailable.rs");
