mod support;

use rusqlite::params;
use sha2::{Digest, Sha256};
use support::workspace_files::WorkspaceIndexFixture;
use support::*;

include!("repository_intelligence_smoke/fixtures/core.rs");
include!("repository_intelligence_smoke/fixtures/graph.rs");
include!("repository_intelligence_smoke/discovery/paraphrases.rs");
include!("repository_intelligence_smoke/discovery/ownership.rs");
include!("repository_intelligence_smoke/discovery/regex.rs");
include!("repository_intelligence_smoke/discovery/labels.rs");
include!("repository_intelligence_smoke/discovery/label_security.rs");
include!("repository_intelligence_smoke/architecture/limits.rs");
include!("repository_intelligence_smoke/traversal/scope.rs");
include!("repository_intelligence_smoke/traversal/cardinality.rs");
include!("repository_intelligence_smoke/agent_views/outgoing.rs");
include!("repository_intelligence_smoke/agent_views/path.rs");
include!("repository_intelligence_smoke/agent_views/architecture.rs");
include!("repository_intelligence_smoke/agent_views/remaining.rs");
include!("repository_intelligence_smoke/agent_views/contract.rs");
include!("repository_intelligence_smoke/coverage/rpc.rs");
include!("repository_intelligence_smoke/coverage/continuation.rs");
include!("repository_intelligence_smoke/coverage/readiness.rs");
include!("repository_intelligence_smoke/authority/root.rs");
include!("repository_intelligence_smoke/authority/scope.rs");
include!("repository_intelligence_smoke/validation/intent_fields.rs");
include!("repository_intelligence_smoke/coverage/negative.rs");
include!("repository_intelligence_smoke/validation/path_ambiguity.rs");
include!("repository_intelligence_smoke/context/ambiguity.rs");
include!("repository_intelligence_smoke/context/terminal.rs");
include!("repository_intelligence_smoke/context/empty.rs");
include!("repository_intelligence_smoke/relationships/expect_actual_rpc.rs");
include!("repository_intelligence_smoke/relationships/expect_actual_agent.rs");
include!("repository_intelligence_smoke/traversal/exact_path.rs");
include!("repository_intelligence_smoke/discovery/resolution_views.rs");
include!("repository_intelligence_smoke/context/output_views.rs");
include!("repository_intelligence_smoke/traversal/path_invalidation.rs");
include!("repository_intelligence_smoke/traversal/path_contract.rs");
