#!/usr/bin/env python3
"""Project the published source_read request schema into a TypeScript client type."""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "docs/public/reference/callables.openapi.json"
OUTPUT = ROOT / "clients/typescript/source-read.ts"


def render(schema: dict, depth: int = 0, symbol: bool = False) -> str:
    if "anyOf" in schema:
        return " | ".join(render(option, depth, symbol) for option in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(render(option, depth, symbol) for option in schema["oneOf"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "object":
        if schema.get("additionalProperties") is not False:
            raise ValueError("source_read object must be closed")
        required = set(schema.get("required", []))
        fields = []
        for name, child in schema.get("properties", {}).items():
            field = json.dumps(name) + ("" if name in required else "?")
            fields.append("  " * (depth + 1) + field + ": " + render(child, depth + 1, symbol=name == "symbol") + ";")
        return "{\n" + "\n".join(fields) + "\n" + "  " * depth + "}"
    if kind == "array":
        return "Array<" + render(schema["items"], depth) + ">"
    if kind == "string":
        return "ExactSymbolSelector" if symbol else "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    raise ValueError(f"unhandled source_read schema node: {schema}")


def generated() -> str:
    document = json.loads(SCHEMA.read_text())
    schema = document["components"]["schemas"]["source_readRequest"]
    branches = schema.get("anyOf", schema.get("oneOf", []))
    short = [
        variant
        for branch in branches
        for variant in branch.get("oneOf", [branch])
        if "symbol" in variant.get("properties", {})
    ]
    if len(short) != 1 or short[0].get("required") != ["symbol"]:
        raise ValueError("expected one exact-symbol source_read branch")
    exact = short[0]["properties"]["symbol"]
    pattern = exact["pattern"]
    return (
        "// Generated by packaging/generate-source-read-types.py from the canonical Kotlin request schema.\n"
        "// Do not edit directly.\n\n"
        "declare const exactSymbolSelectorBrand: unique symbol;\n"
        "export type ExactSymbolSelector = string & { readonly [exactSymbolSelectorBrand]: true };\n\n"
        "export type ExactSymbolSelectorAdmission =\n"
        "  | { readonly type: \"accepted\"; readonly value: ExactSymbolSelector }\n"
        "  | { readonly type: \"rejected\"; readonly reason: \"malformed\" };\n\n"
        "export function admitExactSymbolSelector(raw: string): ExactSymbolSelectorAdmission {\n"
        f"  return new RegExp({json.dumps(pattern)}).test(raw)\n"
        "    ? { type: \"accepted\", value: raw as ExactSymbolSelector }\n"
        "    : { type: \"rejected\", reason: \"malformed\" };\n"
        "}\n\n"
        "export type SourceReadRequest = " + render(schema) + ";\n"
    )


def main() -> int:
    value = generated()
    if len(sys.argv) == 2 and sys.argv[1] == "--check":
        return 0 if OUTPUT.exists() and OUTPUT.read_text() == value else 1
    if len(sys.argv) != 1:
        raise SystemExit("usage: generate-source-read-types.py [--check]")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(value)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
