#!/usr/bin/env python3
"""Check the public documentation structure, claims, and generated assets."""

from __future__ import annotations

import json
import re
import subprocess
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "docs/public"
LIKEC4_TOOLING = ROOT / "docs/tooling/likec4"

PAGES = {
    "index.md": [
        "The compiler sees more than text",
        "Start from the repository root",
        "What is Kast ready to inspect?",
        "What declaration is this?",
        "How is this code connected?",
        "Is this code semantically valid?",
        "How can I change it safely?",
        "Evidence keeps its boundary",
    ],
    "start.md": [
        "# Set up and start Kast",
        "Java 21",
        "IntelliJ IDEA 2026.2",
        "Android Studio 2026.1.2",
        "https://raw.githubusercontent.com/amichne/kast/main/install.sh",
        "rejects unsafe archive paths",
        "kast --schema",
        "kast start",
        "kast status",
    ],
    "questions/workspace-readiness.md": [
        "# What is Kast ready to inspect?",
        "kast workspace inspect",
        "exact root",
    ],
    "questions/declaration-identity.md": [
        "# What declaration is this?",
        "kast symbol discover",
        "kast symbol resolve",
        "kast symbol describe",
    ],
    "questions/code-connections.md": [
        "# How is this code connected?",
        "kast relation read",
        "kast topology build",
        "kast traversal run",
        "explicit limits",
    ],
    "questions/semantic-validity.md": [
        "# Is this code semantically valid?",
        "kast diagnostic check",
        "explicit scope",
    ],
    "questions/safe-change.md": [
        "# How can I change it safely?",
        "kast change plan",
        "kast change apply",
        "kast change verify",
        "kast change recover",
    ],
    "concepts/evidence-boundaries.md": [
        "# Trust the evidence",
        "Complete",
        "Qualified",
        "Rejected",
        "generation",
    ],
    "reference/cli.md": [
        "Generated by docs/generate_cli_reference.py",
        "# CLI reference",
        "workspace.inspect",
        "change.recover",
    ],
    "explanation/how-kast-works.md": [
        "# How Kast works",
        '<script type="module" src="../../architecture/likec4-views.mjs">',
        '<script src="../../javascripts/diagram.js">',
        '<kast-view view-id="runtime-flow"',
        '<kast-view view-id="module-ownership"',
        '<details class="kast-architecture-details"',
        "foreground IDE",
        "twelve canonical operations",
    ],
}

EXPECTED_TOP_NAV = [
    "Start",
    "Repository questions",
    "Trust the evidence",
    "CLI reference",
    "How Kast works",
]

FORBIDDEN_PROSE = [
    "why should you care",
    "revolutionary",
    "game-changing",
    "seamless",
    "unlock the power",
    "—",
]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def nav_paths(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [path for item in value for path in nav_paths(item)]
    if isinstance(value, dict):
        return [path for item in value.values() for path in nav_paths(item)]
    raise AssertionError(f"unsupported navigation value: {value!r}")


def check_config() -> None:
    require((ROOT / "docs/build_public_site.py").is_file(), "public site builder is missing")
    config = tomllib.loads((ROOT / "zensical.toml").read_text())["project"]
    require(config["docs_dir"] == "docs/public", "Zensical docs_dir changed")
    require(config["site_dir"] == "site", "Zensical site_dir changed")
    require(
        config["extra_javascript"] == ["javascripts/accessibility.js"],
        "unexpected global JavaScript surface",
    )
    require(config["plugins"]["search"]["enabled"] is False, "minimal site search is enabled")
    nav = config["nav"]
    top_labels = [next(iter(item)) for item in nav]
    require(top_labels == EXPECTED_TOP_NAV, f"unexpected top navigation: {top_labels}")
    destinations = nav_paths(nav)
    require(destinations == list(PAGES), f"navigation and page contract differ: {destinations}")


def check_pages() -> None:
    reader_pages = {
        page.relative_to(PUBLIC).as_posix()
        for page in PUBLIC.rglob("*.md")
        if page.name != "AGENTS.md"
    }
    require(reader_pages == set(PAGES), f"unexpected public Markdown surface: {sorted(reader_pages)}")

    for relative, phrases in PAGES.items():
        page = PUBLIC / relative
        require(page.is_file(), f"missing page: {relative}")
        text = page.read_text()
        for phrase in phrases:
            require(phrase in text, f"{relative} is missing {phrase!r}")
        lowered = text.lower()
        for phrase in FORBIDDEN_PROSE:
            require(phrase not in lowered, f"{relative} contains forbidden prose {phrase!r}")

    index = (PUBLIC / "index.md").read_text()
    require(
        index.startswith("---\nhide:\n  - toc\n---\n"),
        "homepage does not suppress its duplicate table of contents",
    )
    order = [index.index(phrase) for phrase in PAGES["index.md"]]
    require(order == sorted(order), "homepage reader journey is out of order")

    explanation = (PUBLIC / "explanation/how-kast-works.md").read_text()
    require('browser="true"' not in explanation, "architecture view opens a browser dialog")


def check_flat_declarations(css: str) -> None:
    for property_name in ("box-shadow", "filter"):
        declarations = re.findall(rf"{property_name}\s*:\s*([^;]+);", css)
        for declaration in declarations:
            require(
                re.fullmatch(r"none(?:\s*!important)?", declaration.strip()) is not None,
                f"{property_name} adds elevation: {declaration.strip()}",
            )

    require("drop-shadow" not in css, "authored stylesheet contains a drop shadow")


def check_styles() -> None:
    css = (PUBLIC / "stylesheets/extra.css").read_text()
    for selector in [
        ".kast-hero",
        ".kast-question-grid",
        ".kast-boundary",
        ".kast-notice",
        ".kast-architecture-details",
        ".highlight",
        "kast-view",
        ":focus-visible",
        "prefers-reduced-motion",
    ]:
        require(selector in css, f"site styling is missing {selector}")
    check_flat_declarations(css)

    javascript = (PUBLIC / "javascripts/accessibility.js").read_text()
    for behavior in ["improveLandmarks", ".md-code__nav", ".md-overlay", "document$.subscribe"]:
        require(behavior in javascript, f"site accessibility adapter is missing {behavior}")

    diagram = (PUBLIC / "javascripts/diagram.js").read_text()
    for behavior in [
        "FLAT_DIAGRAM_CSS",
        ".likec4-element-shape",
        ".likec4-edge-label__contents",
        ".likec4-edge-label {",
        ".likec4-edge-label__technology",
        ".likec4-navigation-panel__root",
        "styleShadowRoot",
        "document$.subscribe",
    ]:
        require(behavior in diagram, f"diagram surface adapter is missing {behavior}")


def check_architecture() -> None:
    architecture = PUBLIC / "architecture"
    views = (architecture / "views.c4").read_text()
    require("dynamic view runtime-flow" in views, "runtime-flow view is missing")
    require("view module-ownership" in views, "module-ownership view is missing")
    require("navigateTo" not in views, "architecture source still defines dialog navigation")

    subprocess.run(
        ["python3", "docs/tooling/likec4/generate_bundle.py", "--check"],
        cwd=ROOT,
        check=True,
    )
    likec4 = LIKEC4_TOOLING / "node_modules/.bin/likec4"
    require(likec4.is_file(), "locked LikeC4 executable is missing")

    validation = subprocess.run(
        [
            str(likec4),
            "validate",
            "--json",
            "--no-layout",
            "--file",
            "docs/public/architecture/specification.c4",
            "--file",
            "docs/public/architecture/model.c4",
            "--file",
            "docs/public/architecture/views.c4",
            "docs/public/architecture",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    report = json.loads(validation.stdout)
    require(report["valid"], f"LikeC4 validation failed: {report['errors']}")
    require(report["stats"]["totalFiles"] == 3, "LikeC4 source set changed")
    require(report["stats"]["totalErrors"] == 0, "LikeC4 diagnostics are not empty")
    print("public-docs: LikeC4 sources are valid with zero diagnostics")

    print("public-docs: architecture semantics and generated wrapper contract are current")


def main() -> None:
    check_config()
    check_pages()
    check_styles()
    check_architecture()
    print("public-docs: content contract passed")


if __name__ == "__main__":
    main()
