package io.github.amichne.kast.workspace.intellij.read

import io.github.amichne.kast.kernel.ReadLimitParameter
import io.github.amichne.kast.kernel.ReadLimits

/** Bounded vocabulary at the native effect boundary. No names, paths, references, or PSI. */
enum class IntellijReadCounter {
    /** Detached native discovery/relation page returns, including qualified pages; never public call counts. */
    NATIVE_DISCOVERY_PAGES,
    NATIVE_RELATION_PAGES,
    DISCOVERY_PARTITIONS_OBSERVED,
    DISCOVERY_PARTITIONS_ACCEPTED,
    IMPORTED_PROJECTS,
    IDEA_MODULES,
    SELECTED_GRADLE_MODULES,
    FOREIGN_GRADLE_MODULES,
    SOURCE_ROOTS,
    SOURCE_ROOTS_ABSENT,
    EPOCH_READ_PREEMPTIONS,
    EPOCH_MOVED_RETRIES,
    NAMES_VISITED,
    NAMES_MATCHED,
    LEXICAL_CANDIDATES_RETAINED,
    LEXICAL_CANDIDATES_REPLACED,
    LEXICAL_CANDIDATES_DROPPED,
    CANDIDATES_COLLECTED,
    SCOPE_FILTERED,
    CANDIDATES_PROJECTED,
    COMPILER_REFINEMENTS,
    COMPILER_REFINEMENTS_REJECTED,
    COMPILER_NATIVE_CALLABLE_IDENTITIES,
    COMPILER_ENUM_ENTRY_MEMBER_IDENTITIES,
    COMPILER_CALLABLE_IDENTITIES_UNAVAILABLE,
    RELATION_K2_CONFIRMED_TARGETS,
    RELATION_K2_DIFFERENT_TARGETS,
    RELATION_K2_UNAVAILABLE_TARGETS,
    RELATION_REFERENCE_SHAPES_ADMITTED,
    RELATION_REFERENCE_SHAPES_SKIPPED,
    RELATION_CALL_OWNERS_FOUND,
    RELATION_CALL_OWNERS_UNAVAILABLE,
    RELATION_CALL_OWNERS_EXCLUDED,
    RELATION_CANDIDATES,
    RELATION_PARTITIONS_PREPARED,
    RELATION_LOCATORS_RESTORED,
    RELATION_REPLAYED_PREFIX,
    SOURCE_STRUCTURAL_TASKS,
    SOURCE_ENTITIES_PROJECTED,
    RELATION_FACTS,
    VALUE_PRODUCER_SEED_READS,
    VALUE_PRODUCER_SEEDS_CONFIRMED,
    VALUE_PRODUCER_SEED_REJECTIONS,
    VALUE_MODEL_REVALIDATIONS,
    VALUE_MODEL_REVALIDATIONS_REJECTED,
    VALUE_MODEL_SITE_REVALIDATIONS,
    VALUE_MODEL_SITE_REVALIDATIONS_REJECTED,
    PEER_SITE_READS_STARTED,
    PEER_SITE_READS_COMPLETED,
    PEER_SITE_READS_REJECTED,
    /** PSI restoration only; these outcomes do not establish K2 role or callable identity. */
    VALUE_SITE_RESTORATIONS,
    VALUE_SITE_SHAPES_RESTORED,
    VALUE_SITE_ANCHORS_UNAVAILABLE,
    VALUE_SITE_SHAPES_REJECTED,
    VALUE_FLOW_WRAPPER_RETURNS,
    VALUE_FLOW_READS,
    VALUE_FLOW_TRANSFERS,
    VALUE_FLOW_OBLIGATIONS,
    VALUE_FLOW_REJECTIONS,
    RELATION_ITEMS_OMITTED,
    REVALIDATION_FILES_HASHED,
    REVALIDATION_BYTES_HASHED,
    REVALIDATION_WORK_CHARGED,
    REVALIDATION_CAPTURE_REJECTED,
    REVALIDATION_LOCATORS_RETAINED,
    REVALIDATION_LOCATORS_REJECTED,
    REVALIDATION_LOOKUPS,
    REVALIDATION_LOOKUPS_REJECTED,
    REFERENCE_HANDLES_ISSUED,
    REFERENCE_HANDLES_RESTORED,
    REFERENCE_HANDLES_REJECTED,
    REFERENCE_INLINE_CAPACITY,
    REFERENCE_INLINE_COLLISION,
    QUERY_RETENTION_PRESENTED_CAPTURE_STARTED,
    QUERY_RETENTION_PENDING_IMPACT_CAPTURE_STARTED,
    QUERY_RETENTION_ORIGINAL_CAPTURE_STARTED,
    QUERY_RETENTION_PRESENTED_CAPTURED,
    QUERY_RETENTION_PENDING_IMPACT_CAPTURED,
    QUERY_RETENTION_ORIGINAL_CAPTURED,
    QUERY_RETENTION_CAPTURE_EXECUTION_REJECTED,
    QUERY_RETENTION_CAPTURE_PRESENTATION_ONLY_ROWS,
    QUERY_RETENTION_CAPTURE_BASIS_MISMATCH,
    QUERY_RETENTION_CAPTURE_INCONSISTENT_COVERAGE,
    QUERY_RETENTION_CAPTURE_UNKNOWN_ROW,
    QUERY_RETENTION_CAPTURE_DUPLICATE_ROW,
    QUERY_RETENTION_RESULT_ISSUED,
    QUERY_RETENTION_RESULT_UNAVAILABLE,
    QUERY_RETENTION_RESULT_CAPACITY_EXCEEDED,
}

enum class IntellijReadContributor {
    NONE,
    EXACT_INDEX,
    SCOPED_DECLARATIONS,
    KOTLIN_CLASS,
    KOTLIN_CLASS_SYMBOL,
    KOTLIN_FUNCTION_SYMBOL,
    KOTLIN_PROPERTY_SYMBOL,
    KOTLIN_TYPE_ALIAS,
    OTHER,
}

enum class IntellijReadTermination {
    COMPLETE,
    NAME_CAP,
    CANDIDATE_CAP,
    WORK_LIMIT,
    TIME_LIMIT,
    RESULT_LIMIT,
    BYTE_LIMIT,
    RETENTION_LIMIT,
    RESPONSE_BYTE_LIMIT,
    UNSCOPED_PROVIDER,
    PROVIDER_FAILURE,
    DISCOVERY_PARTITION_NOT_FOUND,
    DISCOVERY_PARTITION_INVALID,
    DISCOVERY_PARTITION_NON_CANONICAL,
    DISCOVERY_PARTITION_KIND_MISMATCH,
    DISCOVERY_PARTITION_CAPACITY,
    DISCOVERY_SOURCE_UNAVAILABLE,
    UNSUPPORTED_ITEM,
    EXACT_REFINEMENT_UNAVAILABLE,
    INDEXING,
    DISPOSED,
    MODULE_ADMISSION_LIMIT,
    SOURCE_ROOT_ADMISSION_LIMIT,
    K2_UNRESOLVED_SYMBOL,
    K2_CALLABLE_CONTAINER_UNSUPPORTED,
    K2_ENUM_OWNER_UNAVAILABLE,
    K2_ENUM_INITIALIZER_MISMATCH,
    K2_ENUM_IDENTITY_UNAVAILABLE,
    K2_UNNAMED_CALLABLE,
    K2_SYMBOL_WITHOUT_PSI,
    K2_SOURCE_CALLABLE_CONFIRMED,
    K2_PARAMETER_INVOCATION_CONFIRMED,
    K2_SOURCELESS_CALLABLE_CONFIRMED,
    K2_INVOKE_RECEIVER_CONFIRMED,
    K2_CALLABLE_IDENTITY_UNAVAILABLE,
    K2_CALLABLE_MODULE_UNSUPPORTED,
    K2_CALLABLE_ORIGIN_UNSUPPORTED,
    K2_CALLABLE_MODULE_IDENTITY_UNAVAILABLE,
    K2_PARAMETER_OWNER_UNAVAILABLE,
    K2_PARAMETER_POSITION_UNAVAILABLE,
    K2_NON_KOTLIN_PSI,
    CALLEE_OUTSIDE_NATIVE_SCOPE,
    TARGET_OUTSIDE_PACKAGE,
    NON_KOTLIN_REFERENCE,
    LIBRARY_POLICY_EXCLUSION,
    RELATION_CALL_OWNER_UNSUPPORTED,
    RELATION_UNRESOLVED_TARGET,
    RELATION_UNSUPPORTED_ITEM,
    RELATION_PROVIDER_INCOMPLETE,
    RELATION_PROVIDER_STALLED,
    QUERY_PUBLICATION_OWNER_RETIRED,
    QUERY_PUBLICATION_CLAIM_UNAVAILABLE,
    QUERY_PUBLICATION_EXPIRED,
    QUERY_PUBLICATION_DEPENDENCY_UNAVAILABLE,
    QUERY_PUBLICATION_PAGE_MISMATCH,
    QUERY_PUBLICATION_NON_ADVANCING,
}

enum class IntellijReadStage {
    HOSTED,
    MODEL_CAPTURE,
    DISCOVERY,
    EXACT_REFINEMENT,
    RELATION,
    VALUE_FLOW,
    VALUE_PRODUCER_SEED,
    VALUE_MODEL_ADMISSION,
    VALUE_MODEL_SITE_ADMISSION,
    SOURCE,
    TRANSPORT,
}

/** Bounded effect phases; a phase proves entry, separately from successful drainage. */
enum class IntellijReadPhase {
    DISCOVERY_INVENTORY,
    DECLARATION_SCAN,
    EXACT_REFINEMENT,
    REFERENCE_INVENTORY,
    REFERENCE_PARTITION,
    REFERENCE_CONFIRMATION,
    DEFINITION_INVENTORY,
    DEFINITION_CONFIRMATION,
    CALLEE_INVENTORY,
    CALLEE_CONFIRMATION,
    TRAVERSAL,
    VALUE_SITE_RESTORATION,
    PEER_SITE_ADMISSION,
    SOURCE_ENUMERATION,
    DIAGNOSTIC_SCOPE,
    DIAGNOSTIC_ENUMERATION,
    DIAGNOSTIC_ANALYSIS,
    FRESHNESS_VALIDATION,
    RETENTION,
    ENCODING,
    CANCELLATION_DRAINAGE,
}

enum class IntellijReadUnexpectedKind {
    RUNTIME,
    LINKAGE,
}

data class IntellijReadUnexpectedFailure
private constructor(
    val stage: IntellijReadStage,
    val kind: IntellijReadUnexpectedKind,
    val exceptionType: String,
    val adapterFrames: List<String>,
) {
    companion object {
        fun capture(
            stage: IntellijReadStage,
            failure: Throwable,
            limits: ReadLimits = ReadLimits.Default,
        ): IntellijReadUnexpectedFailure =
            IntellijReadUnexpectedFailure(
                stage,
                if (failure is LinkageError) IntellijReadUnexpectedKind.LINKAGE else IntellijReadUnexpectedKind.RUNTIME,
                failure.javaClass.name.take(limits[ReadLimitParameter.DIAGNOSTIC_TEXT_CHARACTERS].value),
                failure.stackTrace
                    .asSequence()
                    .filter { it.className.startsWith("io.github.amichne.kast.") }
                    .take(limits[ReadLimitParameter.DIAGNOSTIC_FRAMES].value)
                    .map {
                        "${it.className}.${it.methodName}:${it.lineNumber}"
                            .take(limits[ReadLimitParameter.DIAGNOSTIC_TEXT_CHARACTERS].value)
                    }
                    .toList(),
            )
    }
}

/** Request-local diagnostic capability; owners choose whether to observe. */
interface IntellijReadObservation {
    fun phase(value: IntellijReadPhase) {}

    fun unexpected(failure: IntellijReadUnexpectedFailure) {}

    fun measure(gauge: IntellijReadGauge, value: IntellijReadGaugeValue) {}

    fun count(
        counter: IntellijReadCounter,
        contributor: IntellijReadContributor = IntellijReadContributor.NONE,
        amount: Int = 1,
    )

    fun terminated(reason: IntellijReadTermination, contributor: IntellijReadContributor = IntellijReadContributor.NONE)

    data object None : IntellijReadObservation {
        override fun count(counter: IntellijReadCounter, contributor: IntellijReadContributor, amount: Int) = Unit

        override fun terminated(reason: IntellijReadTermination, contributor: IntellijReadContributor) = Unit
    }
}
