package io.github.amichne.kast.workspace.intellij.read

enum class IntellijReadContributor {
    NONE,
    RELATION_REFERENCES,
    RELATION_CALLERS,
    RELATION_CALLEES,
    RELATION_IMPLEMENTATIONS,
    RELATION_INHERITORS,
    RELATION_OVERRIDES,
    RELATION_TYPE_USES,
    EXACT_INDEX,
    SCOPED_DECLARATIONS,
    KOTLIN_CLASS,
    KOTLIN_CLASS_SYMBOL,
    KOTLIN_FUNCTION_SYMBOL,
    KOTLIN_PROPERTY_SYMBOL,
    KOTLIN_TYPE_ALIAS,
    OTHER,
}

enum class IntellijReadTermination {
    COMPLETE,
    NAME_CAP,
    CANDIDATE_CAP,
    WORK_LIMIT,
    TIME_LIMIT,
    RESULT_LIMIT,
    BYTE_LIMIT,
    RETENTION_LIMIT,
    RESPONSE_BYTE_LIMIT,
    UNSCOPED_PROVIDER,
    PROVIDER_FAILURE,
    DISCOVERY_PARTITION_NOT_FOUND,
    DISCOVERY_PARTITION_INVALID,
    DISCOVERY_PARTITION_NON_CANONICAL,
    DISCOVERY_PARTITION_KIND_MISMATCH,
    DISCOVERY_PARTITION_CAPACITY,
    DISCOVERY_SOURCE_UNAVAILABLE,
    UNSUPPORTED_ITEM,
    EXACT_REFINEMENT_UNAVAILABLE,
    INDEXING,
    DISPOSED,
    MODULE_ADMISSION_LIMIT,
    SOURCE_ROOT_ADMISSION_LIMIT,
    K2_UNRESOLVED_SYMBOL,
    K2_CALLABLE_CONTAINER_UNSUPPORTED,
    K2_ENUM_OWNER_UNAVAILABLE,
    K2_ENUM_INITIALIZER_MISMATCH,
    K2_ENUM_IDENTITY_UNAVAILABLE,
    K2_UNNAMED_CALLABLE,
    K2_SYMBOL_WITHOUT_PSI,
    K2_SOURCE_CALLABLE_CONFIRMED,
    K2_PARAMETER_INVOCATION_CONFIRMED,
    K2_SOURCELESS_CALLABLE_CONFIRMED,
    K2_INVOKE_RECEIVER_CONFIRMED,
    K2_INVOKE_CALL_CONFIRMED,
    K2_INVOKE_CALL_UNRESOLVED,
    K2_CALLABLE_IDENTITY_UNAVAILABLE,
    K2_CALLABLE_MODULE_UNSUPPORTED,
    K2_CALLABLE_ORIGIN_UNSUPPORTED,
    K2_CALLABLE_MODULE_IDENTITY_UNAVAILABLE,
    K2_PARAMETER_OWNER_UNAVAILABLE,
    K2_PARAMETER_POSITION_UNAVAILABLE,
    K2_NON_KOTLIN_PSI,
    CALLEE_OUTSIDE_NATIVE_SCOPE,
    TARGET_OUTSIDE_PACKAGE,
    NON_KOTLIN_REFERENCE,
    LIBRARY_POLICY_EXCLUSION,
    RELATION_CALL_OWNER_UNSUPPORTED,
    RELATION_UNRESOLVED_TARGET,
    RELATION_UNSUPPORTED_ITEM,
    RELATION_PROVIDER_INCOMPLETE,
    RELATION_PROVIDER_STALLED,
    QUERY_PUBLICATION_OWNER_RETIRED,
    QUERY_PUBLICATION_CLAIM_UNAVAILABLE,
    QUERY_PUBLICATION_EXPIRED,
    QUERY_PUBLICATION_DEPENDENCY_UNAVAILABLE,
    QUERY_PUBLICATION_PAGE_MISMATCH,
    QUERY_PUBLICATION_NON_ADVANCING,
    CALLBACK_SUPPLIER_STORED_CALLBACK,
    CALLBACK_SUPPLIER_RETURNED_CALLBACK,
    CALLBACK_SUPPLIER_UNSUPPORTED_CALLBACK_SUPPLY,
    CALLBACK_SUPPLIER_FINALLY_UNSUPPORTED,
    CALLBACK_SUPPLIER_ABRUPT_COMPLETION,
    CALLBACK_SUPPLIER_ANONYMOUS_IDENTITY_UNAVAILABLE,
    CALLBACK_SUPPLIER_UNRESOLVED_ARGUMENT_MAPPING,
    CALLBACK_SUPPLIER_UNRESOLVED_PARAMETER_REFERENCE,
    CALLBACK_SUPPLIER_EXTERNAL_CALLABLE,
    CALLBACK_SUPPLIER_OUTSIDE_DOMAIN,
    CALLBACK_SUPPLIER_PARAMETER_ESCAPES,
    CALLBACK_SUPPLIER_CALLBACK_CYCLE,
    CALLBACK_SUPPLIER_NESTED_CALLBACK_EXECUTION,
    CALLBACK_SUPPLIER_NO_INVOCATION_PROVEN,
    CALLBACK_SUPPLIER_WORK_LIMIT_REACHED,
    CALLBACK_SUPPLIER_TIME_LIMIT_REACHED,
    CALLBACK_SUPPLIER_RESULT_LIMIT_REACHED,
    CALLBACK_SUPPLIER_BYTE_LIMIT_REACHED,
    SEMANTIC_INPUT_READ_CAPTURE_ENDED,
    SEMANTIC_INPUT_PROJECT_UNAVAILABLE,
    SEMANTIC_INPUT_AUTHORITY_MOVED,
    SEMANTIC_INPUT_MODULE_UNAVAILABLE,
    SEMANTIC_INPUT_MODEL_INCOMPLETE,
    SEMANTIC_INPUT_MODEL_ROOT_MISMATCH,
    SEMANTIC_INPUT_DEPENDENCY_MODULE_UNMODELED,
    SEMANTIC_INPUT_DEPENDENCY_GRAPH_REJECTED,
    SEMANTIC_INPUT_DEPENDENCY_CLOSURE_REJECTED,
    SEMANTIC_INPUT_SOURCE_ROOT_INVENTORY_MISMATCH,
    SEMANTIC_INPUT_SOURCE_MODULE_INVENTORY_REJECTED,
    SEMANTIC_INPUT_SOURCE_INVENTORY_REJECTED,
    SEMANTIC_INPUT_RESOLUTION_INVENTORY_REJECTED,
    SEMANTIC_INPUT_COMPILER_CONFIGURATION_UNAVAILABLE,
    SEMANTIC_INPUT_COMPILER_DISTRIBUTION_UNMODELED,
    SEMANTIC_INPUT_COMPILER_PLUGIN_INPUTS_UNMODELED,
    SEMANTIC_INPUT_SOURCE_UNAVAILABLE,
    SEMANTIC_INPUT_SOURCE_DOCUMENT_DIRTY,
    SEMANTIC_INPUT_SOURCE_DOCUMENT_UNCOMMITTED,
    SEMANTIC_INPUT_PROVIDER_UNSUPPORTED,
    SEMANTIC_INPUT_UNAVAILABLE,
    SEMANTIC_INPUT_CAPACITY_EXCEEDED,
    SEMANTIC_INPUT_WORK_EXHAUSTED,
    SEMANTIC_INPUT_MINIMUM_HASH_WORK_UNAVAILABLE,
    SEMANTIC_INPUT_FILE_CAPTURE_ADMISSION_CONSUMED,
    SEMANTIC_INPUT_TIME_EXHAUSTED,
}

enum class IntellijReadStage {
    HOSTED,
    MODEL_CAPTURE,
    DISCOVERY,
    EXACT_REFINEMENT,
    RELATION,
    VALUE_FLOW,
    VALUE_PRODUCER_SEED,
    VALUE_MODEL_ADMISSION,
    SEMANTIC_DEPENDENCY_PREPARATION,
    VALUE_MODEL_SITE_ADMISSION,
    SOURCE,
    TRANSPORT,
}

/** Bounded effect phases; a phase proves entry, separately from successful drainage. */
enum class IntellijReadPhase {
    DISCOVERY_INVENTORY,
    DECLARATION_SCAN,
    EXACT_REFINEMENT,
    REFERENCE_INVENTORY,
    CALLER_REFERENCE_INVENTORY,
    TYPE_USE_REFERENCE_INVENTORY,
    REFERENCE_PARTITION,
    REFERENCE_CONFIRMATION,
    DEFINITION_INVENTORY,
    DEFINITION_CONFIRMATION,
    CALLEE_INVENTORY,
    CALLEE_CONFIRMATION,
    TRAVERSAL,
    VALUE_SITE_RESTORATION,
    PEER_SITE_ADMISSION,
    SOURCE_ENUMERATION,
    SEMANTIC_DEPENDENCY_PREPARATION,
    DIAGNOSTIC_SCOPE,
    CALLBACK_FORMAL_COVERAGE,
    CALLBACK_SUPPLIER_COVERAGE,
    DIAGNOSTIC_ENUMERATION,
    DIAGNOSTIC_ANALYSIS,
    FRESHNESS_VALIDATION,
    RETENTION,
    ENCODING,
    CANCELLATION_DRAINAGE,
}

/** Request-local diagnostic capability; owners choose whether to observe. */
interface IntellijReadObservation {
    fun enterCall(call: IntellijReadCall): IntellijReadCallScope = IntellijReadCallScope.None

    fun submitReadAction(kind: IntellijReadActionKind, mode: IntellijReadActionMode): IntellijReadActionScope =
        IntellijReadActionScope.None

    fun enterSearch(search: IntellijReadSearch): IntellijReadSearchScope {
        val call = enterCall(search.call)
        return object : IntellijReadSearchScope {
            override fun callbackEntered() = Unit

            override fun finish(outcome: IntellijReadCallOutcome) = call.finish(outcome)
        }
    }

    fun phase(value: IntellijReadPhase) {}

    fun unexpected(failure: IntellijReadUnexpectedFailure) {}

    fun measure(gauge: IntellijReadGauge, value: IntellijReadGaugeValue) {}

    fun count(
        counter: IntellijReadCounter,
        contributor: IntellijReadContributor = IntellijReadContributor.NONE,
        amount: Int = 1,
    )

    fun terminated(reason: IntellijReadTermination, contributor: IntellijReadContributor = IntellijReadContributor.NONE)

    data object None : IntellijReadObservation {
        override fun count(counter: IntellijReadCounter, contributor: IntellijReadContributor, amount: Int) = Unit

        override fun terminated(reason: IntellijReadTermination, contributor: IntellijReadContributor) = Unit
    }
}
