package io.github.amichne.kast.api.docs.internal

import io.github.amichne.kast.api.contract.*
import io.github.amichne.kast.api.contract.compatibility.*
import io.github.amichne.kast.api.contract.query.*
import io.github.amichne.kast.api.contract.result.*
import kotlinx.serialization.KSerializer

internal fun docsSchemaSerializers(): Map<String, KSerializer<*>> = mapOf(
    // System responses
    "HealthResponse" to HealthResponse.serializer(),
    "RuntimeStatusResponse" to RuntimeStatusResponse.serializer(),
    "RuntimeLifecycleResponse" to RuntimeLifecycleResponse.serializer(),
    "BackendCapabilities" to BackendCapabilities.serializer(),
    // Shared types
    "FilePosition" to FilePosition.serializer(),
    "Location" to Location.serializer(),
    "Symbol" to Symbol.serializer(),
    "ParameterInfo" to ParameterInfo.serializer(),
    "PageInfo" to PageInfo.serializer(),
    "SearchScope" to SearchScope.serializer(),
    "DeclarationScope" to DeclarationScope.serializer(),
    "ServerLimits" to ServerLimits.serializer(),
    "TextEdit" to TextEdit.serializer(),
    "FileHash" to FileHash.serializer(),
    "OutlineSymbol" to OutlineSymbol.serializer(),
    "WorkspaceModule" to WorkspaceModule.serializer(),
    // Runtime identity vocabulary
    "RuntimeImplementationVersion" to RuntimeImplementationVersion.serializer(),
    // Read queries & results
    "SymbolQuery" to SymbolQuery.serializer(),
    "SymbolResult" to SymbolResult.serializer(),
    "ReferencesQuery" to ReferencesQuery.serializer(),
    "ReferencesResult" to ReferencesResult.serializer(),
    "CallHierarchyQuery" to CallHierarchyQuery.serializer(),
    "CallHierarchyResult" to CallHierarchyResult.serializer(),
    "CallHierarchyStats" to CallHierarchyStats.serializer(),
    "CallNode" to CallNode.serializer(),
    "CallNodeTruncation" to CallNodeTruncation.serializer(),
    "TypeHierarchyQuery" to TypeHierarchyQuery.serializer(),
    "TypeHierarchyResult" to TypeHierarchyResult.serializer(),
    "TypeHierarchyNode" to TypeHierarchyNode.serializer(),
    "TypeHierarchyStats" to TypeHierarchyStats.serializer(),
    "TypeHierarchyTruncation" to TypeHierarchyTruncation.serializer(),
    "SemanticInsertionQuery" to SemanticInsertionQuery.serializer(),
    "SemanticInsertionResult" to SemanticInsertionResult.serializer(),
    "DiagnosticsQuery" to DiagnosticsQuery.serializer(),
    "DiagnosticsResult" to DiagnosticsResult.serializer(),
    "FileAnalysisStatus" to FileAnalysisStatus.serializer(),
    "Diagnostic" to Diagnostic.serializer(),
    "FileOutlineQuery" to FileOutlineQuery.serializer(),
    "FileOutlineResult" to FileOutlineResult.serializer(),
    "WorkspaceSymbolQuery" to WorkspaceSymbolQuery.serializer(),
    "WorkspaceSymbolResult" to WorkspaceSymbolResult.serializer(),
    "WorkspaceSearchQuery" to WorkspaceSearchQuery.serializer(),
    "SearchMatch" to SearchMatch.serializer(),
    "WorkspaceSearchResult" to WorkspaceSearchResult.serializer(),
    "WorkspaceFilesQuery" to WorkspaceFilesQuery.serializer(),
    "WorkspaceFilesResult" to WorkspaceFilesResult.serializer(),
    "SemanticGraphQuery" to SemanticGraphQuery.serializer(),
    "SemanticGraphResult" to SemanticGraphResult.serializer(),
    "WorkspaceFilesContinuationAction" to WorkspaceFilesContinuationAction.serializer(),
    "WorkspaceFilesContinuationQuery" to WorkspaceFilesContinuationQuery.serializer(),
    "WorkspaceFilesPublicContinuationIdentity" to WorkspaceFilesPublicContinuationIdentity.serializer(),
    "WorkspaceFilesPublicContinuationState" to WorkspaceFilesPublicContinuationState.serializer(),
    "WorkspaceFilesPublicContinuationProjection" to WorkspaceFilesPublicContinuationProjection.serializer(),
    "WorkspaceFilesContinuationResult" to WorkspaceFilesContinuationResult.serializer(),
    "WorkspaceFilesContinuationResult.Issued" to WorkspaceFilesContinuationResult.Issued.serializer(),
    "WorkspaceFilesContinuationResult.Consumed" to WorkspaceFilesContinuationResult.Consumed.serializer(),
    "ImplementationsQuery" to ImplementationsQuery.serializer(),
    "ImplementationsResult" to ImplementationsResult.serializer(),
    "CodeActionsQuery" to CodeActionsQuery.serializer(),
    "CodeActionsResult" to CodeActionsResult.serializer(),
    "CodeAction" to CodeAction.serializer(),
    "CompletionsQuery" to CompletionsQuery.serializer(),
    "CompletionsResult" to CompletionsResult.serializer(),
    "CompletionItem" to CompletionItem.serializer(),
    // Mutation queries & results
    "RenameQuery" to RenameQuery.serializer(),
    "RenameResult" to RenameResult.serializer(),
    "ImportOptimizeQuery" to ImportOptimizeQuery.serializer(),
    "ImportOptimizeResult" to ImportOptimizeResult.serializer(),
    "ApplyEditsQuery" to ApplyEditsQuery.serializer(),
    "ApplyEditsResult" to ApplyEditsResult.serializer(),
    "RefreshQuery" to RefreshQuery.serializer(),
    "RefreshResult" to RefreshResult.serializer(),
    "SemanticAdmissionStatus" to SemanticAdmissionStatus.serializer(),
    // FileOperation sealed hierarchy
    "FileOperation" to FileOperation.serializer(),
    "FileOperation.CreateFile" to FileOperation.CreateFile.serializer(),
    "FileOperation.DeleteFile" to FileOperation.DeleteFile.serializer(),
)
