package io.github.amichne.kast.api.docs.internal

import io.github.amichne.kast.api.contract.*
import io.github.amichne.kast.api.contract.compatibility.*
import io.github.amichne.kast.api.contract.query.*
import io.github.amichne.kast.api.contract.result.*
import kotlinx.serialization.KSerializer

internal fun docsSchemaSerializers(): Map<String, KSerializer<*>> = mapOf(
    // System responses
    "HealthResponse" to HealthResponse.serializer(),
    "RuntimeStatusResponse" to RuntimeStatusResponse.serializer(),
    "RuntimeReadiness" to RuntimeReadiness.serializer(),
    "RuntimeReadinessLane" to RuntimeReadinessLane.serializer(),
    "RuntimeReadinessLane.Ready" to RuntimeReadinessLane.Ready.serializer(),
    "RuntimeReadinessLane.InProgress" to RuntimeReadinessLane.InProgress.serializer(),
    "RuntimeReadinessLane.Blocked" to RuntimeReadinessLane.Blocked.serializer(),
    "RuntimeReadinessProgress" to RuntimeReadinessProgress.serializer(),
    "RuntimeProgressStage" to RuntimeProgressStage.serializer(),
    "PublishedWorkspaceGenerationStatus" to PublishedWorkspaceGenerationStatus.serializer(),
    "RuntimeLifecycleResponse" to RuntimeLifecycleResponse.serializer(),
    "BackendCapabilities" to BackendCapabilities.serializer(),
    // Shared types
    "FilePosition" to FilePosition.serializer(),
    "Location" to Location.serializer(),
    "Symbol" to Symbol.serializer(),
    "ParameterInfo" to ParameterInfo.serializer(),
    "PageInfo" to PageInfo.serializer(),
    "SearchScope" to SearchScope.serializer(),
    "DeclarationScope" to DeclarationScope.serializer(),
    "ServerLimits" to ServerLimits.serializer(),
    "TextEdit" to TextEdit.serializer(),
    "FileHash" to FileHash.serializer(),
    "OutlineSymbol" to OutlineSymbol.serializer(),
    "WorkspaceModule" to WorkspaceModule.serializer(),
    // Runtime identity vocabulary
    "RuntimeImplementationVersion" to RuntimeImplementationVersion.serializer(),
    // Read queries & results
    "SymbolQuery" to SymbolQuery.serializer(),
    "SymbolResult" to SymbolResult.serializer(),
    "ReferencesQuery" to ReferencesQuery.serializer(),
    "ReferencesResult" to ReferencesResult.serializer(),
    "CallHierarchyQuery" to CallHierarchyQuery.serializer(),
    "CallHierarchyResult" to CallHierarchyResult.serializer(),
    "CallHierarchyStats" to CallHierarchyStats.serializer(),
    "CallNode" to CallNode.serializer(),
    "CallNodeTruncation" to CallNodeTruncation.serializer(),
    "TypeHierarchyQuery" to TypeHierarchyQuery.serializer(),
    "TypeHierarchyResult" to TypeHierarchyResult.serializer(),
    "TypeHierarchyNode" to TypeHierarchyNode.serializer(),
    "TypeHierarchyStats" to TypeHierarchyStats.serializer(),
    "TypeHierarchyTruncation" to TypeHierarchyTruncation.serializer(),
    "SemanticInsertionQuery" to SemanticInsertionQuery.serializer(),
    "SemanticInsertionResult" to SemanticInsertionResult.serializer(),
    "DiagnosticsQuery" to DiagnosticsQuery.serializer(),
    "DiagnosticsResult" to DiagnosticsResult.serializer(),
    "FileAnalysisStatus" to FileAnalysisStatus.serializer(),
    "Diagnostic" to Diagnostic.serializer(),
    "FileOutlineQuery" to FileOutlineQuery.serializer(),
    "FileOutlineResult" to FileOutlineResult.serializer(),
    "WorkspaceSymbolQuery" to WorkspaceSymbolQuery.serializer(),
    "WorkspaceSymbolResult" to WorkspaceSymbolResult.serializer(),
    "WorkspaceSearchQuery" to WorkspaceSearchQuery.serializer(),
    "SearchMatch" to SearchMatch.serializer(),
    "WorkspaceSearchResult" to WorkspaceSearchResult.serializer(),
    "WorkspaceFilesQuery" to WorkspaceFilesQuery.serializer(),
    "WorkspaceFilesResult" to WorkspaceFilesResult.serializer(),
    "SemanticGraphQuery" to SemanticGraphQuery.serializer(),
    "SemanticGraphResult" to SemanticGraphResult.serializer(),
    "WorkspaceFilesContinuationAction" to WorkspaceFilesContinuationAction.serializer(),
    "WorkspaceFilesContinuationQuery" to WorkspaceFilesContinuationQuery.serializer(),
    "WorkspaceFilesPublicContinuationIdentity" to WorkspaceFilesPublicContinuationIdentity.serializer(),
    "WorkspaceFilesPublicContinuationState" to WorkspaceFilesPublicContinuationState.serializer(),
    "WorkspaceFilesPublicContinuationProjection" to WorkspaceFilesPublicContinuationProjection.serializer(),
    "WorkspaceFilesContinuationResult" to WorkspaceFilesContinuationResult.serializer(),
    "WorkspaceFilesContinuationResult.Issued" to WorkspaceFilesContinuationResult.Issued.serializer(),
    "WorkspaceFilesContinuationResult.Consumed" to WorkspaceFilesContinuationResult.Consumed.serializer(),
    "ImplementationsQuery" to ImplementationsQuery.serializer(),
    "ImplementationsResult" to ImplementationsResult.serializer(),
    "CodeActionsQuery" to CodeActionsQuery.serializer(),
    "CodeActionsResult" to CodeActionsResult.serializer(),
    "CodeAction" to CodeAction.serializer(),
    "CompletionsQuery" to CompletionsQuery.serializer(),
    "CompletionsResult" to CompletionsResult.serializer(),
    "CompletionItem" to CompletionItem.serializer(),
    // Mutation queries & results
    "RenameQuery" to RenameQuery.serializer(),
    "RenameResult" to RenameResult.serializer(),
    "ReplacementPlanQuery" to ReplacementPlanQuery.serializer(),
    "ReplacementPlanResult" to ReplacementPlanResult.serializer(),
    "AddFilePlanQuery" to AddFilePlanQuery.serializer(),
    "AddFilePlanResult" to AddFilePlanResult.serializer(),
    "AddDeclarationPlanQuery" to AddDeclarationPlanQuery.serializer(),
    "AddDeclarationPlanResult" to AddDeclarationPlanResult.serializer(),
    "MutationPostconditionQuery" to MutationPostconditionQuery.serializer(),
    "MutationPostconditionAuthority" to MutationPostconditionAuthority.serializer(),
    "MutationPostconditionAuthority.Rename" to MutationPostconditionAuthority.Rename.serializer(),
    "MutationPostconditionAuthority.Replacement" to MutationPostconditionAuthority.Replacement.serializer(),
    "MutationPostconditionAuthority.AddFile" to MutationPostconditionAuthority.AddFile.serializer(),
    "MutationPostconditionAuthority.AddDeclaration" to MutationPostconditionAuthority.AddDeclaration.serializer(),
    "MutationPostconditionResult" to MutationPostconditionResult.serializer(),
    "MutationPostconditionEvidence" to MutationPostconditionEvidence.serializer(),
    "MutationPostconditionEvidence.Rename" to MutationPostconditionEvidence.Rename.serializer(),
    "MutationPostconditionEvidence.Replacement" to MutationPostconditionEvidence.Replacement.serializer(),
    "MutationPostconditionEvidence.AddFile" to MutationPostconditionEvidence.AddFile.serializer(),
    "MutationPostconditionEvidence.AddDeclaration" to MutationPostconditionEvidence.AddDeclaration.serializer(),
    "RawExactFileObservationQuery" to RawExactFileObservationQuery.serializer(),
    "RawExactFileObservationResult" to RawExactFileObservationResult.serializer(),
    "RawExactFileObservationResult.Absent" to RawExactFileObservationResult.Absent.serializer(),
    "RawExactFileObservationResult.Present" to RawExactFileObservationResult.Present.serializer(),
    "ExactFileImageQuery" to ExactFileImageQuery.serializer(),
    "ExactFileImageResult" to ExactFileImageResult.serializer(),
    "MutationScratchInspectQuery" to MutationScratchInspectQuery.serializer(),
    "MutationScratchInspectResult" to MutationScratchInspectResult.serializer(),
    "MutationScratchRecoveryQuery" to MutationScratchRecoveryQuery.serializer(),
    "MutationScratchRecoveryPreimage" to MutationScratchRecoveryPreimage.serializer(),
    "MutationScratchRecoveryPreimage.Absent" to MutationScratchRecoveryPreimage.Absent.serializer(),
    "MutationScratchRecoveryPreimage.Present" to MutationScratchRecoveryPreimage.Present.serializer(),
    "MutationScratchRecoveryResult" to MutationScratchRecoveryResult.serializer(),
    "ImportOptimizeQuery" to ImportOptimizeQuery.serializer(),
    "ImportOptimizeResult" to ImportOptimizeResult.serializer(),
    "ApplyEditsQuery" to ApplyEditsQuery.serializer(),
    "ApplyEditsResult" to ApplyEditsResult.serializer(),
    "RefreshQuery" to RefreshQuery.serializer(),
    "RefreshResult" to RefreshResult.serializer(),
    "SemanticAdmissionStatus" to SemanticAdmissionStatus.serializer(),
    // FileOperation sealed hierarchy
    "FileOperation" to FileOperation.serializer(),
    "FileOperation.CreateFile" to FileOperation.CreateFile.serializer(),
    "FileOperation.DeleteFile" to FileOperation.DeleteFile.serializer(),
)
