package io.github.amichne.kast.api.docs.internal

internal fun openApiPaths(): Map<String, Any?> = linkedMapOf(
    // System
    "/rpc/health" to systemMethod(
        operationId = "health",
        summary = "Basic health check",
        method = "health",
        responseSchema = "HealthResponse",
    ),
    "/rpc/runtime-status" to systemMethod(
        operationId = "runtimeStatus",
        summary = "Detailed runtime state including indexing progress",
        method = "runtime/status",
        responseSchema = "RuntimeStatusResponse",
    ),
    "/rpc/capabilities" to systemMethod(
        operationId = "capabilities",
        summary = "Advertised read and mutation capabilities",
        method = "capabilities",
        responseSchema = "BackendCapabilities",
    ),

    // Read operations
    "/rpc/raw/resolve" to readMethod(
        operationId = "resolveSymbol",
        summary = "Resolve the symbol at a file position",
        method = "raw/resolve",
        requestSchema = "SymbolQuery",
        responseSchema = "SymbolResult",
        capability = "RESOLVE_SYMBOL",
    ),
    "/rpc/raw/references" to readMethod(
        operationId = "findReferences",
        summary = "Find all references to the symbol at a file position",
        method = "raw/references",
        requestSchema = "ReferencesQuery",
        responseSchema = "ReferencesResult",
        capability = "FIND_REFERENCES",
    ),
    "/rpc/raw/call-hierarchy" to readMethod(
        operationId = "callHierarchy",
        summary = "Expand a bounded incoming or outgoing call tree",
        method = "raw/call-hierarchy",
        requestSchema = "CallHierarchyQuery",
        responseSchema = "CallHierarchyResult",
        capability = "CALL_HIERARCHY",
    ),
    "/rpc/raw/type-hierarchy" to readMethod(
        operationId = "typeHierarchy",
        summary = "Expand supertypes and subtypes from a resolved symbol",
        method = "raw/type-hierarchy",
        requestSchema = "TypeHierarchyQuery",
        responseSchema = "TypeHierarchyResult",
        capability = "TYPE_HIERARCHY",
    ),
    "/rpc/raw/semantic-insertion-point" to readMethod(
        operationId = "semanticInsertionPoint",
        summary = "Find the best insertion point for a new declaration",
        method = "raw/semantic-insertion-point",
        requestSchema = "SemanticInsertionQuery",
        responseSchema = "SemanticInsertionResult",
        capability = "SEMANTIC_INSERTION_POINT",
    ),
    "/rpc/raw/diagnostics" to readMethod(
        operationId = "diagnostics",
        summary = "Run compilation diagnostics for one or more files",
        method = "raw/diagnostics",
        requestSchema = "DiagnosticsQuery",
        responseSchema = "DiagnosticsResult",
        capability = "DIAGNOSTICS",
    ),
    "/rpc/raw/file-outline" to readMethod(
        operationId = "fileOutline",
        summary = "Get a hierarchical symbol outline for a single file",
        method = "raw/file-outline",
        requestSchema = "FileOutlineQuery",
        responseSchema = "FileOutlineResult",
        capability = "FILE_OUTLINE",
    ),
    "/rpc/raw/workspace-symbol" to readMethod(
        operationId = "workspaceSymbolSearch",
        summary = "Search the workspace for symbols by name pattern",
        method = "raw/workspace-symbol",
        requestSchema = "WorkspaceSymbolQuery",
        responseSchema = "WorkspaceSymbolResult",
        capability = "WORKSPACE_SYMBOL_SEARCH",
    ),
    "/rpc/raw/workspace-search" to readMethod(
        operationId = "workspaceSearch",
        summary = "Search workspace file contents for text patterns",
        method = "raw/workspace-search",
        requestSchema = "WorkspaceSearchQuery",
        responseSchema = "WorkspaceSearchResult",
        capability = "WORKSPACE_SEARCH",
    ),
    "/rpc/raw/workspace-files" to readMethod(
        operationId = "workspaceFiles",
        summary = "List workspace modules and optional source files",
        method = "raw/workspace-files",
        requestSchema = "WorkspaceFilesQuery",
        responseSchema = "WorkspaceFilesResult",
        capability = "WORKSPACE_FILES",
    ),
    "/rpc/raw/semantic-graph" to readMethod(
        operationId = "semanticGraph",
        summary = "Export a compiler-backed Kotlin semantic graph page",
        method = "raw/semantic-graph",
        requestSchema = "SemanticGraphQuery",
        responseSchema = "SemanticGraphResult",
        capability = "SEMANTIC_GRAPH",
    ),
    "/rpc/raw/workspace-files-continuation" to internalReadMethod(
        operationId = "workspaceFilesContinuation",
        summary = "Issue or consume server-held public workspace-file continuation state",
        method = "raw/workspace-files-continuation",
        requestSchema = "WorkspaceFilesContinuationQuery",
        responseSchema = "WorkspaceFilesContinuationResult",
    ),
    "/rpc/raw/implementations" to readMethod(
        operationId = "implementations",
        summary = "Find concrete implementations and subclasses for a declaration",
        method = "raw/implementations",
        requestSchema = "ImplementationsQuery",
        responseSchema = "ImplementationsResult",
        capability = "IMPLEMENTATIONS",
    ),
    "/rpc/raw/code-actions" to readMethod(
        operationId = "codeActions",
        summary = "Return available code actions at a file position",
        method = "raw/code-actions",
        requestSchema = "CodeActionsQuery",
        responseSchema = "CodeActionsResult",
        capability = "CODE_ACTIONS",
    ),
    "/rpc/raw/completions" to readMethod(
        operationId = "completions",
        summary = "Return completion candidates available at a file position",
        method = "raw/completions",
        requestSchema = "CompletionsQuery",
        responseSchema = "CompletionsResult",
        capability = "COMPLETIONS",
    ),

    // Mutation operations
    "/rpc/raw/rename" to mutationMethod(
        operationId = "rename",
        summary = "Plan a symbol rename (dry-run by default)",
        method = "raw/rename",
        requestSchema = "RenameQuery",
        responseSchema = "RenameResult",
        capability = "RENAME",
    ),
    "/rpc/raw/plan-replacement" to mutationMethod(
        operationId = "planReplacement",
        summary = "Plan an identity-preserving function-body replacement",
        method = "raw/plan-replacement",
        requestSchema = "ReplacementPlanQuery",
        responseSchema = "ReplacementPlanResult",
        capability = "PLAN_REPLACEMENT",
    ),
    "/rpc/raw/plan-add-file" to mutationMethod(
        operationId = "planAddFile",
        summary = "Plan a compiler-proven Kotlin source file addition",
        method = "raw/plan-add-file",
        requestSchema = "AddFilePlanQuery",
        responseSchema = "AddFilePlanResult",
        capability = "PLAN_ADD_FILE",
    ),
    "/rpc/raw/verify-mutation-postcondition" to mutationMethod(
        operationId = "verifyMutationPostcondition",
        summary = "Verify one exact mutation postcondition",
        method = "raw/verify-mutation-postcondition",
        requestSchema = "MutationPostconditionQuery",
        responseSchema = "MutationPostconditionResult",
        capability = "VERIFY_MUTATION_POSTCONDITION",
    ),
    "/rpc/raw/exact-file-observation" to mutationMethod(
        operationId = "exactFileObservation",
        summary = "Observe one file as an exact byte image or proven absence",
        method = "raw/exact-file-observation",
        requestSchema = "RawExactFileObservationQuery",
        responseSchema = "RawExactFileObservationResult",
        capability = "EXACT_FILE_OBSERVATION",
    ),
    "/rpc/raw/exact-file-image-cas" to mutationMethod(
        operationId = "exactFileImageCas",
        summary = "Commit one exact file byte image with compare-and-swap",
        method = "raw/exact-file-image-cas",
        requestSchema = "ExactFileImageQuery",
        responseSchema = "ExactFileImageResult",
        capability = "EXACT_FILE_IMAGE_CAS",
    ),
    "/rpc/raw/inspect-mutation-scratch" to mutationMethod(
        operationId = "inspectMutationScratch",
        summary = "Fence a mutation attempt and inspect its exact scratch namespace",
        method = "raw/inspect-mutation-scratch",
        requestSchema = "MutationScratchInspectQuery",
        responseSchema = "MutationScratchInspectResult",
        capability = "MUTATION_SCRATCH_RECOVERY",
    ),
    "/rpc/raw/recover-mutation-scratch" to mutationMethod(
        operationId = "recoverMutationScratch",
        summary = "Restore or finalize one journal-owned mutation scratch set",
        method = "raw/recover-mutation-scratch",
        requestSchema = "MutationScratchRecoveryQuery",
        responseSchema = "MutationScratchRecoveryResult",
        capability = "MUTATION_SCRATCH_RECOVERY",
    ),
    "/rpc/raw/optimize-imports" to mutationMethod(
        operationId = "optimizeImports",
        summary = "Optimize imports for one or more files",
        method = "raw/optimize-imports",
        requestSchema = "ImportOptimizeQuery",
        responseSchema = "ImportOptimizeResult",
        capability = "OPTIMIZE_IMPORTS",
    ),
    "/rpc/raw/apply-edits" to mutationMethod(
        operationId = "applyEdits",
        summary = "Apply a prepared edit plan with file-hash conflict detection",
        method = "raw/apply-edits",
        requestSchema = "ApplyEditsQuery",
        responseSchema = "ApplyEditsResult",
        capability = "APPLY_EDITS",
        extraExtensions = mapOf(
            "x-kast-conditional-capability" to "FILE_OPERATIONS — required when fileOperations is non-empty",
        ),
    ),
    "/rpc/raw/workspace-refresh" to mutationMethod(
        operationId = "refreshWorkspace",
        summary = "Force a targeted or full workspace state refresh",
        method = "raw/workspace-refresh",
        requestSchema = "RefreshQuery",
        responseSchema = "RefreshResult",
        capability = "REFRESH_WORKSPACE",
    ),
)
